module MetronomeSDK
  module Models
    module V1
      type billable_metric_list_params =
        { include_archived: bool, limit: Integer, next_page: String }
        & MetronomeSDK::request_parameters

      class BillableMetricListParams < MetronomeSDK::BaseModel
        extend MetronomeSDK::RequestParameters::Converter
        include MetronomeSDK::RequestParameters

        attr_reader include_archived: bool?

        def include_archived=: (bool) -> bool

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader next_page: String?

        def next_page=: (String) -> String

        def initialize:
          (
            include_archived: bool,
            limit: Integer,
            next_page: String,
            request_options: MetronomeSDK::request_opts
          ) -> void
          | (
            ?MetronomeSDK::Models::V1::billable_metric_list_params
            | MetronomeSDK::BaseModel data
          ) -> void

        def to_hash: -> MetronomeSDK::Models::V1::billable_metric_list_params
      end
    end
  end
end
