module MetronomeSDK
  module Models
    module V1
      type billable_metric_archive_params =
        {  } & MetronomeSDK::request_parameters

      class BillableMetricArchiveParams < MetronomeSDK::Models::ID
        extend MetronomeSDK::RequestParameters::Converter
        include MetronomeSDK::RequestParameters

        def initialize:
          (request_options: MetronomeSDK::request_opts) -> void
          | (
            ?MetronomeSDK::Models::V1::billable_metric_archive_params
            | MetronomeSDK::BaseModel data
          ) -> void

        def to_hash: -> MetronomeSDK::Models::V1::billable_metric_archive_params
      end
    end
  end
end
