module MetronomeSDK
  module Models
    module V1
      type billable_metric_archive_response = { data: MetronomeSDK::Models::ID }

      class BillableMetricArchiveResponse < MetronomeSDK::BaseModel
        attr_accessor data: MetronomeSDK::Models::ID

        def initialize:
          (data: MetronomeSDK::Models::ID) -> void
          | (
            ?MetronomeSDK::Models::V1::billable_metric_archive_response
            | MetronomeSDK::BaseModel data
          ) -> void

        def to_hash: -> MetronomeSDK::Models::V1::billable_metric_archive_response
      end
    end
  end
end
