module MetronomeSDK
  module Models
    module V1
      type contract_schedule_pro_services_invoice_response =
        { data: ::Array[MetronomeSDK::Models::V1::Customers::Invoice] }

      class ContractScheduleProServicesInvoiceResponse < MetronomeSDK::BaseModel
        attr_accessor data: ::Array[MetronomeSDK::Models::V1::Customers::Invoice]

        def initialize:
          (data: ::Array[MetronomeSDK::Models::V1::Customers::Invoice]) -> void
          | (
            ?MetronomeSDK::Models::V1::contract_schedule_pro_services_invoice_response
            | MetronomeSDK::BaseModel data
          ) -> void

        def to_hash: -> MetronomeSDK::Models::V1::contract_schedule_pro_services_invoice_response
      end
    end
  end
end
