module MetronomeSDK
  module Models
    module V1
      type custom_field_add_key_params =
        {
          enforce_uniqueness: bool,
          entity: MetronomeSDK::Models::V1::CustomFieldAddKeyParams::entity,
          key: String
        }
        & MetronomeSDK::request_parameters

      class CustomFieldAddKeyParams < MetronomeSDK::BaseModel
        extend MetronomeSDK::RequestParameters::Converter
        include MetronomeSDK::RequestParameters

        attr_accessor enforce_uniqueness: bool

        attr_accessor entity: MetronomeSDK::Models::V1::CustomFieldAddKeyParams::entity

        attr_accessor key: String

        def initialize:
          (
            enforce_uniqueness: bool,
            entity: MetronomeSDK::Models::V1::CustomFieldAddKeyParams::entity,
            key: String,
            request_options: MetronomeSDK::request_opts
          ) -> void
          | (
            ?MetronomeSDK::Models::V1::custom_field_add_key_params
            | MetronomeSDK::BaseModel data
          ) -> void

        def to_hash: -> MetronomeSDK::Models::V1::custom_field_add_key_params

        type entity =
          :alert
          | :billable_metric
          | :charge
          | :commit
          | :contract_credit
          | :contract_product
          | :contract
          | :credit_grant
          | :customer_plan
          | :customer
          | :discount
          | :invoice
          | :plan
          | :professional_service
          | :product
          | :rate_card
          | :scheduled_charge
          | :subscription

        class Entity < MetronomeSDK::Enum
          ALERT: :alert
          BILLABLE_METRIC: :billable_metric
          CHARGE: :charge
          COMMIT: :commit
          CONTRACT_CREDIT: :contract_credit
          CONTRACT_PRODUCT: :contract_product
          CONTRACT: :contract
          CREDIT_GRANT: :credit_grant
          CUSTOMER_PLAN: :customer_plan
          CUSTOMER: :customer
          DISCOUNT: :discount
          INVOICE: :invoice
          PLAN: :plan
          PROFESSIONAL_SERVICE: :professional_service
          PRODUCT: :product
          RATE_CARD: :rate_card
          SCHEDULED_CHARGE: :scheduled_charge
          SUBSCRIPTION: :subscription

          def self.values: -> ::Array[MetronomeSDK::Models::V1::CustomFieldAddKeyParams::entity]
        end
      end
    end
  end
end
