module MetronomeSDK
  module Models
    module V1
      type customer_set_name_params =
        { customer_id: String, name: String } & MetronomeSDK::request_parameters

      class CustomerSetNameParams < MetronomeSDK::BaseModel
        extend MetronomeSDK::RequestParameters::Converter
        include MetronomeSDK::RequestParameters

        attr_accessor customer_id: String

        attr_accessor name: String

        def initialize:
          (
            customer_id: String,
            name: String,
            request_options: MetronomeSDK::request_opts
          ) -> void
          | (
            ?MetronomeSDK::Models::V1::customer_set_name_params
            | MetronomeSDK::BaseModel data
          ) -> void

        def to_hash: -> MetronomeSDK::Models::V1::customer_set_name_params
      end
    end
  end
end
