module MetronomeSDK
  module Models
    module V1
      type invoice_regenerate_params =
        { id: String } & MetronomeSDK::request_parameters

      class InvoiceRegenerateParams < MetronomeSDK::BaseModel
        extend MetronomeSDK::RequestParameters::Converter
        include MetronomeSDK::RequestParameters

        attr_accessor id: String

        def initialize:
          (id: String, request_options: MetronomeSDK::request_opts) -> void
          | (
            ?MetronomeSDK::Models::V1::invoice_regenerate_params
            | MetronomeSDK::BaseModel data
          ) -> void

        def to_hash: -> MetronomeSDK::Models::V1::invoice_regenerate_params
      end
    end
  end
end
