module MetronomeSDK
  module Models
    module V1
      type rollover_amount_max_amount =
        {
          type: MetronomeSDK::Models::V1::RolloverAmountMaxAmount::type_,
          value: Float
        }

      class RolloverAmountMaxAmount < MetronomeSDK::BaseModel
        attr_accessor type: MetronomeSDK::Models::V1::RolloverAmountMaxAmount::type_

        attr_accessor value: Float

        def initialize:
          (
            type: MetronomeSDK::Models::V1::RolloverAmountMaxAmount::type_,
            value: Float
          ) -> void
          | (
            ?MetronomeSDK::Models::V1::rollover_amount_max_amount
            | MetronomeSDK::BaseModel data
          ) -> void

        def to_hash: -> MetronomeSDK::Models::V1::rollover_amount_max_amount

        type type_ = :MAX_AMOUNT

        class Type < MetronomeSDK::Enum
          MAX_AMOUNT: :MAX_AMOUNT

          def self.values: -> ::Array[MetronomeSDK::Models::V1::RolloverAmountMaxAmount::type_]
        end
      end
    end
  end
end
