module MetronomeSDK
  module Models
    module V1
      type usage_ingest_params =
        { usage: ::Array[MetronomeSDK::Models::V1::UsageIngestParams::Usage] }
        & MetronomeSDK::request_parameters

      class UsageIngestParams < MetronomeSDK::BaseModel
        extend MetronomeSDK::RequestParameters::Converter
        include MetronomeSDK::RequestParameters

        attr_reader usage: ::Array[MetronomeSDK::Models::V1::UsageIngestParams::Usage]?

        def usage=: (
          ::Array[MetronomeSDK::Models::V1::UsageIngestParams::Usage]
        ) -> ::Array[MetronomeSDK::Models::V1::UsageIngestParams::Usage]

        def initialize:
          (
            usage: ::Array[MetronomeSDK::Models::V1::UsageIngestParams::Usage],
            request_options: MetronomeSDK::request_opts
          ) -> void
          | (
            ?MetronomeSDK::Models::V1::usage_ingest_params
            | MetronomeSDK::BaseModel data
          ) -> void

        def to_hash: -> MetronomeSDK::Models::V1::usage_ingest_params

        type usage =
          {
            customer_id: String,
            event_type: String,
            timestamp: String,
            transaction_id: String,
            properties: ::Hash[Symbol, top]
          }

        class Usage < MetronomeSDK::BaseModel
          attr_accessor customer_id: String

          attr_accessor event_type: String

          attr_accessor timestamp: String

          attr_accessor transaction_id: String

          attr_reader properties: ::Hash[Symbol, top]?

          def properties=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

          def initialize:
            (
              customer_id: String,
              event_type: String,
              timestamp: String,
              transaction_id: String,
              properties: ::Hash[Symbol, top]
            ) -> void
            | (
              ?MetronomeSDK::Models::V1::UsageIngestParams::usage
              | MetronomeSDK::BaseModel data
            ) -> void

          def to_hash: -> MetronomeSDK::Models::V1::UsageIngestParams::usage
        end
      end
    end
  end
end
