module MetronomeSDK
  module Models
    module V1
      module Customers
        type invoice_add_charge_response = {  }

        class InvoiceAddChargeResponse < MetronomeSDK::BaseModel
          def initialize:
            -> void
            | (
              ?MetronomeSDK::Models::V1::Customers::invoice_add_charge_response
              | MetronomeSDK::BaseModel data
            ) -> void

          def to_hash: -> MetronomeSDK::Models::V1::Customers::invoice_add_charge_response
        end
      end
    end
  end
end
