module MetronomeSDK
  module Models
    module V1
      module Customers
        type plan_add_response = { data: MetronomeSDK::Models::ID }

        class PlanAddResponse < MetronomeSDK::BaseModel
          attr_accessor data: MetronomeSDK::Models::ID

          def initialize:
            (data: MetronomeSDK::Models::ID) -> void
            | (
              ?MetronomeSDK::Models::V1::Customers::plan_add_response
              | MetronomeSDK::BaseModel data
            ) -> void

          def to_hash: -> MetronomeSDK::Models::V1::Customers::plan_add_response
        end
      end
    end
  end
end
