module MetronomeSDK
  module Models
    module V2
      module Notifications
        type offset_create_response =
          { data: MetronomeSDK::V2::LifecycleEventOffsetNotificationConfig }

        class OffsetCreateResponse < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor data: MetronomeSDK::V2::LifecycleEventOffsetNotificationConfig

          def initialize: (
            data: MetronomeSDK::V2::LifecycleEventOffsetNotificationConfig
          ) -> void

          def to_hash: -> {
            data: MetronomeSDK::V2::LifecycleEventOffsetNotificationConfig
          }
        end
      end
    end
  end
end
