module MetronomeSDK
  module Resources
    class V1
      class Contracts
        class RateCards
          class NamedSchedules
            def retrieve:
              (
                MetronomeSDK::Models::V1::Contracts::RateCards::NamedScheduleRetrieveParams
                | ::Hash[Symbol, top] params
              ) -> MetronomeSDK::Models::V1::Contracts::RateCards::NamedScheduleRetrieveResponse
              | (
                contract_id: String,
                customer_id: String,
                schedule_name: String,
                covering_date: Time,
                request_options: MetronomeSDK::request_opts
              ) -> MetronomeSDK::Models::V1::Contracts::RateCards::NamedScheduleRetrieveResponse

            def update:
              (
                MetronomeSDK::Models::V1::Contracts::RateCards::NamedScheduleUpdateParams
                | ::Hash[Symbol, top] params
              ) -> nil
              | (
                contract_id: String,
                customer_id: String,
                schedule_name: String,
                starting_at: Time,
                value: top,
                ending_before: Time,
                request_options: MetronomeSDK::request_opts
              ) -> nil

            def initialize: (client: MetronomeSDK::Client) -> void
          end
        end
      end
    end
  end
end
