module MetronomeSDK
  module Resources
    class V1
      class Contracts
        class RateCards
          class ProductOrders
            def update:
              (
                MetronomeSDK::Models::V1::Contracts::RateCards::ProductOrderUpdateParams
                | ::Hash[Symbol, top] params
              ) -> MetronomeSDK::Models::V1::Contracts::RateCards::ProductOrderUpdateResponse
              | (
                product_moves: ::Array[MetronomeSDK::Models::V1::Contracts::RateCards::ProductOrderUpdateParams::ProductMove],
                rate_card_id: String,
                request_options: MetronomeSDK::request_opts
              ) -> MetronomeSDK::Models::V1::Contracts::RateCards::ProductOrderUpdateResponse

            def set:
              (
                MetronomeSDK::Models::V1::Contracts::RateCards::ProductOrderSetParams
                | ::Hash[Symbol, top] params
              ) -> MetronomeSDK::Models::V1::Contracts::RateCards::ProductOrderSetResponse
              | (
                product_order: ::Array[String],
                rate_card_id: String,
                request_options: MetronomeSDK::request_opts
              ) -> MetronomeSDK::Models::V1::Contracts::RateCards::ProductOrderSetResponse

            def initialize: (client: MetronomeSDK::Client) -> void
          end
        end
      end
    end
  end
end
