module MetronomeSDK
  module Models
    module V1
      module Contracts
        type named_schedule_retrieve_params =
          { rate_card_id: String, schedule_name: String, covering_date: Time }
          & MetronomeSDK::Internal::Type::request_parameters

        class NamedScheduleRetrieveParams < MetronomeSDK::Internal::Type::BaseModel
          extend MetronomeSDK::Internal::Type::RequestParameters::Converter
          include MetronomeSDK::Internal::Type::RequestParameters

          attr_accessor rate_card_id: String

          attr_accessor schedule_name: String

          attr_reader covering_date: Time?

          def covering_date=: (Time) -> Time

          def initialize: (
            rate_card_id: String,
            schedule_name: String,
            ?covering_date: Time,
            ?request_options: MetronomeSDK::request_opts
          ) -> void
        end
      end
    end
  end
end
