module MetronomeSDK
  module Models
    module V1
      module Contracts
        type product_create_response = { data: MetronomeSDK::ID }

        class ProductCreateResponse < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor data: MetronomeSDK::ID

          def initialize: (data: MetronomeSDK::ID) -> void

          def to_hash: -> { data: MetronomeSDK::ID }
        end
      end
    end
  end
end
