module MetronomeSDK
  module Models
    module V1
      module Contracts
        type rate_card_archive_response =
          {
            data: MetronomeSDK::Models::V1::Contracts::RateCardArchiveResponse::Data
          }

        class RateCardArchiveResponse < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor data: MetronomeSDK::Models::V1::Contracts::RateCardArchiveResponse::Data

          def initialize: (
            data: MetronomeSDK::Models::V1::Contracts::RateCardArchiveResponse::Data
          ) -> void

          def to_hash: -> {
            data: MetronomeSDK::Models::V1::Contracts::RateCardArchiveResponse::Data
          }

          type data = { id: String }

          class Data < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor id: String

            def initialize: (id: String) -> void

            def to_hash: -> { id: String }
          end
        end
      end
    end
  end
end
