module MetronomeSDK
  module Models
    module V1
      module Contracts
        type rate_card_archive_params =
          {  } & MetronomeSDK::Internal::Type::request_parameters

        class RateCardArchiveParams < MetronomeSDK::Models::ID
          extend MetronomeSDK::Internal::Type::RequestParameters::Converter
          include MetronomeSDK::Internal::Type::RequestParameters

          def initialize: (?request_options: MetronomeSDK::request_opts) -> void

          def to_hash: -> MetronomeSDK::Models::V1::Contracts::rate_card_archive_params
        end
      end
    end
  end
end
