module MetronomeSDK
  module Models
    module V1
      module Contracts
        type rate_card_archive_response = { data: MetronomeSDK::Models::ID }

        class RateCardArchiveResponse < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor data: MetronomeSDK::Models::ID

          def initialize: (data: MetronomeSDK::Models::ID) -> void

          def to_hash: -> MetronomeSDK::Models::V1::Contracts::rate_card_archive_response
        end
      end
    end
  end
end
