module MetronomeSDK
  module Models
    module V1
      module Contracts
        type rate_card_retrieve_response =
          {
            data: MetronomeSDK::Models::V1::Contracts::RateCardRetrieveResponse::Data
          }

        class RateCardRetrieveResponse < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor data: MetronomeSDK::Models::V1::Contracts::RateCardRetrieveResponse::Data

          def initialize: (
            data: MetronomeSDK::Models::V1::Contracts::RateCardRetrieveResponse::Data
          ) -> void

          type data =
            {
              id: String,
              created_at: Time,
              created_by: String,
              name: String,
              aliases: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveResponse::Data::Alias],
              credit_type_conversions: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveResponse::Data::CreditTypeConversion],
              custom_fields: ::Hash[Symbol, String],
              description: String,
              fiat_credit_type: MetronomeSDK::CreditTypeData
            }

          class Data < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor created_at: Time

            attr_accessor created_by: String

            attr_accessor name: String

            attr_reader aliases: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveResponse::Data::Alias]?

            def aliases=: (
              ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveResponse::Data::Alias]
            ) -> ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveResponse::Data::Alias]

            attr_reader credit_type_conversions: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveResponse::Data::CreditTypeConversion]?

            def credit_type_conversions=: (
              ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveResponse::Data::CreditTypeConversion]
            ) -> ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveResponse::Data::CreditTypeConversion]

            attr_reader custom_fields: ::Hash[Symbol, String]?

            def custom_fields=: (
              ::Hash[Symbol, String]
            ) -> ::Hash[Symbol, String]

            attr_reader description: String?

            def description=: (String) -> String

            attr_reader fiat_credit_type: MetronomeSDK::CreditTypeData?

            def fiat_credit_type=: (
              MetronomeSDK::CreditTypeData
            ) -> MetronomeSDK::CreditTypeData

            def initialize: (
              id: String,
              created_at: Time,
              created_by: String,
              name: String,
              ?aliases: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveResponse::Data::Alias],
              ?credit_type_conversions: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveResponse::Data::CreditTypeConversion],
              ?custom_fields: ::Hash[Symbol, String],
              ?description: String,
              ?fiat_credit_type: MetronomeSDK::CreditTypeData
            ) -> void

            type alias_ =
              { name: String, ending_before: Time, starting_at: Time }

            class Alias < MetronomeSDK::Internal::Type::BaseModel
              attr_accessor name: String

              attr_reader ending_before: Time?

              def ending_before=: (Time) -> Time

              attr_reader starting_at: Time?

              def starting_at=: (Time) -> Time

              def initialize: (
                name: String,
                ?ending_before: Time,
                ?starting_at: Time
              ) -> void
            end

            type credit_type_conversion =
              {
                custom_credit_type: MetronomeSDK::CreditTypeData,
                fiat_per_custom_credit: String
              }

            class CreditTypeConversion < MetronomeSDK::Internal::Type::BaseModel
              attr_accessor custom_credit_type: MetronomeSDK::CreditTypeData

              attr_accessor fiat_per_custom_credit: String

              def initialize: (
                custom_credit_type: MetronomeSDK::CreditTypeData,
                fiat_per_custom_credit: String
              ) -> void
            end
          end
        end
      end
    end
  end
end
