module MetronomeSDK
  module Models
    module V1
      module Contracts
        type rate_card_retrieve_params =
          {  } & MetronomeSDK::Internal::Type::request_parameters

        class RateCardRetrieveParams < MetronomeSDK::Models::ID
          extend MetronomeSDK::Internal::Type::RequestParameters::Converter
          include MetronomeSDK::Internal::Type::RequestParameters

          def initialize: (?request_options: MetronomeSDK::request_opts) -> void
        end
      end
    end
  end
end
