module MetronomeSDK
  module Models
    module V1
      module Contracts
        type rate_card_retrieve_rate_schedule_response =
          {
            data: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data],
            next_page: String?
          }

        class RateCardRetrieveRateScheduleResponse < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor data: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data]

          attr_accessor next_page: String?

          def initialize: (
            data: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data],
            ?next_page: String?
          ) -> void

          def to_hash: -> {
            data: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data],
            next_page: String?
          }

          type data =
            {
              entitled: bool,
              product_custom_fields: ::Hash[Symbol, String],
              product_id: String,
              product_name: String,
              product_tags: ::Array[String],
              rate: MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::Rate,
              starting_at: Time,
              commit_rate: MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::CommitRate,
              ending_before: Time,
              pricing_group_values: ::Hash[Symbol, String]
            }

          class Data < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor entitled: bool

            attr_accessor product_custom_fields: ::Hash[Symbol, String]

            attr_accessor product_id: String

            attr_accessor product_name: String

            attr_accessor product_tags: ::Array[String]

            attr_accessor rate: MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::Rate

            attr_accessor starting_at: Time

            attr_reader commit_rate: MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::CommitRate?

            def commit_rate=: (
              MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::CommitRate
            ) -> MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::CommitRate

            attr_reader ending_before: Time?

            def ending_before=: (Time) -> Time

            attr_reader pricing_group_values: ::Hash[Symbol, String]?

            def pricing_group_values=: (
              ::Hash[Symbol, String]
            ) -> ::Hash[Symbol, String]

            def initialize: (
              entitled: bool,
              product_custom_fields: ::Hash[Symbol, String],
              product_id: String,
              product_name: String,
              product_tags: ::Array[String],
              rate: MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::Rate,
              starting_at: Time,
              ?commit_rate: MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::CommitRate,
              ?ending_before: Time,
              ?pricing_group_values: ::Hash[Symbol, String]
            ) -> void

            def to_hash: -> {
              entitled: bool,
              product_custom_fields: ::Hash[Symbol, String],
              product_id: String,
              product_name: String,
              product_tags: ::Array[String],
              rate: MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::Rate,
              starting_at: Time,
              commit_rate: MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::CommitRate,
              ending_before: Time,
              pricing_group_values: ::Hash[Symbol, String]
            }

            type rate =
              {
                rate_type: MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::Rate::rate_type,
                credit_type: MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::Rate::CreditType,
                custom_rate: ::Hash[Symbol, top],
                is_prorated: bool,
                price: Float,
                pricing_group_values: ::Hash[Symbol, String],
                quantity: Float,
                tiers: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::Rate::Tier],
                use_list_prices: bool
              }

            class Rate < MetronomeSDK::Internal::Type::BaseModel
              attr_accessor rate_type: MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::Rate::rate_type

              attr_reader credit_type: MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::Rate::CreditType?

              def credit_type=: (
                MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::Rate::CreditType
              ) -> MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::Rate::CreditType

              attr_reader custom_rate: ::Hash[Symbol, top]?

              def custom_rate=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

              attr_reader is_prorated: bool?

              def is_prorated=: (bool) -> bool

              attr_reader price: Float?

              def price=: (Float) -> Float

              attr_reader pricing_group_values: ::Hash[Symbol, String]?

              def pricing_group_values=: (
                ::Hash[Symbol, String]
              ) -> ::Hash[Symbol, String]

              attr_reader quantity: Float?

              def quantity=: (Float) -> Float

              attr_reader tiers: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::Rate::Tier]?

              def tiers=: (
                ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::Rate::Tier]
              ) -> ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::Rate::Tier]

              attr_reader use_list_prices: bool?

              def use_list_prices=: (bool) -> bool

              def initialize: (
                rate_type: MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::Rate::rate_type,
                ?credit_type: MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::Rate::CreditType,
                ?custom_rate: ::Hash[Symbol, top],
                ?is_prorated: bool,
                ?price: Float,
                ?pricing_group_values: ::Hash[Symbol, String],
                ?quantity: Float,
                ?tiers: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::Rate::Tier],
                ?use_list_prices: bool
              ) -> void

              def to_hash: -> {
                rate_type: MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::Rate::rate_type,
                credit_type: MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::Rate::CreditType,
                custom_rate: ::Hash[Symbol, top],
                is_prorated: bool,
                price: Float,
                pricing_group_values: ::Hash[Symbol, String],
                quantity: Float,
                tiers: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::Rate::Tier],
                use_list_prices: bool
              }

              type rate_type =
                :FLAT | :PERCENTAGE | :SUBSCRIPTION | :CUSTOM | :TIERED

              module RateType
                extend MetronomeSDK::Internal::Type::Enum

                FLAT: :FLAT
                PERCENTAGE: :PERCENTAGE
                SUBSCRIPTION: :SUBSCRIPTION
                CUSTOM: :CUSTOM
                TIERED: :TIERED

                def self?.values: -> ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::Rate::rate_type]
              end

              type credit_type = { id: String, name: String }

              class CreditType < MetronomeSDK::Internal::Type::BaseModel
                attr_accessor id: String

                attr_accessor name: String

                def initialize: (id: String, name: String) -> void

                def to_hash: -> { id: String, name: String }
              end

              type tier = { price: Float, size: Float }

              class Tier < MetronomeSDK::Internal::Type::BaseModel
                attr_accessor price: Float

                attr_reader size: Float?

                def size=: (Float) -> Float

                def initialize: (price: Float, ?size: Float) -> void

                def to_hash: -> { price: Float, size: Float }
              end
            end

            type commit_rate =
              {
                rate_type: MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::CommitRate::rate_type,
                price: Float,
                tiers: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::CommitRate::Tier]
              }

            class CommitRate < MetronomeSDK::Internal::Type::BaseModel
              attr_accessor rate_type: MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::CommitRate::rate_type

              attr_reader price: Float?

              def price=: (Float) -> Float

              attr_reader tiers: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::CommitRate::Tier]?

              def tiers=: (
                ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::CommitRate::Tier]
              ) -> ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::CommitRate::Tier]

              def initialize: (
                rate_type: MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::CommitRate::rate_type,
                ?price: Float,
                ?tiers: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::CommitRate::Tier]
              ) -> void

              def to_hash: -> {
                rate_type: MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::CommitRate::rate_type,
                price: Float,
                tiers: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::CommitRate::Tier]
              }

              type rate_type =
                :FLAT | :PERCENTAGE | :SUBSCRIPTION | :TIERED | :CUSTOM

              module RateType
                extend MetronomeSDK::Internal::Type::Enum

                FLAT: :FLAT
                PERCENTAGE: :PERCENTAGE
                SUBSCRIPTION: :SUBSCRIPTION
                TIERED: :TIERED
                CUSTOM: :CUSTOM

                def self?.values: -> ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse::Data::CommitRate::rate_type]
              end

              type tier = { price: Float, size: Float }

              class Tier < MetronomeSDK::Internal::Type::BaseModel
                attr_accessor price: Float

                attr_reader size: Float?

                def size=: (Float) -> Float

                def initialize: (price: Float, ?size: Float) -> void

                def to_hash: -> { price: Float, size: Float }
              end
            end
          end
        end
      end
    end
  end
end
