module MetronomeSDK
  module Resources
    class V1
      class AuditLogs
        def list:
          (
            ?MetronomeSDK::Models::V1::AuditLogListParams
            | ::Hash[Symbol, top] params
          ) -> MetronomeSDK::CursorPage[MetronomeSDK::Models::V1::AuditLogListResponse]
          | (
            ending_before: Time,
            limit: Integer,
            next_page: String,
            resource_id: String,
            resource_type: String,
            sort: MetronomeSDK::Models::V1::AuditLogListParams::sort,
            starting_on: Time,
            request_options: MetronomeSDK::request_opts
          ) -> MetronomeSDK::CursorPage[MetronomeSDK::Models::V1::AuditLogListResponse]

        def initialize: (client: MetronomeSDK::Client) -> void
      end
    end
  end
end
