module MetronomeSDK
  module Resources
    class V1
      class CustomFields
        def add_key:
          (
            MetronomeSDK::Models::V1::CustomFieldAddKeyParams
            | ::Hash[Symbol, top] params
          ) -> nil
          | (
            enforce_uniqueness: bool,
            entity: MetronomeSDK::Models::V1::CustomFieldAddKeyParams::entity,
            key: String,
            request_options: MetronomeSDK::request_opts
          ) -> nil

        def delete_values:
          (
            MetronomeSDK::Models::V1::CustomFieldDeleteValuesParams
            | ::Hash[Symbol, top] params
          ) -> nil
          | (
            entity: MetronomeSDK::Models::V1::CustomFieldDeleteValuesParams::entity,
            entity_id: String,
            keys: ::Array[String],
            request_options: MetronomeSDK::request_opts
          ) -> nil

        def list_keys:
          (
            ?MetronomeSDK::Models::V1::CustomFieldListKeysParams
            | ::Hash[Symbol, top] params
          ) -> MetronomeSDK::Models::V1::CustomFieldListKeysResponse
          | (
            next_page: String,
            entities: ::Array[MetronomeSDK::Models::V1::CustomFieldListKeysParams::entity],
            request_options: MetronomeSDK::request_opts
          ) -> MetronomeSDK::Models::V1::CustomFieldListKeysResponse

        def remove_key:
          (
            MetronomeSDK::Models::V1::CustomFieldRemoveKeyParams
            | ::Hash[Symbol, top] params
          ) -> nil
          | (
            entity: MetronomeSDK::Models::V1::CustomFieldRemoveKeyParams::entity,
            key: String,
            request_options: MetronomeSDK::request_opts
          ) -> nil

        def set_values:
          (
            MetronomeSDK::Models::V1::CustomFieldSetValuesParams
            | ::Hash[Symbol, top] params
          ) -> nil
          | (
            custom_fields: ::Hash[Symbol, String],
            entity: MetronomeSDK::Models::V1::CustomFieldSetValuesParams::entity,
            entity_id: String,
            request_options: MetronomeSDK::request_opts
          ) -> nil

        def initialize: (client: MetronomeSDK::Client) -> void
      end
    end
  end
end
