module MetronomeSDK
  module Resources
    class V1
      class Plans
        def list:
          (
            ?MetronomeSDK::Models::V1::PlanListParams
            | ::Hash[Symbol, top] params
          ) -> MetronomeSDK::CursorPage[MetronomeSDK::Models::V1::PlanListResponse]
          | (
            limit: Integer,
            next_page: String,
            request_options: MetronomeSDK::request_opts
          ) -> MetronomeSDK::CursorPage[MetronomeSDK::Models::V1::PlanListResponse]

        def get_details:
          (
            MetronomeSDK::Models::V1::PlanGetDetailsParams
            | ::Hash[Symbol, top] params
          ) -> MetronomeSDK::Models::V1::PlanGetDetailsResponse
          | (
            plan_id: String,
            request_options: MetronomeSDK::request_opts
          ) -> MetronomeSDK::Models::V1::PlanGetDetailsResponse

        def list_charges:
          (
            MetronomeSDK::Models::V1::PlanListChargesParams
            | ::Hash[Symbol, top] params
          ) -> MetronomeSDK::CursorPage[MetronomeSDK::Models::V1::PlanListChargesResponse]
          | (
            plan_id: String,
            limit: Integer,
            next_page: String,
            request_options: MetronomeSDK::request_opts
          ) -> MetronomeSDK::CursorPage[MetronomeSDK::Models::V1::PlanListChargesResponse]

        def list_customers:
          (
            MetronomeSDK::Models::V1::PlanListCustomersParams
            | ::Hash[Symbol, top] params
          ) -> MetronomeSDK::CursorPage[MetronomeSDK::Models::V1::PlanListCustomersResponse]
          | (
            plan_id: String,
            limit: Integer,
            next_page: String,
            status: MetronomeSDK::Models::V1::PlanListCustomersParams::status,
            request_options: MetronomeSDK::request_opts
          ) -> MetronomeSDK::CursorPage[MetronomeSDK::Models::V1::PlanListCustomersResponse]

        def initialize: (client: MetronomeSDK::Client) -> void
      end
    end
  end
end
