module MetronomeSDK
  module Resources
    class V1
      class Services
        def list:
          (
            ?MetronomeSDK::Models::V1::ServiceListParams
            | ::Hash[Symbol, top] params
          ) -> MetronomeSDK::Models::V1::ServiceListResponse
          | (
            request_options: MetronomeSDK::request_opts
          ) -> MetronomeSDK::Models::V1::ServiceListResponse

        def initialize: (client: MetronomeSDK::Client) -> void
      end
    end
  end
end
