module MetronomeSDK
  module Resources
    class Notifications
      attr_reader offset: MetronomeSDK::Resources::Notifications::Offset

      attr_reader system_: MetronomeSDK::Resources::Notifications::System

      def create: (
        name: String,
        policy: MetronomeSDK::NotificationCreateParams::Policy,
        ?uniqueness_key: String,
        ?request_options: MetronomeSDK::request_opts
      ) -> MetronomeSDK::Models::NotificationCreateResponse

      def retrieve: (
        id: String,
        ?request_options: MetronomeSDK::request_opts
      ) -> MetronomeSDK::Models::NotificationRetrieveResponse

      def update: (
        policy: MetronomeSDK::Models::NotificationUpdateParams::policy,
        ?id: String,
        ?is_enabled: bool,
        ?request_options: MetronomeSDK::request_opts
      ) -> MetronomeSDK::Models::NotificationUpdateResponse

      def archive: (
        id: String,
        ?request_options: MetronomeSDK::request_opts
      ) -> MetronomeSDK::Models::NotificationArchiveResponse

      def initialize: (client: MetronomeSDK::Client) -> void
    end
  end
end
