module MetronomeSDK
  module Resources
    class Payments
      def list: (
        customer_id: String,
        invoice_id: String,
        ?limit: Integer,
        ?next_page: String,
        ?statuses: ::Array[MetronomeSDK::Models::PaymentListParams::status],
        ?request_options: MetronomeSDK::request_opts
      ) -> MetronomeSDK::Internal::BodyCursorPage[MetronomeSDK::Models::PaymentListResponse]

      def attempt: (
        customer_id: String,
        invoice_id: String,
        ?request_options: MetronomeSDK::request_opts
      ) -> MetronomeSDK::Models::PaymentAttemptResponse

      def cancel: (
        customer_id: String,
        invoice_id: String,
        ?request_options: MetronomeSDK::request_opts
      ) -> MetronomeSDK::Models::PaymentCancelResponse

      def initialize: (client: MetronomeSDK::Client) -> void
    end
  end
end
