module MetronomeSDK
  module Resources
    class V2
      class Contracts
        def retrieve: (
          contract_id: String,
          customer_id: String,
          ?as_of_date: Time,
          ?include_balance: bool,
          ?include_ledgers: bool,
          ?request_options: MetronomeSDK::request_opts
        ) -> MetronomeSDK::Models::V2::ContractRetrieveResponse

        def list: (
          customer_id: String,
          ?covering_date: Time,
          ?include_archived: bool,
          ?include_balance: bool,
          ?include_ledgers: bool,
          ?starting_at: Time,
          ?request_options: MetronomeSDK::request_opts
        ) -> MetronomeSDK::Models::V2::ContractListResponse

        def edit: (
          contract_id: String,
          customer_id: String,
          ?add_billing_provider_configuration_update: MetronomeSDK::V2::ContractEditParams::AddBillingProviderConfigurationUpdate,
          ?add_commits: ::Array[MetronomeSDK::V2::ContractEditParams::AddCommit],
          ?add_credits: ::Array[MetronomeSDK::V2::ContractEditParams::AddCredit],
          ?add_discounts: ::Array[MetronomeSDK::V2::ContractEditParams::AddDiscount],
          ?add_overrides: ::Array[MetronomeSDK::V2::ContractEditParams::AddOverride],
          ?add_prepaid_balance_threshold_configuration: MetronomeSDK::PrepaidBalanceThresholdConfigurationV2,
          ?add_professional_services: ::Array[MetronomeSDK::V2::ContractEditParams::AddProfessionalService],
          ?add_recurring_commits: ::Array[MetronomeSDK::V2::ContractEditParams::AddRecurringCommit],
          ?add_recurring_credits: ::Array[MetronomeSDK::V2::ContractEditParams::AddRecurringCredit],
          ?add_reseller_royalties: ::Array[MetronomeSDK::V2::ContractEditParams::AddResellerRoyalty],
          ?add_scheduled_charges: ::Array[MetronomeSDK::V2::ContractEditParams::AddScheduledCharge],
          ?add_spend_threshold_configuration: MetronomeSDK::SpendThresholdConfigurationV2,
          ?add_subscriptions: ::Array[MetronomeSDK::V2::ContractEditParams::AddSubscription],
          ?allow_contract_ending_before_finalized_invoice: bool,
          ?archive_commits: ::Array[MetronomeSDK::V2::ContractEditParams::ArchiveCommit],
          ?archive_credits: ::Array[MetronomeSDK::V2::ContractEditParams::ArchiveCredit],
          ?archive_scheduled_charges: ::Array[MetronomeSDK::V2::ContractEditParams::ArchiveScheduledCharge],
          ?remove_overrides: ::Array[MetronomeSDK::V2::ContractEditParams::RemoveOverride],
          ?uniqueness_key: String,
          ?update_commits: ::Array[MetronomeSDK::V2::ContractEditParams::UpdateCommit],
          ?update_contract_end_date: Time?,
          ?update_contract_name: String?,
          ?update_credits: ::Array[MetronomeSDK::V2::ContractEditParams::UpdateCredit],
          ?update_net_payment_terms_days: Float?,
          ?update_prepaid_balance_threshold_configuration: MetronomeSDK::V2::ContractEditParams::UpdatePrepaidBalanceThresholdConfiguration,
          ?update_recurring_commits: ::Array[MetronomeSDK::V2::ContractEditParams::UpdateRecurringCommit],
          ?update_recurring_credits: ::Array[MetronomeSDK::V2::ContractEditParams::UpdateRecurringCredit],
          ?update_scheduled_charges: ::Array[MetronomeSDK::V2::ContractEditParams::UpdateScheduledCharge],
          ?update_spend_threshold_configuration: MetronomeSDK::V2::ContractEditParams::UpdateSpendThresholdConfiguration,
          ?update_subscriptions: ::Array[MetronomeSDK::V2::ContractEditParams::UpdateSubscription],
          ?request_options: MetronomeSDK::request_opts
        ) -> MetronomeSDK::Models::V2::ContractEditResponse

        def edit_commit: (
          commit_id: String,
          customer_id: String,
          ?access_schedule: MetronomeSDK::V2::ContractEditCommitParams::AccessSchedule,
          ?applicable_product_ids: ::Array[String]?,
          ?applicable_product_tags: ::Array[String]?,
          ?description: String,
          ?hierarchy_configuration: MetronomeSDK::CommitHierarchyConfiguration,
          ?invoice_contract_id: String,
          ?invoice_schedule: MetronomeSDK::V2::ContractEditCommitParams::InvoiceSchedule,
          ?name: String,
          ?priority: Float?,
          ?product_id: String,
          ?rate_type: MetronomeSDK::Models::V2::ContractEditCommitParams::rate_type,
          ?specifiers: ::Array[MetronomeSDK::CommitSpecifierInput]?,
          ?request_options: MetronomeSDK::request_opts
        ) -> MetronomeSDK::Models::V2::ContractEditCommitResponse

        def edit_credit: (
          credit_id: String,
          customer_id: String,
          ?access_schedule: MetronomeSDK::V2::ContractEditCreditParams::AccessSchedule,
          ?applicable_product_ids: ::Array[String]?,
          ?applicable_product_tags: ::Array[String]?,
          ?description: String,
          ?hierarchy_configuration: MetronomeSDK::CommitHierarchyConfiguration,
          ?name: String,
          ?priority: Float?,
          ?product_id: String,
          ?rate_type: MetronomeSDK::Models::V2::ContractEditCreditParams::rate_type,
          ?specifiers: ::Array[MetronomeSDK::CommitSpecifierInput]?,
          ?request_options: MetronomeSDK::request_opts
        ) -> MetronomeSDK::Models::V2::ContractEditCreditResponse

        def get_edit_history: (
          contract_id: String,
          customer_id: String,
          ?request_options: MetronomeSDK::request_opts
        ) -> MetronomeSDK::Models::V2::ContractGetEditHistoryResponse

        def initialize: (client: MetronomeSDK::Client) -> void
      end
    end
  end
end
