module Metronome
  module Models
    type alert_archive_params =
      { id: String, release_uniqueness_key: bool }
      & Metronome::request_parameters

    class AlertArchiveParams < Metronome::BaseModel
      extend Metronome::RequestParameters::Converter
      include Metronome::RequestParameters

      attr_accessor id: String

      attr_reader release_uniqueness_key: bool?

      def release_uniqueness_key=: (bool) -> void

      def initialize:
        (
          id: String,
          release_uniqueness_key: bool,
          request_options: Metronome::request_opts
        ) -> void
        | (
          ?Metronome::Models::alert_archive_params | Metronome::BaseModel data
        ) -> void

      def to_hash: -> Metronome::Models::alert_archive_params
    end
  end
end
