module Metronome
  module Models
    type billable_metric_archive_response = { data: Metronome::Models::ID }

    class BillableMetricArchiveResponse < Metronome::BaseModel
      attr_accessor data: Metronome::Models::ID

      def initialize:
        (data: Metronome::Models::ID) -> void
        | (
          ?Metronome::Models::billable_metric_archive_response
          | Metronome::BaseModel data
        ) -> void

      def to_hash: -> Metronome::Models::billable_metric_archive_response
    end
  end
end
