module Metronome
  module Models
    type contract_update_end_date_response = { data: Metronome::Models::ID }

    class ContractUpdateEndDateResponse < Metronome::BaseModel
      attr_accessor data: Metronome::Models::ID

      def initialize:
        (data: Metronome::Models::ID) -> void
        | (
          ?Metronome::Models::contract_update_end_date_response
          | Metronome::BaseModel data
        ) -> void

      def to_hash: -> Metronome::Models::contract_update_end_date_response
    end
  end
end
