module Metronome
  module Models
    type contract_archive_response = { data: Metronome::Models::ID }

    class ContractArchiveResponse < Metronome::BaseModel
      attr_accessor data: Metronome::Models::ID

      def initialize:
        (data: Metronome::Models::ID) -> void
        | (
          ?Metronome::Models::contract_archive_response
          | Metronome::BaseModel data
        ) -> void

      def to_h: -> Metronome::Models::contract_archive_response
    end
  end
end
