module Metronome
  module Models
    type credit =
      {
        id: String,
        product: Metronome::Models::Credit::Product,
        type: Metronome::Models::Credit::type_,
        access_schedule: Metronome::Models::ScheduleDuration,
        applicable_contract_ids: Array[String],
        applicable_product_ids: Array[String],
        applicable_product_tags: Array[String],
        balance: Float,
        contract: Metronome::Models::Credit::Contract,
        custom_fields: Hash[Symbol, String],
        description: String,
        ledger: Array[Metronome::Models::Credit::ledger],
        name: String,
        netsuite_sales_order_id: String,
        priority: Float,
        rate_type: Metronome::Models::Credit::rate_type,
        salesforce_opportunity_id: String,
        uniqueness_key: String
      }

    class Credit < Metronome::BaseModel
      attr_accessor id: String

      attr_accessor product: Metronome::Models::Credit::Product

      attr_accessor type: Metronome::Models::Credit::type_

      attr_reader access_schedule: Metronome::Models::ScheduleDuration?

      def access_schedule=: (Metronome::Models::ScheduleDuration) -> void

      attr_reader applicable_contract_ids: Array[String]?

      def applicable_contract_ids=: (Array[String]) -> void

      attr_reader applicable_product_ids: Array[String]?

      def applicable_product_ids=: (Array[String]) -> void

      attr_reader applicable_product_tags: Array[String]?

      def applicable_product_tags=: (Array[String]) -> void

      attr_reader balance: Float?

      def balance=: (Float) -> void

      attr_reader contract: Metronome::Models::Credit::Contract?

      def contract=: (Metronome::Models::Credit::Contract) -> void

      attr_reader custom_fields: Hash[Symbol, String]?

      def custom_fields=: (Hash[Symbol, String]) -> void

      attr_reader description: String?

      def description=: (String) -> void

      attr_reader ledger: Array[Metronome::Models::Credit::ledger]?

      def ledger=: (Array[Metronome::Models::Credit::ledger]) -> void

      attr_reader name: String?

      def name=: (String) -> void

      attr_reader netsuite_sales_order_id: String?

      def netsuite_sales_order_id=: (String) -> void

      attr_reader priority: Float?

      def priority=: (Float) -> void

      attr_reader rate_type: Metronome::Models::Credit::rate_type?

      def rate_type=: (Metronome::Models::Credit::rate_type) -> void

      attr_reader salesforce_opportunity_id: String?

      def salesforce_opportunity_id=: (String) -> void

      attr_reader uniqueness_key: String?

      def uniqueness_key=: (String) -> void

      def initialize:
        (
          id: String,
          product: Metronome::Models::Credit::Product,
          type: Metronome::Models::Credit::type_,
          access_schedule: Metronome::Models::ScheduleDuration,
          applicable_contract_ids: Array[String],
          applicable_product_ids: Array[String],
          applicable_product_tags: Array[String],
          balance: Float,
          contract: Metronome::Models::Credit::Contract,
          custom_fields: Hash[Symbol, String],
          description: String,
          ledger: Array[Metronome::Models::Credit::ledger],
          name: String,
          netsuite_sales_order_id: String,
          priority: Float,
          rate_type: Metronome::Models::Credit::rate_type,
          salesforce_opportunity_id: String,
          uniqueness_key: String
        ) -> void
        | (?Metronome::Models::credit | Metronome::BaseModel data) -> void

      def to_h: -> Metronome::Models::credit

      type product = { id: String, name: String }

      class Product < Metronome::BaseModel
        attr_accessor id: String

        attr_accessor name: String

        def initialize:
          (id: String, name: String) -> void
          | (
            ?Metronome::Models::Credit::product | Metronome::BaseModel data
          ) -> void

        def to_h: -> Metronome::Models::Credit::product
      end

      type type_ = :CREDIT

      class Type < Metronome::Enum
        CREDIT: :CREDIT

        def self.values: -> Array[Metronome::Models::Credit::type_]
      end

      type contract = { id: String }

      class Contract < Metronome::BaseModel
        attr_accessor id: String

        def initialize:
          (id: String) -> void
          | (
            ?Metronome::Models::Credit::contract | Metronome::BaseModel data
          ) -> void

        def to_h: -> Metronome::Models::Credit::contract
      end

      type ledger =
        Metronome::Models::Credit::Ledger::CreditSegmentStartLedgerEntry
        | Metronome::Models::Credit::Ledger::CreditAutomatedInvoiceDeductionLedgerEntry
        | Metronome::Models::Credit::Ledger::CreditExpirationLedgerEntry
        | Metronome::Models::Credit::Ledger::CreditCanceledLedgerEntry
        | Metronome::Models::Credit::Ledger::CreditCreditedLedgerEntry
        | Metronome::Models::Credit::Ledger::CreditManualLedgerEntry

      class Ledger < Metronome::Union
        type credit_segment_start_ledger_entry =
          {
            amount: Float,
            segment_id: String,
            timestamp: Time,
            type: Metronome::Models::Credit::Ledger::CreditSegmentStartLedgerEntry::type_
          }

        class CreditSegmentStartLedgerEntry < Metronome::BaseModel
          attr_accessor amount: Float

          attr_accessor segment_id: String

          attr_accessor timestamp: Time

          attr_accessor type: Metronome::Models::Credit::Ledger::CreditSegmentStartLedgerEntry::type_

          def initialize:
            (
              amount: Float,
              segment_id: String,
              timestamp: Time,
              type: Metronome::Models::Credit::Ledger::CreditSegmentStartLedgerEntry::type_
            ) -> void
            | (
              ?Metronome::Models::Credit::Ledger::credit_segment_start_ledger_entry
              | Metronome::BaseModel data
            ) -> void

          def to_h: -> Metronome::Models::Credit::Ledger::credit_segment_start_ledger_entry

          type type_ = :CREDIT_SEGMENT_START

          class Type < Metronome::Enum
            CREDIT_SEGMENT_START: :CREDIT_SEGMENT_START

            def self.values: -> Array[Metronome::Models::Credit::Ledger::CreditSegmentStartLedgerEntry::type_]
          end
        end

        type credit_automated_invoice_deduction_ledger_entry =
          {
            amount: Float,
            invoice_id: String,
            segment_id: String,
            timestamp: Time,
            type: Metronome::Models::Credit::Ledger::CreditAutomatedInvoiceDeductionLedgerEntry::type_
          }

        class CreditAutomatedInvoiceDeductionLedgerEntry < Metronome::BaseModel
          attr_accessor amount: Float

          attr_accessor invoice_id: String

          attr_accessor segment_id: String

          attr_accessor timestamp: Time

          attr_accessor type: Metronome::Models::Credit::Ledger::CreditAutomatedInvoiceDeductionLedgerEntry::type_

          def initialize:
            (
              amount: Float,
              invoice_id: String,
              segment_id: String,
              timestamp: Time,
              type: Metronome::Models::Credit::Ledger::CreditAutomatedInvoiceDeductionLedgerEntry::type_
            ) -> void
            | (
              ?Metronome::Models::Credit::Ledger::credit_automated_invoice_deduction_ledger_entry
              | Metronome::BaseModel data
            ) -> void

          def to_h: -> Metronome::Models::Credit::Ledger::credit_automated_invoice_deduction_ledger_entry

          type type_ = :CREDIT_AUTOMATED_INVOICE_DEDUCTION

          class Type < Metronome::Enum
            CREDIT_AUTOMATED_INVOICE_DEDUCTION: :CREDIT_AUTOMATED_INVOICE_DEDUCTION

            def self.values: -> Array[Metronome::Models::Credit::Ledger::CreditAutomatedInvoiceDeductionLedgerEntry::type_]
          end
        end

        type credit_expiration_ledger_entry =
          {
            amount: Float,
            segment_id: String,
            timestamp: Time,
            type: Metronome::Models::Credit::Ledger::CreditExpirationLedgerEntry::type_
          }

        class CreditExpirationLedgerEntry < Metronome::BaseModel
          attr_accessor amount: Float

          attr_accessor segment_id: String

          attr_accessor timestamp: Time

          attr_accessor type: Metronome::Models::Credit::Ledger::CreditExpirationLedgerEntry::type_

          def initialize:
            (
              amount: Float,
              segment_id: String,
              timestamp: Time,
              type: Metronome::Models::Credit::Ledger::CreditExpirationLedgerEntry::type_
            ) -> void
            | (
              ?Metronome::Models::Credit::Ledger::credit_expiration_ledger_entry
              | Metronome::BaseModel data
            ) -> void

          def to_h: -> Metronome::Models::Credit::Ledger::credit_expiration_ledger_entry

          type type_ = :CREDIT_EXPIRATION

          class Type < Metronome::Enum
            CREDIT_EXPIRATION: :CREDIT_EXPIRATION

            def self.values: -> Array[Metronome::Models::Credit::Ledger::CreditExpirationLedgerEntry::type_]
          end
        end

        type credit_canceled_ledger_entry =
          {
            amount: Float,
            invoice_id: String,
            segment_id: String,
            timestamp: Time,
            type: Metronome::Models::Credit::Ledger::CreditCanceledLedgerEntry::type_
          }

        class CreditCanceledLedgerEntry < Metronome::BaseModel
          attr_accessor amount: Float

          attr_accessor invoice_id: String

          attr_accessor segment_id: String

          attr_accessor timestamp: Time

          attr_accessor type: Metronome::Models::Credit::Ledger::CreditCanceledLedgerEntry::type_

          def initialize:
            (
              amount: Float,
              invoice_id: String,
              segment_id: String,
              timestamp: Time,
              type: Metronome::Models::Credit::Ledger::CreditCanceledLedgerEntry::type_
            ) -> void
            | (
              ?Metronome::Models::Credit::Ledger::credit_canceled_ledger_entry
              | Metronome::BaseModel data
            ) -> void

          def to_h: -> Metronome::Models::Credit::Ledger::credit_canceled_ledger_entry

          type type_ = :CREDIT_CANCELED

          class Type < Metronome::Enum
            CREDIT_CANCELED: :CREDIT_CANCELED

            def self.values: -> Array[Metronome::Models::Credit::Ledger::CreditCanceledLedgerEntry::type_]
          end
        end

        type credit_credited_ledger_entry =
          {
            amount: Float,
            invoice_id: String,
            segment_id: String,
            timestamp: Time,
            type: Metronome::Models::Credit::Ledger::CreditCreditedLedgerEntry::type_
          }

        class CreditCreditedLedgerEntry < Metronome::BaseModel
          attr_accessor amount: Float

          attr_accessor invoice_id: String

          attr_accessor segment_id: String

          attr_accessor timestamp: Time

          attr_accessor type: Metronome::Models::Credit::Ledger::CreditCreditedLedgerEntry::type_

          def initialize:
            (
              amount: Float,
              invoice_id: String,
              segment_id: String,
              timestamp: Time,
              type: Metronome::Models::Credit::Ledger::CreditCreditedLedgerEntry::type_
            ) -> void
            | (
              ?Metronome::Models::Credit::Ledger::credit_credited_ledger_entry
              | Metronome::BaseModel data
            ) -> void

          def to_h: -> Metronome::Models::Credit::Ledger::credit_credited_ledger_entry

          type type_ = :CREDIT_CREDITED

          class Type < Metronome::Enum
            CREDIT_CREDITED: :CREDIT_CREDITED

            def self.values: -> Array[Metronome::Models::Credit::Ledger::CreditCreditedLedgerEntry::type_]
          end
        end

        type credit_manual_ledger_entry =
          {
            amount: Float,
            reason: String,
            timestamp: Time,
            type: Metronome::Models::Credit::Ledger::CreditManualLedgerEntry::type_
          }

        class CreditManualLedgerEntry < Metronome::BaseModel
          attr_accessor amount: Float

          attr_accessor reason: String

          attr_accessor timestamp: Time

          attr_accessor type: Metronome::Models::Credit::Ledger::CreditManualLedgerEntry::type_

          def initialize:
            (
              amount: Float,
              reason: String,
              timestamp: Time,
              type: Metronome::Models::Credit::Ledger::CreditManualLedgerEntry::type_
            ) -> void
            | (
              ?Metronome::Models::Credit::Ledger::credit_manual_ledger_entry
              | Metronome::BaseModel data
            ) -> void

          def to_h: -> Metronome::Models::Credit::Ledger::credit_manual_ledger_entry

          type type_ = :CREDIT_MANUAL

          class Type < Metronome::Enum
            CREDIT_MANUAL: :CREDIT_MANUAL

            def self.values: -> Array[Metronome::Models::Credit::Ledger::CreditManualLedgerEntry::type_]
          end
        end

        private def self.variants: -> [[nil, Metronome::Models::Credit::Ledger::CreditSegmentStartLedgerEntry], [nil, Metronome::Models::Credit::Ledger::CreditAutomatedInvoiceDeductionLedgerEntry], [nil, Metronome::Models::Credit::Ledger::CreditExpirationLedgerEntry], [nil, Metronome::Models::Credit::Ledger::CreditCanceledLedgerEntry], [nil, Metronome::Models::Credit::Ledger::CreditCreditedLedgerEntry], [nil, Metronome::Models::Credit::Ledger::CreditManualLedgerEntry]]
      end

      type rate_type = :COMMIT_RATE | :LIST_RATE

      class RateType < Metronome::Enum
        COMMIT_RATE: :COMMIT_RATE
        LIST_RATE: :LIST_RATE

        def self.values: -> Array[Metronome::Models::Credit::rate_type]
      end
    end
  end
end
