module Metronome
  module Models
    type credit_grant_void_params =
      {
        id: String,
        release_uniqueness_key: bool,
        void_credit_purchase_invoice: bool
      }
      & Metronome::request_parameters

    class CreditGrantVoidParams < Metronome::BaseModel
      extend Metronome::RequestParameters::Converter
      include Metronome::RequestParameters

      attr_accessor id: String

      attr_reader release_uniqueness_key: bool?

      def release_uniqueness_key=: (bool) -> bool

      attr_reader void_credit_purchase_invoice: bool?

      def void_credit_purchase_invoice=: (bool) -> bool

      def initialize:
        (
          id: String,
          release_uniqueness_key: bool,
          void_credit_purchase_invoice: bool,
          request_options: Metronome::request_opts
        ) -> void
        | (
          ?Metronome::Models::credit_grant_void_params
          | Metronome::BaseModel data
        ) -> void

      def to_hash: -> Metronome::Models::credit_grant_void_params
    end
  end
end
