module Metronome
  module Models
    type credit_grant_create_response = { data: Metronome::Models::ID }

    class CreditGrantCreateResponse < Metronome::BaseModel
      attr_accessor data: Metronome::Models::ID

      def initialize:
        (data: Metronome::Models::ID) -> void
        | (
          ?Metronome::Models::credit_grant_create_response
          | Metronome::BaseModel data
        ) -> void

      def to_h: -> Metronome::Models::credit_grant_create_response
    end
  end
end
