module Metronome
  module Models
    type customer_list_costs_params =
      {
        customer_id: String,
        ending_before: Time,
        starting_on: Time,
        limit: Integer,
        next_page: String
      }
      & Metronome::request_parameters

    class CustomerListCostsParams < Metronome::BaseModel
      extend Metronome::RequestParameters::Converter
      include Metronome::RequestParameters

      attr_accessor customer_id: String

      attr_accessor ending_before: Time

      attr_accessor starting_on: Time

      attr_reader limit: Integer?

      def limit=: (Integer) -> void

      attr_reader next_page: String?

      def next_page=: (String) -> void

      def initialize:
        (
          customer_id: String,
          ending_before: Time,
          starting_on: Time,
          limit: Integer,
          next_page: String,
          request_options: Metronome::request_opts
        ) -> void
        | (
          ?Metronome::Models::customer_list_costs_params
          | Metronome::BaseModel data
        ) -> void

      def to_h: -> Metronome::Models::customer_list_costs_params
    end
  end
end
