module Metronome
  module Models
    type custom_field_list_keys_response =
      {
        data: ::Array[Metronome::Models::CustomFieldListKeysResponse::Data],
        next_page: String?
      }

    class CustomFieldListKeysResponse < Metronome::BaseModel
      attr_accessor data: ::Array[Metronome::Models::CustomFieldListKeysResponse::Data]

      attr_accessor next_page: String?

      def initialize:
        (
          data: ::Array[Metronome::Models::CustomFieldListKeysResponse::Data],
          next_page: String?
        ) -> void
        | (
          ?Metronome::Models::custom_field_list_keys_response
          | Metronome::BaseModel data
        ) -> void

      def to_hash: -> Metronome::Models::custom_field_list_keys_response

      type data =
        {
          enforce_uniqueness: bool,
          entity: Metronome::Models::CustomFieldListKeysResponse::Data::entity,
          key: String
        }

      class Data < Metronome::BaseModel
        attr_accessor enforce_uniqueness: bool

        attr_accessor entity: Metronome::Models::CustomFieldListKeysResponse::Data::entity

        attr_accessor key: String

        def initialize:
          (
            enforce_uniqueness: bool,
            entity: Metronome::Models::CustomFieldListKeysResponse::Data::entity,
            key: String
          ) -> void
          | (
            ?Metronome::Models::CustomFieldListKeysResponse::data
            | Metronome::BaseModel data
          ) -> void

        def to_hash: -> Metronome::Models::CustomFieldListKeysResponse::data

        type entity =
          :alert
          | :billable_metric
          | :charge
          | :commit
          | :contract_credit
          | :contract_product
          | :contract
          | :credit_grant
          | :customer_plan
          | :customer
          | :discount
          | :invoice
          | :plan
          | :professional_service
          | :product
          | :rate_card
          | :scheduled_charge

        class Entity < Metronome::Enum
          ALERT: :alert
          BILLABLE_METRIC: :billable_metric
          CHARGE: :charge
          COMMIT: :commit
          CONTRACT_CREDIT: :contract_credit
          CONTRACT_PRODUCT: :contract_product
          CONTRACT: :contract
          CREDIT_GRANT: :credit_grant
          CUSTOMER_PLAN: :customer_plan
          CUSTOMER: :customer
          DISCOUNT: :discount
          INVOICE: :invoice
          PLAN: :plan
          PROFESSIONAL_SERVICE: :professional_service
          PRODUCT: :product
          RATE_CARD: :rate_card
          SCHEDULED_CHARGE: :scheduled_charge

          def self.values: -> ::Array[Metronome::Models::CustomFieldListKeysResponse::Data::entity]
        end
      end
    end
  end
end
