module Metronome
  module Models
    type custom_field_list_keys_params =
      {
        next_page: String,
        entities: Array[Metronome::Models::CustomFieldListKeysParams::entity]
      }
      & Metronome::request_parameters

    class CustomFieldListKeysParams < Metronome::BaseModel
      extend Metronome::RequestParameters::Converter
      include Metronome::RequestParameters

      attr_reader next_page: String?

      def next_page=: (String) -> void

      attr_reader entities: Array[Metronome::Models::CustomFieldListKeysParams::entity]

      def entities=: (
        Array[Metronome::Models::CustomFieldListKeysParams::entity]
      ) -> void

      def initialize:
        (
          next_page: String,
          entities: Array[Metronome::Models::CustomFieldListKeysParams::entity],
          request_options: Metronome::request_opts
        ) -> void
        | (
          ?Metronome::Models::custom_field_list_keys_params
          | Metronome::BaseModel data
        ) -> void

      def to_h: -> Metronome::Models::custom_field_list_keys_params

      type entity =
        :alert
        | :billable_metric
        | :charge
        | :commit
        | :contract_credit
        | :contract_product
        | :contract
        | :credit_grant
        | :customer_plan
        | :customer
        | :discount
        | :invoice
        | :plan
        | :professional_service
        | :product
        | :rate_card
        | :scheduled_charge

      class Entity < Metronome::Enum
        ALERT: :alert
        BILLABLE_METRIC: :billable_metric
        CHARGE: :charge
        COMMIT: :commit
        CONTRACT_CREDIT: :contract_credit
        CONTRACT_PRODUCT: :contract_product
        CONTRACT: :contract
        CREDIT_GRANT: :credit_grant
        CUSTOMER_PLAN: :customer_plan
        CUSTOMER: :customer
        DISCOUNT: :discount
        INVOICE: :invoice
        PLAN: :plan
        PROFESSIONAL_SERVICE: :professional_service
        PRODUCT: :product
        RATE_CARD: :rate_card
        SCHEDULED_CHARGE: :scheduled_charge

        def self.values: -> Array[Metronome::Models::CustomFieldListKeysParams::entity]
      end
    end
  end
end
