module Metronome
  module Models
    type customer_create_response = { data: Metronome::Models::Customer }

    class CustomerCreateResponse < Metronome::BaseModel
      attr_accessor data: Metronome::Models::Customer

      def initialize:
        (data: Metronome::Models::Customer) -> void
        | (
          ?Metronome::Models::customer_create_response
          | Metronome::BaseModel data
        ) -> void

      def to_h: -> Metronome::Models::customer_create_response
    end
  end
end
