module Metronome
  module Models
    type customer_retrieve_params =
      { customer_id: String } & Metronome::request_parameters

    class CustomerRetrieveParams < Metronome::BaseModel
      extend Metronome::RequestParameters::Converter
      include Metronome::RequestParameters

      attr_accessor customer_id: String

      def initialize:
        (customer_id: String, request_options: Metronome::request_opts) -> void
        | (
          ?Metronome::Models::customer_retrieve_params
          | Metronome::BaseModel data
        ) -> void

      def to_h: -> Metronome::Models::customer_retrieve_params
    end
  end
end
