module Metronome
  module Models
    type customer_archive_response = { data: Metronome::Models::ID }

    class CustomerArchiveResponse < Metronome::BaseModel
      attr_accessor data: Metronome::Models::ID

      def initialize:
        (data: Metronome::Models::ID) -> void
        | (
          ?Metronome::Models::customer_archive_response
          | Metronome::BaseModel data
        ) -> void

      def to_hash: -> Metronome::Models::customer_archive_response
    end
  end
end
