module Metronome
  module Models
    type customer_list_billable_metrics_params =
      {
        customer_id: String,
        include_archived: bool,
        limit: Integer,
        next_page: String,
        on_current_plan: bool
      }
      & Metronome::request_parameters

    class CustomerListBillableMetricsParams < Metronome::BaseModel
      extend Metronome::RequestParameters::Converter
      include Metronome::RequestParameters

      attr_accessor customer_id: String

      attr_reader include_archived: bool?

      def include_archived=: (bool) -> void

      attr_reader limit: Integer?

      def limit=: (Integer) -> void

      attr_reader next_page: String?

      def next_page=: (String) -> void

      attr_reader on_current_plan: bool?

      def on_current_plan=: (bool) -> void

      def initialize:
        (
          customer_id: String,
          include_archived: bool,
          limit: Integer,
          next_page: String,
          on_current_plan: bool,
          request_options: Metronome::request_opts
        ) -> void
        | (
          ?Metronome::Models::customer_list_billable_metrics_params
          | Metronome::BaseModel data
        ) -> void

      def to_hash: -> Metronome::Models::customer_list_billable_metrics_params
    end
  end
end
