module Metronome
  module Models
    type id = { id: String }

    class ID < Metronome::BaseModel
      attr_accessor id: String

      def initialize:
        (id: String) -> void
        | (?Metronome::Models::id | Metronome::BaseModel data) -> void

      def to_hash: -> Metronome::Models::id
    end
  end
end
