module Metronome
  module Models
    type invoice_void_response =
      { data: Metronome::Models::InvoiceVoidResponse::Data }

    class InvoiceVoidResponse < Metronome::BaseModel
      attr_reader data: Metronome::Models::InvoiceVoidResponse::Data?

      def data=: (
        Metronome::Models::InvoiceVoidResponse::Data
      ) -> Metronome::Models::InvoiceVoidResponse::Data

      def initialize:
        (data: Metronome::Models::InvoiceVoidResponse::Data) -> void
        | (
          ?Metronome::Models::invoice_void_response | Metronome::BaseModel data
        ) -> void

      def to_hash: -> Metronome::Models::invoice_void_response

      type data = { id: String }

      class Data < Metronome::BaseModel
        attr_accessor id: String

        def initialize:
          (id: String) -> void
          | (
            ?Metronome::Models::InvoiceVoidResponse::data
            | Metronome::BaseModel data
          ) -> void

        def to_hash: -> Metronome::Models::InvoiceVoidResponse::data
      end
    end
  end
end
