module Metronome
  module Models
    type plan_get_details_params =
      { plan_id: String } & Metronome::request_parameters

    class PlanGetDetailsParams < Metronome::BaseModel
      extend Metronome::RequestParameters::Converter
      include Metronome::RequestParameters

      attr_accessor plan_id: String

      def initialize:
        (plan_id: String, request_options: Metronome::request_opts) -> void
        | (
          ?Metronome::Models::plan_get_details_params
          | Metronome::BaseModel data
        ) -> void

      def to_hash: -> Metronome::Models::plan_get_details_params
    end
  end
end
