module Metronome
  module Models
    type plan_list_response =
      {
        id: String,
        description: String,
        name: String,
        custom_fields: Hash[Symbol, String]
      }

    class PlanListResponse < Metronome::BaseModel
      attr_accessor id: String

      attr_accessor description: String

      attr_accessor name: String

      attr_reader custom_fields: Hash[Symbol, String]?

      def custom_fields=: (Hash[Symbol, String]) -> void

      def initialize:
        (
          id: String,
          description: String,
          name: String,
          custom_fields: Hash[Symbol, String]
        ) -> void
        | (
          ?Metronome::Models::plan_list_response | Metronome::BaseModel data
        ) -> void

      def to_h: -> Metronome::Models::plan_list_response
    end
  end
end
