module Metronome
  module Models
    type pricing_unit_list_response =
      { id: String, is_currency: bool, name: String }

    class PricingUnitListResponse < Metronome::BaseModel
      attr_reader id: String?

      def id=: (String) -> String

      attr_reader is_currency: bool?

      def is_currency=: (bool) -> bool

      attr_reader name: String?

      def name=: (String) -> String

      def initialize:
        (id: String, is_currency: bool, name: String) -> void
        | (
          ?Metronome::Models::pricing_unit_list_response
          | Metronome::BaseModel data
        ) -> void

      def to_hash: -> Metronome::Models::pricing_unit_list_response
    end
  end
end
