module Metronome
  module Models
    type rollover_amount_max_amount =
      { type: Metronome::Models::RolloverAmountMaxAmount::type_, value: Float }

    class RolloverAmountMaxAmount < Metronome::BaseModel
      attr_accessor type: Metronome::Models::RolloverAmountMaxAmount::type_

      attr_accessor value: Float

      def initialize:
        (
          type: Metronome::Models::RolloverAmountMaxAmount::type_,
          value: Float
        ) -> void
        | (
          ?Metronome::Models::rollover_amount_max_amount
          | Metronome::BaseModel data
        ) -> void

      def to_hash: -> Metronome::Models::rollover_amount_max_amount

      type type_ = :MAX_AMOUNT

      class Type < Metronome::Enum
        MAX_AMOUNT: :MAX_AMOUNT

        def self.values: -> Array[Metronome::Models::RolloverAmountMaxAmount::type_]
      end
    end
  end
end
