module Metronome
  module Models
    type rollover_amount_max_percentage =
      {
        type: Metronome::Models::RolloverAmountMaxPercentage::type_,
        value: Float
      }

    class RolloverAmountMaxPercentage < Metronome::BaseModel
      attr_accessor type: Metronome::Models::RolloverAmountMaxPercentage::type_

      attr_accessor value: Float

      def initialize:
        (
          type: Metronome::Models::RolloverAmountMaxPercentage::type_,
          value: Float
        ) -> void
        | (
          ?Metronome::Models::rollover_amount_max_percentage
          | Metronome::BaseModel data
        ) -> void

      def to_hash: -> Metronome::Models::rollover_amount_max_percentage

      type type_ = :MAX_PERCENTAGE

      class Type < Metronome::Enum
        MAX_PERCENTAGE: :MAX_PERCENTAGE

        def self.values: -> Array[Metronome::Models::RolloverAmountMaxPercentage::type_]
      end
    end
  end
end
