module Metronome
  module Models
    type schedule_point_in_time =
      {
        credit_type: Metronome::Models::CreditTypeData,
        schedule_items: Array[Metronome::Models::SchedulePointInTime::ScheduleItem]
      }

    class SchedulePointInTime < Metronome::BaseModel
      attr_reader credit_type: Metronome::Models::CreditTypeData?

      def credit_type=: (Metronome::Models::CreditTypeData) -> void

      attr_reader schedule_items: Array[Metronome::Models::SchedulePointInTime::ScheduleItem]?

      def schedule_items=: (
        Array[Metronome::Models::SchedulePointInTime::ScheduleItem]
      ) -> void

      def initialize:
        (
          credit_type: Metronome::Models::CreditTypeData,
          schedule_items: Array[Metronome::Models::SchedulePointInTime::ScheduleItem]
        ) -> void
        | (
          ?Metronome::Models::schedule_point_in_time | Metronome::BaseModel data
        ) -> void

      def to_hash: -> Metronome::Models::schedule_point_in_time

      type schedule_item =
        {
          id: String,
          amount: Float,
          invoice_id: String,
          quantity: Float,
          timestamp: Time,
          unit_price: Float
        }

      class ScheduleItem < Metronome::BaseModel
        attr_accessor id: String

        attr_accessor amount: Float

        attr_accessor invoice_id: String

        attr_accessor quantity: Float

        attr_accessor timestamp: Time

        attr_accessor unit_price: Float

        def initialize:
          (
            id: String,
            amount: Float,
            invoice_id: String,
            quantity: Float,
            timestamp: Time,
            unit_price: Float
          ) -> void
          | (
            ?Metronome::Models::SchedulePointInTime::schedule_item
            | Metronome::BaseModel data
          ) -> void

        def to_hash: -> Metronome::Models::SchedulePointInTime::schedule_item
      end
    end
  end
end
