module MetronomeSDK
  module Resources
    class V1
      class BillableMetrics
        def create: (
          name: String,
          ?aggregation_key: String,
          ?aggregation_type: MetronomeSDK::Models::V1::BillableMetricCreateParams::aggregation_type,
          ?custom_fields: ::Hash[Symbol, String],
          ?event_type_filter: MetronomeSDK::V1::BillableMetricCreateParams::EventTypeFilter,
          ?group_keys: ::Array[::Array[String]],
          ?property_filters: ::Array[MetronomeSDK::V1::BillableMetricCreateParams::PropertyFilter],
          ?sql: String,
          ?request_options: MetronomeSDK::request_opts
        ) -> MetronomeSDK::Models::V1::BillableMetricCreateResponse

        def retrieve: (
          billable_metric_id: String,
          ?request_options: MetronomeSDK::request_opts
        ) -> MetronomeSDK::Models::V1::BillableMetricRetrieveResponse

        def list: (
          ?include_archived: bool,
          ?limit: Integer,
          ?next_page: String,
          ?request_options: MetronomeSDK::request_opts
        ) -> MetronomeSDK::Internal::CursorPage[MetronomeSDK::Models::V1::BillableMetricListResponse]

        def archive: (
          id: String,
          ?request_options: MetronomeSDK::request_opts
        ) -> MetronomeSDK::Models::V1::BillableMetricArchiveResponse

        def initialize: (client: MetronomeSDK::Client) -> void
      end
    end
  end
end
