module MetronomeSDK
  module Resources
    class V1
      class CreditGrants
        def create: (
          customer_id: String,
          expires_at: Time,
          grant_amount: MetronomeSDK::V1::CreditGrantCreateParams::GrantAmount,
          name: String,
          paid_amount: MetronomeSDK::V1::CreditGrantCreateParams::PaidAmount,
          priority: Float,
          ?credit_grant_type: String,
          ?custom_fields: ::Hash[Symbol, String],
          ?effective_at: Time,
          ?invoice_date: Time,
          ?product_ids: ::Array[String],
          ?reason: String,
          ?rollover_settings: MetronomeSDK::V1::CreditGrantCreateParams::RolloverSettings,
          ?uniqueness_key: String,
          ?request_options: MetronomeSDK::request_opts
        ) -> MetronomeSDK::Models::V1::CreditGrantCreateResponse

        def list: (
          ?limit: Integer,
          ?next_page: String,
          ?credit_grant_ids: ::Array[String],
          ?credit_type_ids: ::Array[String],
          ?customer_ids: ::Array[String],
          ?effective_before: Time,
          ?not_expiring_before: Time,
          ?request_options: MetronomeSDK::request_opts
        ) -> MetronomeSDK::Internal::CursorPage[MetronomeSDK::Models::V1::CreditGrantListResponse]

        def edit: (
          id: String,
          ?credit_grant_type: String,
          ?expires_at: Time,
          ?name: String,
          ?request_options: MetronomeSDK::request_opts
        ) -> MetronomeSDK::Models::V1::CreditGrantEditResponse

        def list_entries: (
          ?next_page: String,
          ?credit_type_ids: ::Array[String],
          ?customer_ids: ::Array[String],
          ?ending_before: Time,
          ?starting_on: Time,
          ?request_options: MetronomeSDK::request_opts
        ) -> MetronomeSDK::Models::V1::CreditGrantListEntriesResponse

        def `void`: (
          id: String,
          ?release_uniqueness_key: bool,
          ?void_credit_purchase_invoice: bool,
          ?request_options: MetronomeSDK::request_opts
        ) -> MetronomeSDK::Models::V1::CreditGrantVoidResponse

        def initialize: (client: MetronomeSDK::Client) -> void
      end
    end
  end
end
