module MetronomeSDK
  module Resources
    class V1
      class Dashboards
        def get_embeddable_url: (
          customer_id: String,
          dashboard: MetronomeSDK::Models::V1::DashboardGetEmbeddableURLParams::dashboard,
          ?bm_group_key_overrides: ::Array[MetronomeSDK::Models::V1::DashboardGetEmbeddableURLParams::BmGroupKeyOverride],
          ?color_overrides: ::Array[MetronomeSDK::Models::V1::DashboardGetEmbeddableURLParams::ColorOverride],
          ?dashboard_options: ::Array[MetronomeSDK::Models::V1::DashboardGetEmbeddableURLParams::DashboardOption],
          ?request_options: MetronomeSDK::request_opts
        ) -> MetronomeSDK::Models::V1::DashboardGetEmbeddableURLResponse

        def initialize: (client: MetronomeSDK::Client) -> void
      end
    end
  end
end
