module MetronomeSDK
  module Models
    module V1
      module Contracts
        module RateCards
          type named_schedule_update_params =
            {
              contract_id: String,
              customer_id: String,
              schedule_name: String,
              starting_at: Time,
              value: top,
              ending_before: Time
            }
            & MetronomeSDK::Internal::Type::request_parameters

          class NamedScheduleUpdateParams < MetronomeSDK::Internal::Type::BaseModel
            extend MetronomeSDK::Internal::Type::RequestParameters::Converter
            include MetronomeSDK::Internal::Type::RequestParameters

            attr_accessor contract_id: String

            attr_accessor customer_id: String

            attr_accessor schedule_name: String

            attr_accessor starting_at: Time

            attr_accessor value: top

            attr_reader ending_before: Time?

            def ending_before=: (Time) -> Time

            def initialize: (
              contract_id: String,
              customer_id: String,
              schedule_name: String,
              starting_at: Time,
              value: top,
              ?ending_before: Time,
              ?request_options: MetronomeSDK::request_opts
            ) -> void
          end
        end
      end
    end
  end
end
