module MetronomeSDK
  module Models
    module V1
      module Contracts
        module RateCards
          type product_order_update_response = { data: MetronomeSDK::ID }

          class ProductOrderUpdateResponse < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor data: MetronomeSDK::ID

            def initialize: (data: MetronomeSDK::ID) -> void

            def to_hash: -> { data: MetronomeSDK::ID }
          end
        end
      end
    end
  end
end
