module MetronomeSDK
  module Models
    module V1
      module Contracts
        module RateCards
          type product_order_update_response =
            {
              data: MetronomeSDK::Models::V1::Contracts::RateCards::ProductOrderUpdateResponse::Data
            }

          class ProductOrderUpdateResponse < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor data: MetronomeSDK::Models::V1::Contracts::RateCards::ProductOrderUpdateResponse::Data

            def initialize: (
              data: MetronomeSDK::Models::V1::Contracts::RateCards::ProductOrderUpdateResponse::Data
            ) -> void

            type data = { id: String }

            class Data < MetronomeSDK::Internal::Type::BaseModel
              attr_accessor id: String

              def initialize: (id: String) -> void
            end
          end
        end
      end
    end
  end
end
