module MetronomeSDK
  module Models
    module V1
      module Contracts
        module RateCards
          type product_order_set_response = { data: MetronomeSDK::Models::ID }

          class ProductOrderSetResponse < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor data: MetronomeSDK::Models::ID

            def initialize: (data: MetronomeSDK::Models::ID) -> void

            def to_hash: -> MetronomeSDK::Models::V1::Contracts::RateCards::product_order_set_response
          end
        end
      end
    end
  end
end
