module MetronomeSDK
  module Models
    module V1
      module Contracts
        module RateCards
          type product_order_update_params =
            {
              product_moves: ::Array[MetronomeSDK::V1::Contracts::RateCards::ProductOrderUpdateParams::ProductMove],
              rate_card_id: String
            }
            & MetronomeSDK::Internal::Type::request_parameters

          class ProductOrderUpdateParams < MetronomeSDK::Internal::Type::BaseModel
            extend MetronomeSDK::Internal::Type::RequestParameters::Converter
            include MetronomeSDK::Internal::Type::RequestParameters

            attr_accessor product_moves: ::Array[MetronomeSDK::V1::Contracts::RateCards::ProductOrderUpdateParams::ProductMove]

            attr_accessor rate_card_id: String

            def initialize: (
              product_moves: ::Array[MetronomeSDK::V1::Contracts::RateCards::ProductOrderUpdateParams::ProductMove],
              rate_card_id: String,
              ?request_options: MetronomeSDK::request_opts
            ) -> void

            type product_move = { position: Float, product_id: String }

            class ProductMove < MetronomeSDK::Internal::Type::BaseModel
              attr_accessor position: Float

              attr_accessor product_id: String

              def initialize: (position: Float, product_id: String) -> void
            end
          end
        end
      end
    end
  end
end
