module MetronomeSDK
  module Resources
    class V1
      class Contracts
        class RateCards
          attr_reader product_orders: MetronomeSDK::Resources::V1::Contracts::RateCards::ProductOrders

          attr_reader rates: MetronomeSDK::Resources::V1::Contracts::RateCards::Rates

          attr_reader named_schedules: MetronomeSDK::Resources::V1::Contracts::RateCards::NamedSchedules

          def create: (
            name: String,
            ?aliases: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardCreateParams::Alias],
            ?credit_type_conversions: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardCreateParams::CreditTypeConversion],
            ?custom_fields: ::Hash[Symbol, String],
            ?description: String,
            ?fiat_credit_type_id: String,
            ?request_options: MetronomeSDK::request_opts
          ) -> MetronomeSDK::Models::V1::Contracts::RateCardCreateResponse

          def retrieve: (
            id: String,
            ?request_options: MetronomeSDK::request_opts
          ) -> MetronomeSDK::Models::V1::Contracts::RateCardRetrieveResponse

          def update: (
            rate_card_id: String,
            ?aliases: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardUpdateParams::Alias],
            ?description: String,
            ?name: String,
            ?request_options: MetronomeSDK::request_opts
          ) -> MetronomeSDK::Models::V1::Contracts::RateCardUpdateResponse

          def list: (
            ?limit: Integer,
            ?next_page: String,
            ?body: top,
            ?request_options: MetronomeSDK::request_opts
          ) -> MetronomeSDK::Internal::CursorPage[MetronomeSDK::Models::V1::Contracts::RateCardListResponse]

          def archive: (
            id: String,
            ?request_options: MetronomeSDK::request_opts
          ) -> MetronomeSDK::Models::V1::Contracts::RateCardArchiveResponse

          def retrieve_rate_schedule: (
            rate_card_id: String,
            starting_at: Time,
            ?limit: Integer,
            ?next_page: String,
            ?ending_before: Time,
            ?selectors: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleParams::Selector],
            ?request_options: MetronomeSDK::request_opts
          ) -> MetronomeSDK::Models::V1::Contracts::RateCardRetrieveRateScheduleResponse

          def initialize: (client: MetronomeSDK::Client) -> void
        end
      end
    end
  end
end
