module Metronome
  module Resources
    class Customers
      class Alerts
        def retrieve:
          (
            Metronome::Models::Customers::AlertRetrieveParams
            | Hash[Symbol, top] params
          ) -> Metronome::Models::Customers::AlertRetrieveResponse
          | (
            alert_id: String,
            customer_id: String,
            request_options: Metronome::request_opts
          ) -> Metronome::Models::Customers::AlertRetrieveResponse

        def list:
          (
            Metronome::Models::Customers::AlertListParams
            | Hash[Symbol, top] params
          ) -> Metronome::Models::Customers::AlertListResponse
          | (
            customer_id: String,
            next_page: String,
            alert_statuses: Array[Metronome::Models::Customers::AlertListParams::alert_status],
            request_options: Metronome::request_opts
          ) -> Metronome::Models::Customers::AlertListResponse

        def reset:
          (
            Metronome::Models::Customers::AlertResetParams
            | Hash[Symbol, top] params
          ) -> nil
          | (
            alert_id: String,
            customer_id: String,
            request_options: Metronome::request_opts
          ) -> nil

        def initialize: (client: Metronome::Client) -> void
      end
    end
  end
end
