module Metronome
  module Resources
    class Customers
      class Credits
        def create:
          (
            Metronome::Models::Customers::CreditCreateParams
            | ::Hash[Symbol, top] params
          ) -> Metronome::Models::Customers::CreditCreateResponse
          | (
            access_schedule: Metronome::Models::Customers::CreditCreateParams::AccessSchedule,
            customer_id: String,
            priority: Float,
            product_id: String,
            applicable_contract_ids: ::Array[String],
            applicable_product_ids: ::Array[String],
            applicable_product_tags: ::Array[String],
            custom_fields: ::Hash[Symbol, String],
            description: String,
            name: String,
            netsuite_sales_order_id: String,
            rate_type: Metronome::Models::Customers::CreditCreateParams::rate_type,
            salesforce_opportunity_id: String,
            uniqueness_key: String,
            request_options: Metronome::request_opts
          ) -> Metronome::Models::Customers::CreditCreateResponse

        def list:
          (
            Metronome::Models::Customers::CreditListParams
            | ::Hash[Symbol, top] params
          ) -> Metronome::Models::Customers::CreditListResponse
          | (
            customer_id: String,
            covering_date: Time,
            credit_id: String,
            effective_before: Time,
            include_archived: bool,
            include_balance: bool,
            include_contract_credits: bool,
            include_ledgers: bool,
            next_page: String,
            starting_at: Time,
            request_options: Metronome::request_opts
          ) -> Metronome::Models::Customers::CreditListResponse

        def update_end_date:
          (
            Metronome::Models::Customers::CreditUpdateEndDateParams
            | ::Hash[Symbol, top] params
          ) -> Metronome::Models::Customers::CreditUpdateEndDateResponse
          | (
            access_ending_before: Time,
            credit_id: String,
            customer_id: String,
            request_options: Metronome::request_opts
          ) -> Metronome::Models::Customers::CreditUpdateEndDateResponse

        def initialize: (client: Metronome::Client) -> void
      end
    end
  end
end
