module Metronome
  module Resources
    class Customers
      class NamedSchedules
        def retrieve:
          (
            Metronome::Models::Customers::NamedScheduleRetrieveParams
            | ::Hash[Symbol, top] params
          ) -> Metronome::Models::Customers::NamedScheduleRetrieveResponse
          | (
            customer_id: String,
            schedule_name: String,
            covering_date: Time,
            request_options: Metronome::request_opts
          ) -> Metronome::Models::Customers::NamedScheduleRetrieveResponse

        def update:
          (
            Metronome::Models::Customers::NamedScheduleUpdateParams
            | ::Hash[Symbol, top] params
          ) -> nil
          | (
            customer_id: String,
            schedule_name: String,
            starting_at: Time,
            value: top,
            ending_before: Time,
            request_options: Metronome::request_opts
          ) -> nil

        def initialize: (client: Metronome::Client) -> void
      end
    end
  end
end
