module MetronomeSDK
  module Models
    module V2
      type contract_edit_credit_params =
        {
          credit_id: String,
          customer_id: String,
          access_schedule: MetronomeSDK::V2::ContractEditCreditParams::AccessSchedule,
          applicable_product_ids: ::Array[String]?,
          applicable_product_tags: ::Array[String]?,
          product_id: String,
          specifiers: ::Array[MetronomeSDK::V2::ContractEditCreditParams::Specifier]
        }
        & MetronomeSDK::Internal::Type::request_parameters

      class ContractEditCreditParams < MetronomeSDK::Internal::Type::BaseModel
        extend MetronomeSDK::Internal::Type::RequestParameters::Converter
        include MetronomeSDK::Internal::Type::RequestParameters

        attr_accessor credit_id: String

        attr_accessor customer_id: String

        attr_reader access_schedule: MetronomeSDK::V2::ContractEditCreditParams::AccessSchedule?

        def access_schedule=: (
          MetronomeSDK::V2::ContractEditCreditParams::AccessSchedule
        ) -> MetronomeSDK::V2::ContractEditCreditParams::AccessSchedule

        attr_accessor applicable_product_ids: ::Array[String]?

        attr_accessor applicable_product_tags: ::Array[String]?

        attr_reader product_id: String?

        def product_id=: (String) -> String

        attr_reader specifiers: ::Array[MetronomeSDK::V2::ContractEditCreditParams::Specifier]?

        def specifiers=: (
          ::Array[MetronomeSDK::V2::ContractEditCreditParams::Specifier]
        ) -> ::Array[MetronomeSDK::V2::ContractEditCreditParams::Specifier]

        def initialize: (
          credit_id: String,
          customer_id: String,
          ?access_schedule: MetronomeSDK::V2::ContractEditCreditParams::AccessSchedule,
          ?applicable_product_ids: ::Array[String]?,
          ?applicable_product_tags: ::Array[String]?,
          ?product_id: String,
          ?specifiers: ::Array[MetronomeSDK::V2::ContractEditCreditParams::Specifier],
          ?request_options: MetronomeSDK::request_opts
        ) -> void

        def to_hash: -> {
          credit_id: String,
          customer_id: String,
          access_schedule: MetronomeSDK::V2::ContractEditCreditParams::AccessSchedule,
          applicable_product_ids: ::Array[String]?,
          applicable_product_tags: ::Array[String]?,
          product_id: String,
          specifiers: ::Array[MetronomeSDK::V2::ContractEditCreditParams::Specifier],
          request_options: MetronomeSDK::RequestOptions
        }

        type access_schedule =
          {
            add_schedule_items: ::Array[MetronomeSDK::V2::ContractEditCreditParams::AccessSchedule::AddScheduleItem],
            remove_schedule_items: ::Array[MetronomeSDK::V2::ContractEditCreditParams::AccessSchedule::RemoveScheduleItem],
            update_schedule_items: ::Array[MetronomeSDK::V2::ContractEditCreditParams::AccessSchedule::UpdateScheduleItem]
          }

        class AccessSchedule < MetronomeSDK::Internal::Type::BaseModel
          attr_reader add_schedule_items: ::Array[MetronomeSDK::V2::ContractEditCreditParams::AccessSchedule::AddScheduleItem]?

          def add_schedule_items=: (
            ::Array[MetronomeSDK::V2::ContractEditCreditParams::AccessSchedule::AddScheduleItem]
          ) -> ::Array[MetronomeSDK::V2::ContractEditCreditParams::AccessSchedule::AddScheduleItem]

          attr_reader remove_schedule_items: ::Array[MetronomeSDK::V2::ContractEditCreditParams::AccessSchedule::RemoveScheduleItem]?

          def remove_schedule_items=: (
            ::Array[MetronomeSDK::V2::ContractEditCreditParams::AccessSchedule::RemoveScheduleItem]
          ) -> ::Array[MetronomeSDK::V2::ContractEditCreditParams::AccessSchedule::RemoveScheduleItem]

          attr_reader update_schedule_items: ::Array[MetronomeSDK::V2::ContractEditCreditParams::AccessSchedule::UpdateScheduleItem]?

          def update_schedule_items=: (
            ::Array[MetronomeSDK::V2::ContractEditCreditParams::AccessSchedule::UpdateScheduleItem]
          ) -> ::Array[MetronomeSDK::V2::ContractEditCreditParams::AccessSchedule::UpdateScheduleItem]

          def initialize: (
            ?add_schedule_items: ::Array[MetronomeSDK::V2::ContractEditCreditParams::AccessSchedule::AddScheduleItem],
            ?remove_schedule_items: ::Array[MetronomeSDK::V2::ContractEditCreditParams::AccessSchedule::RemoveScheduleItem],
            ?update_schedule_items: ::Array[MetronomeSDK::V2::ContractEditCreditParams::AccessSchedule::UpdateScheduleItem]
          ) -> void

          def to_hash: -> {
            add_schedule_items: ::Array[MetronomeSDK::V2::ContractEditCreditParams::AccessSchedule::AddScheduleItem],
            remove_schedule_items: ::Array[MetronomeSDK::V2::ContractEditCreditParams::AccessSchedule::RemoveScheduleItem],
            update_schedule_items: ::Array[MetronomeSDK::V2::ContractEditCreditParams::AccessSchedule::UpdateScheduleItem]
          }

          type add_schedule_item =
            { amount: Float, ending_before: Time, starting_at: Time }

          class AddScheduleItem < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor amount: Float

            attr_accessor ending_before: Time

            attr_accessor starting_at: Time

            def initialize: (
              amount: Float,
              ending_before: Time,
              starting_at: Time
            ) -> void

            def to_hash: -> {
              amount: Float,
              ending_before: Time,
              starting_at: Time
            }
          end

          type remove_schedule_item = { id: String }

          class RemoveScheduleItem < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor id: String

            def initialize: (id: String) -> void

            def to_hash: -> { id: String }
          end

          type update_schedule_item =
            {
              id: String,
              amount: Float,
              ending_before: Time,
              starting_at: Time
            }

          class UpdateScheduleItem < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor id: String

            attr_reader amount: Float?

            def amount=: (Float) -> Float

            attr_reader ending_before: Time?

            def ending_before=: (Time) -> Time

            attr_reader starting_at: Time?

            def starting_at=: (Time) -> Time

            def initialize: (
              id: String,
              ?amount: Float,
              ?ending_before: Time,
              ?starting_at: Time
            ) -> void

            def to_hash: -> {
              id: String,
              amount: Float,
              ending_before: Time,
              starting_at: Time
            }
          end
        end

        type specifier =
          {
            presentation_group_values: ::Hash[Symbol, String],
            pricing_group_values: ::Hash[Symbol, String],
            product_id: String,
            product_tags: ::Array[String]
          }

        class Specifier < MetronomeSDK::Internal::Type::BaseModel
          attr_reader presentation_group_values: ::Hash[Symbol, String]?

          def presentation_group_values=: (
            ::Hash[Symbol, String]
          ) -> ::Hash[Symbol, String]

          attr_reader pricing_group_values: ::Hash[Symbol, String]?

          def pricing_group_values=: (
            ::Hash[Symbol, String]
          ) -> ::Hash[Symbol, String]

          attr_reader product_id: String?

          def product_id=: (String) -> String

          attr_reader product_tags: ::Array[String]?

          def product_tags=: (::Array[String]) -> ::Array[String]

          def initialize: (
            ?presentation_group_values: ::Hash[Symbol, String],
            ?pricing_group_values: ::Hash[Symbol, String],
            ?product_id: String,
            ?product_tags: ::Array[String]
          ) -> void

          def to_hash: -> {
            presentation_group_values: ::Hash[Symbol, String],
            pricing_group_values: ::Hash[Symbol, String],
            product_id: String,
            product_tags: ::Array[String]
          }
        end
      end
    end
  end
end
