module MetronomeSDK
  module Models
    module V2
      type contract_edit_commit_response = { data: MetronomeSDK::ID }

      class ContractEditCommitResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor data: MetronomeSDK::ID

        def initialize: (data: MetronomeSDK::ID) -> void
      end
    end
  end
end
