module MetronomeSDK
  module Models
    module V2
      type contract_retrieve_response = { data: MetronomeSDK::ContractV2 }

      class ContractRetrieveResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor data: MetronomeSDK::ContractV2

        def initialize: (data: MetronomeSDK::ContractV2) -> void

        def to_hash: -> { data: MetronomeSDK::ContractV2 }
      end
    end
  end
end
