module MetronomeSDK
  module Models
    module V2
      type contract_edit_credit_response =
        { data: MetronomeSDK::Models::V2::ContractEditCreditResponse::Data }

      class ContractEditCreditResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor data: MetronomeSDK::Models::V2::ContractEditCreditResponse::Data

        def initialize: (
          data: MetronomeSDK::Models::V2::ContractEditCreditResponse::Data
        ) -> void

        type data = { id: String }

        class Data < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor id: String

          def initialize: (id: String) -> void
        end
      end
    end
  end
end
