module MetronomeSDK
  module Models
    module V2
      type contract_list_response = { data: ::Array[MetronomeSDK::ContractV2] }

      class ContractListResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor data: ::Array[MetronomeSDK::ContractV2]

        def initialize: (data: ::Array[MetronomeSDK::ContractV2]) -> void

        def to_hash: -> { data: ::Array[MetronomeSDK::ContractV2] }
      end
    end
  end
end
