module MetronomeSDK
  module Models
    module V2
      type contract_edit_commit_params =
        {
          commit_id: String,
          customer_id: String,
          access_schedule: MetronomeSDK::Models::V2::ContractEditCommitParams::AccessSchedule,
          applicable_product_ids: ::Array[String]?,
          applicable_product_tags: ::Array[String]?,
          invoice_contract_id: String,
          invoice_schedule: MetronomeSDK::Models::V2::ContractEditCommitParams::InvoiceSchedule,
          product_id: String
        }
        & MetronomeSDK::Internal::Type::request_parameters

      class ContractEditCommitParams < MetronomeSDK::Internal::Type::BaseModel
        extend MetronomeSDK::Internal::Type::RequestParameters::Converter
        include MetronomeSDK::Internal::Type::RequestParameters

        attr_accessor commit_id: String

        attr_accessor customer_id: String

        attr_reader access_schedule: MetronomeSDK::Models::V2::ContractEditCommitParams::AccessSchedule?

        def access_schedule=: (
          MetronomeSDK::Models::V2::ContractEditCommitParams::AccessSchedule
        ) -> MetronomeSDK::Models::V2::ContractEditCommitParams::AccessSchedule

        attr_accessor applicable_product_ids: ::Array[String]?

        attr_accessor applicable_product_tags: ::Array[String]?

        attr_reader invoice_contract_id: String?

        def invoice_contract_id=: (String) -> String

        attr_reader invoice_schedule: MetronomeSDK::Models::V2::ContractEditCommitParams::InvoiceSchedule?

        def invoice_schedule=: (
          MetronomeSDK::Models::V2::ContractEditCommitParams::InvoiceSchedule
        ) -> MetronomeSDK::Models::V2::ContractEditCommitParams::InvoiceSchedule

        attr_reader product_id: String?

        def product_id=: (String) -> String

        def initialize: (
          commit_id: String,
          customer_id: String,
          ?access_schedule: MetronomeSDK::Models::V2::ContractEditCommitParams::AccessSchedule,
          ?applicable_product_ids: ::Array[String]?,
          ?applicable_product_tags: ::Array[String]?,
          ?invoice_contract_id: String,
          ?invoice_schedule: MetronomeSDK::Models::V2::ContractEditCommitParams::InvoiceSchedule,
          ?product_id: String,
          ?request_options: MetronomeSDK::request_opts
        ) -> void

        def to_hash: -> MetronomeSDK::Models::V2::contract_edit_commit_params

        type access_schedule =
          {
            add_schedule_items: ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::AccessSchedule::AddScheduleItem],
            remove_schedule_items: ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::AccessSchedule::RemoveScheduleItem],
            update_schedule_items: ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::AccessSchedule::UpdateScheduleItem]
          }

        class AccessSchedule < MetronomeSDK::Internal::Type::BaseModel
          attr_reader add_schedule_items: ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::AccessSchedule::AddScheduleItem]?

          def add_schedule_items=: (
            ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::AccessSchedule::AddScheduleItem]
          ) -> ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::AccessSchedule::AddScheduleItem]

          attr_reader remove_schedule_items: ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::AccessSchedule::RemoveScheduleItem]?

          def remove_schedule_items=: (
            ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::AccessSchedule::RemoveScheduleItem]
          ) -> ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::AccessSchedule::RemoveScheduleItem]

          attr_reader update_schedule_items: ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::AccessSchedule::UpdateScheduleItem]?

          def update_schedule_items=: (
            ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::AccessSchedule::UpdateScheduleItem]
          ) -> ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::AccessSchedule::UpdateScheduleItem]

          def initialize: (
            ?add_schedule_items: ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::AccessSchedule::AddScheduleItem],
            ?remove_schedule_items: ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::AccessSchedule::RemoveScheduleItem],
            ?update_schedule_items: ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::AccessSchedule::UpdateScheduleItem]
          ) -> void

          def to_hash: -> MetronomeSDK::Models::V2::ContractEditCommitParams::access_schedule

          type add_schedule_item =
            { amount: Float, ending_before: Time, starting_at: Time }

          class AddScheduleItem < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor amount: Float

            attr_accessor ending_before: Time

            attr_accessor starting_at: Time

            def initialize: (
              amount: Float,
              ending_before: Time,
              starting_at: Time
            ) -> void

            def to_hash: -> MetronomeSDK::Models::V2::ContractEditCommitParams::AccessSchedule::add_schedule_item
          end

          type remove_schedule_item = { id: String }

          class RemoveScheduleItem < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor id: String

            def initialize: (id: String) -> void

            def to_hash: -> MetronomeSDK::Models::V2::ContractEditCommitParams::AccessSchedule::remove_schedule_item
          end

          type update_schedule_item =
            {
              id: String,
              amount: Float,
              ending_before: Time,
              starting_at: Time
            }

          class UpdateScheduleItem < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor id: String

            attr_reader amount: Float?

            def amount=: (Float) -> Float

            attr_reader ending_before: Time?

            def ending_before=: (Time) -> Time

            attr_reader starting_at: Time?

            def starting_at=: (Time) -> Time

            def initialize: (
              id: String,
              ?amount: Float,
              ?ending_before: Time,
              ?starting_at: Time
            ) -> void

            def to_hash: -> MetronomeSDK::Models::V2::ContractEditCommitParams::AccessSchedule::update_schedule_item
          end
        end

        type invoice_schedule =
          {
            add_schedule_items: ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::InvoiceSchedule::AddScheduleItem],
            remove_schedule_items: ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::InvoiceSchedule::RemoveScheduleItem],
            update_schedule_items: ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::InvoiceSchedule::UpdateScheduleItem]
          }

        class InvoiceSchedule < MetronomeSDK::Internal::Type::BaseModel
          attr_reader add_schedule_items: ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::InvoiceSchedule::AddScheduleItem]?

          def add_schedule_items=: (
            ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::InvoiceSchedule::AddScheduleItem]
          ) -> ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::InvoiceSchedule::AddScheduleItem]

          attr_reader remove_schedule_items: ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::InvoiceSchedule::RemoveScheduleItem]?

          def remove_schedule_items=: (
            ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::InvoiceSchedule::RemoveScheduleItem]
          ) -> ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::InvoiceSchedule::RemoveScheduleItem]

          attr_reader update_schedule_items: ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::InvoiceSchedule::UpdateScheduleItem]?

          def update_schedule_items=: (
            ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::InvoiceSchedule::UpdateScheduleItem]
          ) -> ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::InvoiceSchedule::UpdateScheduleItem]

          def initialize: (
            ?add_schedule_items: ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::InvoiceSchedule::AddScheduleItem],
            ?remove_schedule_items: ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::InvoiceSchedule::RemoveScheduleItem],
            ?update_schedule_items: ::Array[MetronomeSDK::Models::V2::ContractEditCommitParams::InvoiceSchedule::UpdateScheduleItem]
          ) -> void

          def to_hash: -> MetronomeSDK::Models::V2::ContractEditCommitParams::invoice_schedule

          type add_schedule_item =
            {
              timestamp: Time,
              amount: Float,
              quantity: Float,
              unit_price: Float
            }

          class AddScheduleItem < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor timestamp: Time

            attr_reader amount: Float?

            def amount=: (Float) -> Float

            attr_reader quantity: Float?

            def quantity=: (Float) -> Float

            attr_reader unit_price: Float?

            def unit_price=: (Float) -> Float

            def initialize: (
              timestamp: Time,
              ?amount: Float,
              ?quantity: Float,
              ?unit_price: Float
            ) -> void

            def to_hash: -> MetronomeSDK::Models::V2::ContractEditCommitParams::InvoiceSchedule::add_schedule_item
          end

          type remove_schedule_item = { id: String }

          class RemoveScheduleItem < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor id: String

            def initialize: (id: String) -> void

            def to_hash: -> MetronomeSDK::Models::V2::ContractEditCommitParams::InvoiceSchedule::remove_schedule_item
          end

          type update_schedule_item =
            {
              id: String,
              amount: Float,
              quantity: Float,
              timestamp: Time,
              unit_price: Float
            }

          class UpdateScheduleItem < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor id: String

            attr_reader amount: Float?

            def amount=: (Float) -> Float

            attr_reader quantity: Float?

            def quantity=: (Float) -> Float

            attr_reader timestamp: Time?

            def timestamp=: (Time) -> Time

            attr_reader unit_price: Float?

            def unit_price=: (Float) -> Float

            def initialize: (
              id: String,
              ?amount: Float,
              ?quantity: Float,
              ?timestamp: Time,
              ?unit_price: Float
            ) -> void

            def to_hash: -> MetronomeSDK::Models::V2::ContractEditCommitParams::InvoiceSchedule::update_schedule_item
          end
        end
      end
    end
  end
end
