module MetronomeSDK
  module Models
    module V2
      type contract_list_params =
        {
          customer_id: String,
          covering_date: Time,
          include_archived: bool,
          include_balance: bool,
          include_ledgers: bool,
          starting_at: Time
        }
        & MetronomeSDK::Internal::Type::request_parameters

      class ContractListParams < MetronomeSDK::Internal::Type::BaseModel
        extend MetronomeSDK::Internal::Type::RequestParameters::Converter
        include MetronomeSDK::Internal::Type::RequestParameters

        attr_accessor customer_id: String

        attr_reader covering_date: Time?

        def covering_date=: (Time) -> Time

        attr_reader include_archived: bool?

        def include_archived=: (bool) -> bool

        attr_reader include_balance: bool?

        def include_balance=: (bool) -> bool

        attr_reader include_ledgers: bool?

        def include_ledgers=: (bool) -> bool

        attr_reader starting_at: Time?

        def starting_at=: (Time) -> Time

        def initialize: (
          customer_id: String,
          ?covering_date: Time,
          ?include_archived: bool,
          ?include_balance: bool,
          ?include_ledgers: bool,
          ?starting_at: Time,
          ?request_options: MetronomeSDK::request_opts
        ) -> void

        def to_hash: -> {
          customer_id: String,
          covering_date: Time,
          include_archived: bool,
          include_balance: bool,
          include_ledgers: bool,
          starting_at: Time,
          request_options: MetronomeSDK::RequestOptions
        }
      end
    end
  end
end
