module MetronomeSDK
  module Models
    module V2
      type contract_edit_response =
        { data: MetronomeSDK::Models::V2::ContractEditResponse::Data }

      class ContractEditResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor data: MetronomeSDK::Models::V2::ContractEditResponse::Data

        def initialize: (
          data: MetronomeSDK::Models::V2::ContractEditResponse::Data
        ) -> void

        def to_hash: -> {
          data: MetronomeSDK::Models::V2::ContractEditResponse::Data
        }

        type data = { id: String }

        class Data < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor id: String

          def initialize: (id: String) -> void

          def to_hash: -> { id: String }
        end
      end
    end
  end
end
