module MetronomeSDK
  module Models
    module V2
      type lifecycle_event_system_notification_config =
        {
          policy: MetronomeSDK::V2::LifecycleEventSystemPolicy,
          type: MetronomeSDK::Models::V2::LifecycleEventSystemNotificationConfig::type_,
          is_enabled: bool
        }

      class LifecycleEventSystemNotificationConfig < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor policy: MetronomeSDK::V2::LifecycleEventSystemPolicy

        attr_accessor type: MetronomeSDK::Models::V2::LifecycleEventSystemNotificationConfig::type_

        attr_reader is_enabled: bool?

        def is_enabled=: (bool) -> bool

        def initialize: (
          policy: MetronomeSDK::V2::LifecycleEventSystemPolicy,
          type: MetronomeSDK::Models::V2::LifecycleEventSystemNotificationConfig::type_,
          ?is_enabled: bool
        ) -> void

        def to_hash: -> {
          policy: MetronomeSDK::V2::LifecycleEventSystemPolicy,
          type: MetronomeSDK::Models::V2::LifecycleEventSystemNotificationConfig::type_,
          is_enabled: bool
        }

        type type_ = :SYSTEM_LIFECYCLE_EVENT

        module Type
          extend MetronomeSDK::Internal::Type::Enum

          SYSTEM_LIFECYCLE_EVENT: :SYSTEM_LIFECYCLE_EVENT

          def self?.values: -> ::Array[MetronomeSDK::Models::V2::LifecycleEventSystemNotificationConfig::type_]
        end
      end
    end
  end
end
