module MetronomeSDK
  module Models
    module V2
      type lifecycle_event_offset_policy = { offset: String, type: String }

      class LifecycleEventOffsetPolicy < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor offset: String

        attr_accessor type: String

        def initialize: (offset: String, type: String) -> void

        def to_hash: -> { offset: String, type: String }
      end
    end
  end
end
