module MetronomeSDK
  module Models
    module V2
      type notification_list_offset_response =
        {
          data: ::Array[MetronomeSDK::V2::LifecycleEventOffsetNotificationConfig],
          cursor: String?
        }

      class NotificationListOffsetResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor data: ::Array[MetronomeSDK::V2::LifecycleEventOffsetNotificationConfig]

        attr_accessor cursor: String?

        def initialize: (
          data: ::Array[MetronomeSDK::V2::LifecycleEventOffsetNotificationConfig],
          ?cursor: String?
        ) -> void

        def to_hash: -> {
          data: ::Array[MetronomeSDK::V2::LifecycleEventOffsetNotificationConfig],
          cursor: String?
        }
      end
    end
  end
end
