module MetronomeSDK
  module Models
    module V2
      type notification_create_response =
        { data: MetronomeSDK::V2::LifecycleEventOffsetNotificationConfig }

      class NotificationCreateResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor data: MetronomeSDK::V2::LifecycleEventOffsetNotificationConfig

        def initialize: (
          data: MetronomeSDK::V2::LifecycleEventOffsetNotificationConfig
        ) -> void

        def to_hash: -> {
          data: MetronomeSDK::V2::LifecycleEventOffsetNotificationConfig
        }
      end
    end
  end
end
