module Metronome
  module Resources
    class BillableMetrics
      def create:
        (
          Metronome::Models::BillableMetricCreateParams
          | Hash[Symbol, top] params
        ) -> Metronome::Models::BillableMetricCreateResponse
        | (
          name: String,
          aggregation_key: String,
          aggregation_type: Metronome::Models::BillableMetricCreateParams::aggregation_type,
          custom_fields: Hash[Symbol, String],
          event_type_filter: Metronome::Models::EventTypeFilter,
          group_keys: Array[Array[String]],
          property_filters: Array[Metronome::Models::PropertyFilter],
          sql: String,
          request_options: Metronome::request_opts
        ) -> Metronome::Models::BillableMetricCreateResponse

      def retrieve:
        (
          Metronome::Models::BillableMetricRetrieveParams
          | Hash[Symbol, top] params
        ) -> Metronome::Models::BillableMetricRetrieveResponse
        | (
          billable_metric_id: String,
          request_options: Metronome::request_opts
        ) -> Metronome::Models::BillableMetricRetrieveResponse

      def list:
        (
          ?Metronome::Models::BillableMetricListParams
          | Hash[Symbol, top] params
        ) -> Metronome::CursorPage[Metronome::Models::BillableMetricListResponse]
        | (
          include_archived: bool,
          limit: Integer,
          next_page: String,
          request_options: Metronome::request_opts
        ) -> Metronome::CursorPage[Metronome::Models::BillableMetricListResponse]

      def archive:
        (
          Metronome::Models::BillableMetricArchiveParams
          | Hash[Symbol, top] params
        ) -> Metronome::Models::BillableMetricArchiveResponse
        | (
          id: String,
          request_options: Metronome::request_opts
        ) -> Metronome::Models::BillableMetricArchiveResponse

      def initialize: (client: Metronome::Client) -> void
    end
  end
end
