module Metronome
  module Resources
    class Plans
      def list:
        (
          ?Metronome::Models::PlanListParams | Hash[Symbol, top] params
        ) -> Metronome::CursorPage[Metronome::Models::PlanListResponse]
        | (
          limit: Integer,
          next_page: String,
          request_options: Metronome::request_opts
        ) -> Metronome::CursorPage[Metronome::Models::PlanListResponse]

      def get_details:
        (
          Metronome::Models::PlanGetDetailsParams | Hash[Symbol, top] params
        ) -> Metronome::Models::PlanGetDetailsResponse
        | (
          Metronome::Models::PlanGetDetailsParams | Hash[Symbol, top] params,
          plan_id: String,
          request_options: Metronome::request_opts
        ) -> Metronome::Models::PlanGetDetailsResponse

      def list_charges:
        (
          Metronome::Models::PlanListChargesParams | Hash[Symbol, top] params
        ) -> Metronome::CursorPage[Metronome::Models::PlanListChargesResponse]
        | (
          Metronome::Models::PlanListChargesParams | Hash[Symbol, top] params,
          plan_id: String,
          limit: Integer,
          next_page: String,
          request_options: Metronome::request_opts
        ) -> Metronome::CursorPage[Metronome::Models::PlanListChargesResponse]

      def list_customers:
        (
          Metronome::Models::PlanListCustomersParams | Hash[Symbol, top] params
        ) -> Metronome::CursorPage[Metronome::Models::PlanListCustomersResponse]
        | (
          Metronome::Models::PlanListCustomersParams | Hash[Symbol, top] params,
          plan_id: String,
          limit: Integer,
          next_page: String,
          status: Metronome::Models::PlanListCustomersParams::status,
          request_options: Metronome::request_opts
        ) -> Metronome::CursorPage[Metronome::Models::PlanListCustomersResponse]

      def initialize: (client: Metronome::Client) -> void
    end
  end
end
