module Metronome
  module Resources
    class PricingUnits
      def list:
        (
          ?Metronome::Models::PricingUnitListParams | ::Hash[Symbol, top] params
        ) -> Metronome::CursorPage[Metronome::Models::PricingUnitListResponse]
        | (
          limit: Integer,
          next_page: String,
          request_options: Metronome::request_opts
        ) -> Metronome::CursorPage[Metronome::Models::PricingUnitListResponse]

      def initialize: (client: Metronome::Client) -> void
    end
  end
end
