module Metronome
  module Resources
    class Services
      def list:
        (
          ?Metronome::Models::ServiceListParams | ::Hash[Symbol, top] params
        ) -> Metronome::Models::ServiceListResponse
        | (
          request_options: Metronome::request_opts
        ) -> Metronome::Models::ServiceListResponse

      def initialize: (client: Metronome::Client) -> void
    end
  end
end
