module MetronomeSDK
  module Models
    type base_usage_filter =
      { group_key: String, group_values: ::Array[String], starting_at: Time }

    class BaseUsageFilter < MetronomeSDK::BaseModel
      attr_accessor group_key: String

      attr_accessor group_values: ::Array[String]

      attr_reader starting_at: Time?

      def starting_at=: (Time) -> Time

      def initialize:
        (
          group_key: String,
          group_values: ::Array[String],
          starting_at: Time
        ) -> void
        | (
          ?MetronomeSDK::Models::base_usage_filter
          | MetronomeSDK::BaseModel data
        ) -> void

      def to_hash: -> MetronomeSDK::Models::base_usage_filter
    end
  end
end
