module MetronomeSDK
  module Resources
    class V1
      class Customers
        class Plans
          def list:
            (
              MetronomeSDK::Models::V1::Customers::PlanListParams
              | ::Hash[Symbol, top] params
            ) -> MetronomeSDK::CursorPage[MetronomeSDK::Models::V1::Customers::PlanListResponse]
            | (
              customer_id: String,
              limit: Integer,
              next_page: String,
              request_options: MetronomeSDK::request_opts
            ) -> MetronomeSDK::CursorPage[MetronomeSDK::Models::V1::Customers::PlanListResponse]

          def add:
            (
              MetronomeSDK::Models::V1::Customers::PlanAddParams
              | ::Hash[Symbol, top] params
            ) -> MetronomeSDK::Models::V1::Customers::PlanAddResponse
            | (
              customer_id: String,
              plan_id: String,
              starting_on: Time,
              ending_before: Time,
              net_payment_terms_days: Float,
              overage_rate_adjustments: ::Array[MetronomeSDK::Models::V1::Customers::PlanAddParams::OverageRateAdjustment],
              price_adjustments: ::Array[MetronomeSDK::Models::V1::Customers::PlanAddParams::PriceAdjustment],
              trial_spec: MetronomeSDK::Models::V1::Customers::PlanAddParams::TrialSpec,
              request_options: MetronomeSDK::request_opts
            ) -> MetronomeSDK::Models::V1::Customers::PlanAddResponse

          def end_:
            (
              MetronomeSDK::Models::V1::Customers::PlanEndParams
              | ::Hash[Symbol, top] params
            ) -> MetronomeSDK::Models::V1::Customers::PlanEndResponse
            | (
              customer_id: String,
              customer_plan_id: String,
              ending_before: Time,
              void_invoices: bool,
              void_stripe_invoices: bool,
              request_options: MetronomeSDK::request_opts
            ) -> MetronomeSDK::Models::V1::Customers::PlanEndResponse

          def list_price_adjustments:
            (
              MetronomeSDK::Models::V1::Customers::PlanListPriceAdjustmentsParams
              | ::Hash[Symbol, top] params
            ) -> MetronomeSDK::CursorPage[MetronomeSDK::Models::V1::Customers::PlanListPriceAdjustmentsResponse]
            | (
              customer_id: String,
              customer_plan_id: String,
              limit: Integer,
              next_page: String,
              request_options: MetronomeSDK::request_opts
            ) -> MetronomeSDK::CursorPage[MetronomeSDK::Models::V1::Customers::PlanListPriceAdjustmentsResponse]

          def initialize: (client: MetronomeSDK::Client) -> void
        end
      end
    end
  end
end
