module MetronomeSDK
  module Models
    module V1
      module Customers
        type alert_list_response =
          {
            data: ::Array[MetronomeSDK::V1::Customers::CustomerAlert],
            next_page: String?
          }

        class AlertListResponse < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor data: ::Array[MetronomeSDK::V1::Customers::CustomerAlert]

          attr_accessor next_page: String?

          def initialize: (
            data: ::Array[MetronomeSDK::V1::Customers::CustomerAlert],
            next_page: String?
          ) -> void
        end
      end
    end
  end
end
