module MetronomeSDK
  module Models
    module V1
      module Customers
        type alert_list_params =
          {
            customer_id: String,
            next_page: String,
            alert_statuses: ::Array[MetronomeSDK::Models::V1::Customers::AlertListParams::alert_status]
          }
          & MetronomeSDK::Internal::Type::request_parameters

        class AlertListParams < MetronomeSDK::Internal::Type::BaseModel
          extend MetronomeSDK::Internal::Type::RequestParameters::Converter
          include MetronomeSDK::Internal::Type::RequestParameters

          attr_accessor customer_id: String

          attr_reader next_page: String?

          def next_page=: (String) -> String

          attr_reader alert_statuses: ::Array[MetronomeSDK::Models::V1::Customers::AlertListParams::alert_status]?

          def alert_statuses=: (
            ::Array[MetronomeSDK::Models::V1::Customers::AlertListParams::alert_status]
          ) -> ::Array[MetronomeSDK::Models::V1::Customers::AlertListParams::alert_status]

          def initialize: (
            customer_id: String,
            ?next_page: String,
            ?alert_statuses: ::Array[MetronomeSDK::Models::V1::Customers::AlertListParams::alert_status],
            ?request_options: MetronomeSDK::request_opts
          ) -> void

          def to_hash: -> {
            customer_id: String,
            next_page: String,
            alert_statuses: ::Array[MetronomeSDK::Models::V1::Customers::AlertListParams::alert_status],
            request_options: MetronomeSDK::RequestOptions
          }

          type alert_status = :ENABLED | :DISABLED | :ARCHIVED

          module AlertStatus
            extend MetronomeSDK::Internal::Type::Enum

            ENABLED: :ENABLED
            DISABLED: :DISABLED
            ARCHIVED: :ARCHIVED

            def self?.values: -> ::Array[MetronomeSDK::Models::V1::Customers::AlertListParams::alert_status]
          end
        end
      end
    end
  end
end
