module MetronomeSDK
  module Models
    module V1
      module Customers
        type alert_retrieve_params =
          {
            alert_id: String,
            customer_id: String,
            group_values: ::Array[MetronomeSDK::V1::Customers::AlertRetrieveParams::GroupValue],
            plans_or_contracts: MetronomeSDK::Models::V1::Customers::AlertRetrieveParams::plans_or_contracts,
            seat_filter: MetronomeSDK::V1::Customers::AlertRetrieveParams::SeatFilter
          }
          & MetronomeSDK::Internal::Type::request_parameters

        class AlertRetrieveParams < MetronomeSDK::Internal::Type::BaseModel
          extend MetronomeSDK::Internal::Type::RequestParameters::Converter
          include MetronomeSDK::Internal::Type::RequestParameters

          attr_accessor alert_id: String

          attr_accessor customer_id: String

          attr_reader group_values: ::Array[MetronomeSDK::V1::Customers::AlertRetrieveParams::GroupValue]?

          def group_values=: (
            ::Array[MetronomeSDK::V1::Customers::AlertRetrieveParams::GroupValue]
          ) -> ::Array[MetronomeSDK::V1::Customers::AlertRetrieveParams::GroupValue]

          attr_reader plans_or_contracts: MetronomeSDK::Models::V1::Customers::AlertRetrieveParams::plans_or_contracts?

          def plans_or_contracts=: (
            MetronomeSDK::Models::V1::Customers::AlertRetrieveParams::plans_or_contracts
          ) -> MetronomeSDK::Models::V1::Customers::AlertRetrieveParams::plans_or_contracts

          attr_reader seat_filter: MetronomeSDK::V1::Customers::AlertRetrieveParams::SeatFilter?

          def seat_filter=: (
            MetronomeSDK::V1::Customers::AlertRetrieveParams::SeatFilter
          ) -> MetronomeSDK::V1::Customers::AlertRetrieveParams::SeatFilter

          def initialize: (
            alert_id: String,
            customer_id: String,
            ?group_values: ::Array[MetronomeSDK::V1::Customers::AlertRetrieveParams::GroupValue],
            ?plans_or_contracts: MetronomeSDK::Models::V1::Customers::AlertRetrieveParams::plans_or_contracts,
            ?seat_filter: MetronomeSDK::V1::Customers::AlertRetrieveParams::SeatFilter,
            ?request_options: MetronomeSDK::request_opts
          ) -> void

          def to_hash: -> {
            alert_id: String,
            customer_id: String,
            group_values: ::Array[MetronomeSDK::V1::Customers::AlertRetrieveParams::GroupValue],
            plans_or_contracts: MetronomeSDK::Models::V1::Customers::AlertRetrieveParams::plans_or_contracts,
            seat_filter: MetronomeSDK::V1::Customers::AlertRetrieveParams::SeatFilter,
            request_options: MetronomeSDK::RequestOptions
          }

          type group_value = { key: String, value: String }

          class GroupValue < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor key: String

            attr_accessor value: String

            def initialize: (key: String, value: String) -> void

            def to_hash: -> { key: String, value: String }
          end

          type plans_or_contracts = :PLANS | :CONTRACTS

          module PlansOrContracts
            extend MetronomeSDK::Internal::Type::Enum

            PLANS: :PLANS
            CONTRACTS: :CONTRACTS

            def self?.values: -> ::Array[MetronomeSDK::Models::V1::Customers::AlertRetrieveParams::plans_or_contracts]
          end

          type seat_filter =
            { seat_group_key: String, seat_group_value: String }

          class SeatFilter < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor seat_group_key: String

            attr_accessor seat_group_value: String

            def initialize: (
              seat_group_key: String,
              seat_group_value: String
            ) -> void

            def to_hash: -> { seat_group_key: String, seat_group_value: String }
          end
        end
      end
    end
  end
end
