module MetronomeSDK
  module Models
    module V1
      module Customers
        type alert_retrieve_response =
          { data: MetronomeSDK::V1::Customers::CustomerAlert }

        class AlertRetrieveResponse < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor data: MetronomeSDK::V1::Customers::CustomerAlert

          def initialize: (
            data: MetronomeSDK::V1::Customers::CustomerAlert
          ) -> void
        end
      end
    end
  end
end
