module MetronomeSDK
  module Models
    module V1
      module Customers
        type commit_list_response =
          { data: ::Array[MetronomeSDK::Commit], next_page: String? }

        class CommitListResponse < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor data: ::Array[MetronomeSDK::Commit]

          attr_accessor next_page: String?

          def initialize: (
            data: ::Array[MetronomeSDK::Commit],
            next_page: String?
          ) -> void
        end
      end
    end
  end
end
