module MetronomeSDK
  module Models
    module V1
      module Customers
        type commit_list_response =
          {
            data: ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data],
            next_page: String?
          }

        class CommitListResponse < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor data: ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data]

          attr_accessor next_page: String?

          def initialize: (
            data: ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data],
            next_page: String?
          ) -> void

          def to_hash: -> {
            data: ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data],
            next_page: String?
          }

          type data =
            {
              id: String,
              product: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Product,
              type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::type_,
              access_schedule: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::AccessSchedule,
              amount: Float,
              applicable_contract_ids: ::Array[String],
              applicable_product_ids: ::Array[String],
              applicable_product_tags: ::Array[String],
              archived_at: Time,
              balance: Float,
              contract: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Contract,
              custom_fields: ::Hash[Symbol, String],
              description: String,
              invoice_contract: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::InvoiceContract,
              invoice_schedule: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::InvoiceSchedule,
              ledger: ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::ledger],
              name: String,
              netsuite_sales_order_id: String,
              priority: Float,
              rate_type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::rate_type,
              rolled_over_from: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::RolledOverFrom,
              rollover_fraction: Float,
              salesforce_opportunity_id: String,
              specifiers: ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Specifier],
              uniqueness_key: String
            }

          class Data < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor product: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Product

            attr_accessor type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::type_

            attr_reader access_schedule: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::AccessSchedule?

            def access_schedule=: (
              MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::AccessSchedule
            ) -> MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::AccessSchedule

            attr_reader amount: Float?

            def amount=: (Float) -> Float

            attr_reader applicable_contract_ids: ::Array[String]?

            def applicable_contract_ids=: (::Array[String]) -> ::Array[String]

            attr_reader applicable_product_ids: ::Array[String]?

            def applicable_product_ids=: (::Array[String]) -> ::Array[String]

            attr_reader applicable_product_tags: ::Array[String]?

            def applicable_product_tags=: (::Array[String]) -> ::Array[String]

            attr_reader archived_at: Time?

            def archived_at=: (Time) -> Time

            attr_reader balance: Float?

            def balance=: (Float) -> Float

            attr_reader contract: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Contract?

            def contract=: (
              MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Contract
            ) -> MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Contract

            attr_reader custom_fields: ::Hash[Symbol, String]?

            def custom_fields=: (
              ::Hash[Symbol, String]
            ) -> ::Hash[Symbol, String]

            attr_reader description: String?

            def description=: (String) -> String

            attr_reader invoice_contract: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::InvoiceContract?

            def invoice_contract=: (
              MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::InvoiceContract
            ) -> MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::InvoiceContract

            attr_reader invoice_schedule: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::InvoiceSchedule?

            def invoice_schedule=: (
              MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::InvoiceSchedule
            ) -> MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::InvoiceSchedule

            attr_reader ledger: ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::ledger]?

            def ledger=: (
              ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::ledger]
            ) -> ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::ledger]

            attr_reader name: String?

            def name=: (String) -> String

            attr_reader netsuite_sales_order_id: String?

            def netsuite_sales_order_id=: (String) -> String

            attr_reader priority: Float?

            def priority=: (Float) -> Float

            attr_reader rate_type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::rate_type?

            def rate_type=: (
              MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::rate_type
            ) -> MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::rate_type

            attr_reader rolled_over_from: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::RolledOverFrom?

            def rolled_over_from=: (
              MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::RolledOverFrom
            ) -> MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::RolledOverFrom

            attr_reader rollover_fraction: Float?

            def rollover_fraction=: (Float) -> Float

            attr_reader salesforce_opportunity_id: String?

            def salesforce_opportunity_id=: (String) -> String

            attr_reader specifiers: ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Specifier]?

            def specifiers=: (
              ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Specifier]
            ) -> ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Specifier]

            attr_reader uniqueness_key: String?

            def uniqueness_key=: (String) -> String

            def initialize: (
              id: String,
              product: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Product,
              type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::type_,
              ?access_schedule: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::AccessSchedule,
              ?amount: Float,
              ?applicable_contract_ids: ::Array[String],
              ?applicable_product_ids: ::Array[String],
              ?applicable_product_tags: ::Array[String],
              ?archived_at: Time,
              ?balance: Float,
              ?contract: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Contract,
              ?custom_fields: ::Hash[Symbol, String],
              ?description: String,
              ?invoice_contract: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::InvoiceContract,
              ?invoice_schedule: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::InvoiceSchedule,
              ?ledger: ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::ledger],
              ?name: String,
              ?netsuite_sales_order_id: String,
              ?priority: Float,
              ?rate_type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::rate_type,
              ?rolled_over_from: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::RolledOverFrom,
              ?rollover_fraction: Float,
              ?salesforce_opportunity_id: String,
              ?specifiers: ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Specifier],
              ?uniqueness_key: String
            ) -> void

            def to_hash: -> {
              id: String,
              product: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Product,
              type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::type_,
              access_schedule: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::AccessSchedule,
              amount: Float,
              applicable_contract_ids: ::Array[String],
              applicable_product_ids: ::Array[String],
              applicable_product_tags: ::Array[String],
              archived_at: Time,
              balance: Float,
              contract: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Contract,
              custom_fields: ::Hash[Symbol, String],
              description: String,
              invoice_contract: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::InvoiceContract,
              invoice_schedule: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::InvoiceSchedule,
              ledger: ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::ledger],
              name: String,
              netsuite_sales_order_id: String,
              priority: Float,
              rate_type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::rate_type,
              rolled_over_from: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::RolledOverFrom,
              rollover_fraction: Float,
              salesforce_opportunity_id: String,
              specifiers: ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Specifier],
              uniqueness_key: String
            }

            type product = { id: String, name: String }

            class Product < MetronomeSDK::Internal::Type::BaseModel
              attr_accessor id: String

              attr_accessor name: String

              def initialize: (id: String, name: String) -> void

              def to_hash: -> { id: String, name: String }
            end

            type type_ = :PREPAID | :POSTPAID

            module Type
              extend MetronomeSDK::Internal::Type::Enum

              PREPAID: :PREPAID
              POSTPAID: :POSTPAID

              def self?.values: -> ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::type_]
            end

            type access_schedule =
              {
                schedule_items: ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::AccessSchedule::ScheduleItem],
                credit_type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::AccessSchedule::CreditType
              }

            class AccessSchedule < MetronomeSDK::Internal::Type::BaseModel
              attr_accessor schedule_items: ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::AccessSchedule::ScheduleItem]

              attr_reader credit_type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::AccessSchedule::CreditType?

              def credit_type=: (
                MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::AccessSchedule::CreditType
              ) -> MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::AccessSchedule::CreditType

              def initialize: (
                schedule_items: ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::AccessSchedule::ScheduleItem],
                ?credit_type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::AccessSchedule::CreditType
              ) -> void

              def to_hash: -> {
                schedule_items: ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::AccessSchedule::ScheduleItem],
                credit_type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::AccessSchedule::CreditType
              }

              type schedule_item =
                {
                  id: String,
                  amount: Float,
                  ending_before: Time,
                  starting_at: Time
                }

              class ScheduleItem < MetronomeSDK::Internal::Type::BaseModel
                attr_accessor id: String

                attr_accessor amount: Float

                attr_accessor ending_before: Time

                attr_accessor starting_at: Time

                def initialize: (
                  id: String,
                  amount: Float,
                  ending_before: Time,
                  starting_at: Time
                ) -> void

                def to_hash: -> {
                  id: String,
                  amount: Float,
                  ending_before: Time,
                  starting_at: Time
                }
              end

              type credit_type = { id: String, name: String }

              class CreditType < MetronomeSDK::Internal::Type::BaseModel
                attr_accessor id: String

                attr_accessor name: String

                def initialize: (id: String, name: String) -> void

                def to_hash: -> { id: String, name: String }
              end
            end

            type contract = { id: String }

            class Contract < MetronomeSDK::Internal::Type::BaseModel
              attr_accessor id: String

              def initialize: (id: String) -> void

              def to_hash: -> { id: String }
            end

            type invoice_contract = { id: String }

            class InvoiceContract < MetronomeSDK::Internal::Type::BaseModel
              attr_accessor id: String

              def initialize: (id: String) -> void

              def to_hash: -> { id: String }
            end

            type invoice_schedule =
              {
                credit_type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::InvoiceSchedule::CreditType,
                schedule_items: ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::InvoiceSchedule::ScheduleItem]
              }

            class InvoiceSchedule < MetronomeSDK::Internal::Type::BaseModel
              attr_reader credit_type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::InvoiceSchedule::CreditType?

              def credit_type=: (
                MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::InvoiceSchedule::CreditType
              ) -> MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::InvoiceSchedule::CreditType

              attr_reader schedule_items: ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::InvoiceSchedule::ScheduleItem]?

              def schedule_items=: (
                ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::InvoiceSchedule::ScheduleItem]
              ) -> ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::InvoiceSchedule::ScheduleItem]

              def initialize: (
                ?credit_type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::InvoiceSchedule::CreditType,
                ?schedule_items: ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::InvoiceSchedule::ScheduleItem]
              ) -> void

              def to_hash: -> {
                credit_type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::InvoiceSchedule::CreditType,
                schedule_items: ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::InvoiceSchedule::ScheduleItem]
              }

              type credit_type = { id: String, name: String }

              class CreditType < MetronomeSDK::Internal::Type::BaseModel
                attr_accessor id: String

                attr_accessor name: String

                def initialize: (id: String, name: String) -> void

                def to_hash: -> { id: String, name: String }
              end

              type schedule_item =
                {
                  id: String,
                  amount: Float,
                  invoice_id: String,
                  quantity: Float,
                  timestamp: Time,
                  unit_price: Float
                }

              class ScheduleItem < MetronomeSDK::Internal::Type::BaseModel
                attr_accessor id: String

                attr_accessor amount: Float

                attr_accessor invoice_id: String

                attr_accessor quantity: Float

                attr_accessor timestamp: Time

                attr_accessor unit_price: Float

                def initialize: (
                  id: String,
                  amount: Float,
                  invoice_id: String,
                  quantity: Float,
                  timestamp: Time,
                  unit_price: Float
                ) -> void

                def to_hash: -> {
                  id: String,
                  amount: Float,
                  invoice_id: String,
                  quantity: Float,
                  timestamp: Time,
                  unit_price: Float
                }
              end
            end

            type ledger =
              MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember0
              | MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember1
              | MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember2
              | MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember3
              | MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember4
              | MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember5
              | MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember6
              | MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember7
              | MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember8
              | MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember9
              | MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember10
              | MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember11
              | MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember12

            module Ledger
              extend MetronomeSDK::Internal::Type::Union

              type union_member0 =
                {
                  amount: Float,
                  segment_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember0::type_
                }

              class UnionMember0 < MetronomeSDK::Internal::Type::BaseModel
                attr_accessor amount: Float

                attr_accessor segment_id: String

                attr_accessor timestamp: Time

                attr_accessor type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember0::type_

                def initialize: (
                  amount: Float,
                  segment_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember0::type_
                ) -> void

                def to_hash: -> {
                  amount: Float,
                  segment_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember0::type_
                }

                type type_ = :PREPAID_COMMIT_SEGMENT_START

                module Type
                  extend MetronomeSDK::Internal::Type::Enum

                  PREPAID_COMMIT_SEGMENT_START: :PREPAID_COMMIT_SEGMENT_START

                  def self?.values: -> ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember0::type_]
                end
              end

              type union_member1 =
                {
                  amount: Float,
                  invoice_id: String,
                  segment_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember1::type_
                }

              class UnionMember1 < MetronomeSDK::Internal::Type::BaseModel
                attr_accessor amount: Float

                attr_accessor invoice_id: String

                attr_accessor segment_id: String

                attr_accessor timestamp: Time

                attr_accessor type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember1::type_

                def initialize: (
                  amount: Float,
                  invoice_id: String,
                  segment_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember1::type_
                ) -> void

                def to_hash: -> {
                  amount: Float,
                  invoice_id: String,
                  segment_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember1::type_
                }

                type type_ = :PREPAID_COMMIT_AUTOMATED_INVOICE_DEDUCTION

                module Type
                  extend MetronomeSDK::Internal::Type::Enum

                  PREPAID_COMMIT_AUTOMATED_INVOICE_DEDUCTION: :PREPAID_COMMIT_AUTOMATED_INVOICE_DEDUCTION

                  def self?.values: -> ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember1::type_]
                end
              end

              type union_member2 =
                {
                  amount: Float,
                  new_contract_id: String,
                  segment_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember2::type_
                }

              class UnionMember2 < MetronomeSDK::Internal::Type::BaseModel
                attr_accessor amount: Float

                attr_accessor new_contract_id: String

                attr_accessor segment_id: String

                attr_accessor timestamp: Time

                attr_accessor type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember2::type_

                def initialize: (
                  amount: Float,
                  new_contract_id: String,
                  segment_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember2::type_
                ) -> void

                def to_hash: -> {
                  amount: Float,
                  new_contract_id: String,
                  segment_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember2::type_
                }

                type type_ = :PREPAID_COMMIT_ROLLOVER

                module Type
                  extend MetronomeSDK::Internal::Type::Enum

                  PREPAID_COMMIT_ROLLOVER: :PREPAID_COMMIT_ROLLOVER

                  def self?.values: -> ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember2::type_]
                end
              end

              type union_member3 =
                {
                  amount: Float,
                  segment_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember3::type_
                }

              class UnionMember3 < MetronomeSDK::Internal::Type::BaseModel
                attr_accessor amount: Float

                attr_accessor segment_id: String

                attr_accessor timestamp: Time

                attr_accessor type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember3::type_

                def initialize: (
                  amount: Float,
                  segment_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember3::type_
                ) -> void

                def to_hash: -> {
                  amount: Float,
                  segment_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember3::type_
                }

                type type_ = :PREPAID_COMMIT_EXPIRATION

                module Type
                  extend MetronomeSDK::Internal::Type::Enum

                  PREPAID_COMMIT_EXPIRATION: :PREPAID_COMMIT_EXPIRATION

                  def self?.values: -> ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember3::type_]
                end
              end

              type union_member4 =
                {
                  amount: Float,
                  invoice_id: String,
                  segment_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember4::type_
                }

              class UnionMember4 < MetronomeSDK::Internal::Type::BaseModel
                attr_accessor amount: Float

                attr_accessor invoice_id: String

                attr_accessor segment_id: String

                attr_accessor timestamp: Time

                attr_accessor type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember4::type_

                def initialize: (
                  amount: Float,
                  invoice_id: String,
                  segment_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember4::type_
                ) -> void

                def to_hash: -> {
                  amount: Float,
                  invoice_id: String,
                  segment_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember4::type_
                }

                type type_ = :PREPAID_COMMIT_CANCELED

                module Type
                  extend MetronomeSDK::Internal::Type::Enum

                  PREPAID_COMMIT_CANCELED: :PREPAID_COMMIT_CANCELED

                  def self?.values: -> ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember4::type_]
                end
              end

              type union_member5 =
                {
                  amount: Float,
                  invoice_id: String,
                  segment_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember5::type_
                }

              class UnionMember5 < MetronomeSDK::Internal::Type::BaseModel
                attr_accessor amount: Float

                attr_accessor invoice_id: String

                attr_accessor segment_id: String

                attr_accessor timestamp: Time

                attr_accessor type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember5::type_

                def initialize: (
                  amount: Float,
                  invoice_id: String,
                  segment_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember5::type_
                ) -> void

                def to_hash: -> {
                  amount: Float,
                  invoice_id: String,
                  segment_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember5::type_
                }

                type type_ = :PREPAID_COMMIT_CREDITED

                module Type
                  extend MetronomeSDK::Internal::Type::Enum

                  PREPAID_COMMIT_CREDITED: :PREPAID_COMMIT_CREDITED

                  def self?.values: -> ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember5::type_]
                end
              end

              type union_member6 =
                {
                  amount: Float,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember6::type_
                }

              class UnionMember6 < MetronomeSDK::Internal::Type::BaseModel
                attr_accessor amount: Float

                attr_accessor timestamp: Time

                attr_accessor type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember6::type_

                def initialize: (
                  amount: Float,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember6::type_
                ) -> void

                def to_hash: -> {
                  amount: Float,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember6::type_
                }

                type type_ = :POSTPAID_COMMIT_INITIAL_BALANCE

                module Type
                  extend MetronomeSDK::Internal::Type::Enum

                  POSTPAID_COMMIT_INITIAL_BALANCE: :POSTPAID_COMMIT_INITIAL_BALANCE

                  def self?.values: -> ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember6::type_]
                end
              end

              type union_member7 =
                {
                  amount: Float,
                  invoice_id: String,
                  segment_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember7::type_
                }

              class UnionMember7 < MetronomeSDK::Internal::Type::BaseModel
                attr_accessor amount: Float

                attr_accessor invoice_id: String

                attr_accessor segment_id: String

                attr_accessor timestamp: Time

                attr_accessor type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember7::type_

                def initialize: (
                  amount: Float,
                  invoice_id: String,
                  segment_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember7::type_
                ) -> void

                def to_hash: -> {
                  amount: Float,
                  invoice_id: String,
                  segment_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember7::type_
                }

                type type_ = :POSTPAID_COMMIT_AUTOMATED_INVOICE_DEDUCTION

                module Type
                  extend MetronomeSDK::Internal::Type::Enum

                  POSTPAID_COMMIT_AUTOMATED_INVOICE_DEDUCTION: :POSTPAID_COMMIT_AUTOMATED_INVOICE_DEDUCTION

                  def self?.values: -> ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember7::type_]
                end
              end

              type union_member8 =
                {
                  amount: Float,
                  new_contract_id: String,
                  segment_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember8::type_
                }

              class UnionMember8 < MetronomeSDK::Internal::Type::BaseModel
                attr_accessor amount: Float

                attr_accessor new_contract_id: String

                attr_accessor segment_id: String

                attr_accessor timestamp: Time

                attr_accessor type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember8::type_

                def initialize: (
                  amount: Float,
                  new_contract_id: String,
                  segment_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember8::type_
                ) -> void

                def to_hash: -> {
                  amount: Float,
                  new_contract_id: String,
                  segment_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember8::type_
                }

                type type_ = :POSTPAID_COMMIT_ROLLOVER

                module Type
                  extend MetronomeSDK::Internal::Type::Enum

                  POSTPAID_COMMIT_ROLLOVER: :POSTPAID_COMMIT_ROLLOVER

                  def self?.values: -> ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember8::type_]
                end
              end

              type union_member9 =
                {
                  amount: Float,
                  invoice_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember9::type_
                }

              class UnionMember9 < MetronomeSDK::Internal::Type::BaseModel
                attr_accessor amount: Float

                attr_accessor invoice_id: String

                attr_accessor timestamp: Time

                attr_accessor type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember9::type_

                def initialize: (
                  amount: Float,
                  invoice_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember9::type_
                ) -> void

                def to_hash: -> {
                  amount: Float,
                  invoice_id: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember9::type_
                }

                type type_ = :POSTPAID_COMMIT_TRUEUP

                module Type
                  extend MetronomeSDK::Internal::Type::Enum

                  POSTPAID_COMMIT_TRUEUP: :POSTPAID_COMMIT_TRUEUP

                  def self?.values: -> ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember9::type_]
                end
              end

              type union_member10 =
                {
                  amount: Float,
                  reason: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember10::type_
                }

              class UnionMember10 < MetronomeSDK::Internal::Type::BaseModel
                attr_accessor amount: Float

                attr_accessor reason: String

                attr_accessor timestamp: Time

                attr_accessor type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember10::type_

                def initialize: (
                  amount: Float,
                  reason: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember10::type_
                ) -> void

                def to_hash: -> {
                  amount: Float,
                  reason: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember10::type_
                }

                type type_ = :PREPAID_COMMIT_MANUAL

                module Type
                  extend MetronomeSDK::Internal::Type::Enum

                  PREPAID_COMMIT_MANUAL: :PREPAID_COMMIT_MANUAL

                  def self?.values: -> ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember10::type_]
                end
              end

              type union_member11 =
                {
                  amount: Float,
                  reason: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember11::type_
                }

              class UnionMember11 < MetronomeSDK::Internal::Type::BaseModel
                attr_accessor amount: Float

                attr_accessor reason: String

                attr_accessor timestamp: Time

                attr_accessor type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember11::type_

                def initialize: (
                  amount: Float,
                  reason: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember11::type_
                ) -> void

                def to_hash: -> {
                  amount: Float,
                  reason: String,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember11::type_
                }

                type type_ = :POSTPAID_COMMIT_MANUAL

                module Type
                  extend MetronomeSDK::Internal::Type::Enum

                  POSTPAID_COMMIT_MANUAL: :POSTPAID_COMMIT_MANUAL

                  def self?.values: -> ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember11::type_]
                end
              end

              type union_member12 =
                {
                  amount: Float,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember12::type_
                }

              class UnionMember12 < MetronomeSDK::Internal::Type::BaseModel
                attr_accessor amount: Float

                attr_accessor timestamp: Time

                attr_accessor type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember12::type_

                def initialize: (
                  amount: Float,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember12::type_
                ) -> void

                def to_hash: -> {
                  amount: Float,
                  timestamp: Time,
                  type: MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember12::type_
                }

                type type_ = :POSTPAID_COMMIT_EXPIRATION

                module Type
                  extend MetronomeSDK::Internal::Type::Enum

                  POSTPAID_COMMIT_EXPIRATION: :POSTPAID_COMMIT_EXPIRATION

                  def self?.values: -> ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::Ledger::UnionMember12::type_]
                end
              end

              def self?.variants: -> ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::ledger]
            end

            type rate_type = :COMMIT_RATE | :LIST_RATE

            module RateType
              extend MetronomeSDK::Internal::Type::Enum

              COMMIT_RATE: :COMMIT_RATE
              LIST_RATE: :LIST_RATE

              def self?.values: -> ::Array[MetronomeSDK::Models::V1::Customers::CommitListResponse::Data::rate_type]
            end

            type rolled_over_from = { commit_id: String, contract_id: String }

            class RolledOverFrom < MetronomeSDK::Internal::Type::BaseModel
              attr_accessor commit_id: String

              attr_accessor contract_id: String

              def initialize: (commit_id: String, contract_id: String) -> void

              def to_hash: -> { commit_id: String, contract_id: String }
            end

            type specifier =
              {
                presentation_group_values: ::Hash[Symbol, String],
                pricing_group_values: ::Hash[Symbol, String],
                product_id: String,
                product_tags: ::Array[String]
              }

            class Specifier < MetronomeSDK::Internal::Type::BaseModel
              attr_reader presentation_group_values: ::Hash[Symbol, String]?

              def presentation_group_values=: (
                ::Hash[Symbol, String]
              ) -> ::Hash[Symbol, String]

              attr_reader pricing_group_values: ::Hash[Symbol, String]?

              def pricing_group_values=: (
                ::Hash[Symbol, String]
              ) -> ::Hash[Symbol, String]

              attr_reader product_id: String?

              def product_id=: (String) -> String

              attr_reader product_tags: ::Array[String]?

              def product_tags=: (::Array[String]) -> ::Array[String]

              def initialize: (
                ?presentation_group_values: ::Hash[Symbol, String],
                ?pricing_group_values: ::Hash[Symbol, String],
                ?product_id: String,
                ?product_tags: ::Array[String]
              ) -> void

              def to_hash: -> {
                presentation_group_values: ::Hash[Symbol, String],
                pricing_group_values: ::Hash[Symbol, String],
                product_id: String,
                product_tags: ::Array[String]
              }
            end
          end
        end
      end
    end
  end
end
