module MetronomeSDK
  module Models
    module V1
      module Customers
        type commit_list_response =
          { data: ::Array[MetronomeSDK::Models::Commit], next_page: String? }

        class CommitListResponse < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor data: ::Array[MetronomeSDK::Models::Commit]

          attr_accessor next_page: String?

          def initialize: (
            data: ::Array[MetronomeSDK::Models::Commit],
            next_page: String?
          ) -> void

          def to_hash: -> MetronomeSDK::Models::V1::Customers::commit_list_response
        end
      end
    end
  end
end
