module MetronomeSDK
  module Models
    module V1
      module Customers
        type credit_list_response =
          { data: ::Array[MetronomeSDK::Credit], next_page: String? }

        class CreditListResponse < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor data: ::Array[MetronomeSDK::Credit]

          attr_accessor next_page: String?

          def initialize: (
            data: ::Array[MetronomeSDK::Credit],
            next_page: String?
          ) -> void

          def to_hash: -> {
            data: ::Array[MetronomeSDK::Credit],
            next_page: String?
          }
        end
      end
    end
  end
end
