module MetronomeSDK
  module Models
    module V1
      module Customers
        type invoice_list_breakdowns_response =
          { breakdown_end_timestamp: Time, breakdown_start_timestamp: Time }

        class InvoiceListBreakdownsResponse < MetronomeSDK::Models::V1::Customers::Invoice
          def breakdown_end_timestamp: -> Time

          def breakdown_end_timestamp=: (Time _) -> Time

          def breakdown_start_timestamp: -> Time

          def breakdown_start_timestamp=: (Time _) -> Time

          def initialize: (
            breakdown_end_timestamp: Time,
            breakdown_start_timestamp: Time
          ) -> void

          def to_hash: -> MetronomeSDK::Models::V1::Customers::invoice_list_breakdowns_response
        end
      end
    end
  end
end
