module MetronomeSDK
  module Models
    module V1
      module Customers
        type invoice_retrieve_response =
          { data: MetronomeSDK::V1::Customers::Invoice }

        class InvoiceRetrieveResponse < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor data: MetronomeSDK::V1::Customers::Invoice

          def initialize: (data: MetronomeSDK::V1::Customers::Invoice) -> void
        end
      end
    end
  end
end
