module MetronomeSDK
  module Models
    module V1
      module Customers
        type plan_add_response =
          { data: MetronomeSDK::Models::V1::Customers::PlanAddResponse::Data }

        class PlanAddResponse < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor data: MetronomeSDK::Models::V1::Customers::PlanAddResponse::Data

          def initialize: (
            data: MetronomeSDK::Models::V1::Customers::PlanAddResponse::Data
          ) -> void

          def to_hash: -> {
            data: MetronomeSDK::Models::V1::Customers::PlanAddResponse::Data
          }

          type data = { id: String }

          class Data < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor id: String

            def initialize: (id: String) -> void

            def to_hash: -> { id: String }
          end
        end
      end
    end
  end
end
