module MetronomeSDK
  module Models
    module V1
      module Customers
        type plan_end_response = {  }

        class PlanEndResponse < MetronomeSDK::Internal::Type::BaseModel
          def initialize: -> void

          def to_hash: -> {  }
        end
      end
    end
  end
end
