module MetronomeSDK
  module Models
    module V1
      module Customers
        type plan_end_params =
          {
            customer_id: String,
            customer_plan_id: String,
            ending_before: Time,
            void_invoices: bool,
            void_stripe_invoices: bool
          }
          & MetronomeSDK::Internal::Type::request_parameters

        class PlanEndParams < MetronomeSDK::Internal::Type::BaseModel
          extend MetronomeSDK::Internal::Type::RequestParameters::Converter
          include MetronomeSDK::Internal::Type::RequestParameters

          attr_accessor customer_id: String

          attr_accessor customer_plan_id: String

          attr_reader ending_before: Time?

          def ending_before=: (Time) -> Time

          attr_reader void_invoices: bool?

          def void_invoices=: (bool) -> bool

          attr_reader void_stripe_invoices: bool?

          def void_stripe_invoices=: (bool) -> bool

          def initialize: (
            customer_id: String,
            customer_plan_id: String,
            ?ending_before: Time,
            ?void_invoices: bool,
            ?void_stripe_invoices: bool,
            ?request_options: MetronomeSDK::request_opts
          ) -> void

          def to_hash: -> MetronomeSDK::Models::V1::Customers::plan_end_params
        end
      end
    end
  end
end
