module Metronome
  module Models
    module Customers
      type alert_list_response =
        {
          data: Array[Metronome::Models::Customers::CustomerAlert],
          next_page: String?
        }

      class AlertListResponse < Metronome::BaseModel
        attr_accessor data: Array[Metronome::Models::Customers::CustomerAlert]

        attr_accessor next_page: String?

        def initialize:
          (
            data: Array[Metronome::Models::Customers::CustomerAlert],
            next_page: String?
          ) -> void
          | (
            ?Metronome::Models::Customers::alert_list_response
            | Metronome::BaseModel data
          ) -> void

        def to_h: -> Metronome::Models::Customers::alert_list_response
      end
    end
  end
end
