module Metronome
  module Models
    module Customers
      type commit_update_end_date_params =
        {
          commit_id: String,
          customer_id: String,
          access_ending_before: Time,
          invoices_ending_before: Time
        }
        & Metronome::request_parameters

      class CommitUpdateEndDateParams < Metronome::BaseModel
        extend Metronome::RequestParameters::Converter
        include Metronome::RequestParameters

        attr_accessor commit_id: String

        attr_accessor customer_id: String

        attr_reader access_ending_before: Time?

        def access_ending_before=: (Time) -> Time

        attr_reader invoices_ending_before: Time?

        def invoices_ending_before=: (Time) -> Time

        def initialize:
          (
            commit_id: String,
            customer_id: String,
            access_ending_before: Time,
            invoices_ending_before: Time,
            request_options: Metronome::request_opts
          ) -> void
          | (
            ?Metronome::Models::Customers::commit_update_end_date_params
            | Metronome::BaseModel data
          ) -> void

        def to_hash: -> Metronome::Models::Customers::commit_update_end_date_params
      end
    end
  end
end
