module Metronome
  module Models
    module Customers
      type commit_create_response = { data: Metronome::Models::ID }

      class CommitCreateResponse < Metronome::BaseModel
        attr_accessor data: Metronome::Models::ID

        def initialize:
          (data: Metronome::Models::ID) -> void
          | (
            ?Metronome::Models::Customers::commit_create_response
            | Metronome::BaseModel data
          ) -> void

        def to_hash: -> Metronome::Models::Customers::commit_create_response
      end
    end
  end
end
