module Metronome
  module Models
    module Customers
      type commit_list_response =
        { data: Array[Metronome::Models::Commit], next_page: String? }

      class CommitListResponse < Metronome::BaseModel
        attr_accessor data: Array[Metronome::Models::Commit]

        attr_accessor next_page: String?

        def initialize:
          (data: Array[Metronome::Models::Commit], next_page: String?) -> void
          | (
            ?Metronome::Models::Customers::commit_list_response
            | Metronome::BaseModel data
          ) -> void

        def to_h: -> Metronome::Models::Customers::commit_list_response
      end
    end
  end
end
