module Metronome
  module Models
    module Customers
      type credit_list_response =
        { data: Array[Metronome::Models::Credit], next_page: String? }

      class CreditListResponse < Metronome::BaseModel
        attr_accessor data: Array[Metronome::Models::Credit]

        attr_accessor next_page: String?

        def initialize:
          (data: Array[Metronome::Models::Credit], next_page: String?) -> void
          | (
            ?Metronome::Models::Customers::credit_list_response
            | Metronome::BaseModel data
          ) -> void

        def to_hash: -> Metronome::Models::Customers::credit_list_response
      end
    end
  end
end
