module Metronome
  module Models
    module Customers
      type invoice_add_charge_response = {  }

      class InvoiceAddChargeResponse < Metronome::BaseModel
        def initialize:
          -> void
          | (
            ?Metronome::Models::Customers::invoice_add_charge_response
            | Metronome::BaseModel data
          ) -> void

        def to_h: -> Metronome::Models::Customers::invoice_add_charge_response
      end
    end
  end
end
