module Metronome
  module Models
    module Customers
      type named_schedule_update_params =
        {
          customer_id: String,
          schedule_name: String,
          starting_at: Time,
          value: top,
          ending_before: Time
        }
        & Metronome::request_parameters

      class NamedScheduleUpdateParams < Metronome::BaseModel
        extend Metronome::RequestParameters::Converter
        include Metronome::RequestParameters

        attr_accessor customer_id: String

        attr_accessor schedule_name: String

        attr_accessor starting_at: Time

        attr_accessor value: top

        attr_reader ending_before: Time?

        def ending_before=: (Time) -> void

        def initialize:
          (
            customer_id: String,
            schedule_name: String,
            starting_at: Time,
            value: top,
            ending_before: Time,
            request_options: Metronome::request_opts
          ) -> void
          | (
            ?Metronome::Models::Customers::named_schedule_update_params
            | Metronome::BaseModel data
          ) -> void

        def to_h: -> Metronome::Models::Customers::named_schedule_update_params
      end
    end
  end
end
