module Metronome
  module Models
    module Customers
      type named_schedule_retrieve_params =
        { customer_id: String, schedule_name: String, covering_date: Time }
        & Metronome::request_parameters

      class NamedScheduleRetrieveParams < Metronome::BaseModel
        extend Metronome::RequestParameters::Converter
        include Metronome::RequestParameters

        attr_accessor customer_id: String

        attr_accessor schedule_name: String

        attr_reader covering_date: Time?

        def covering_date=: (Time) -> Time

        def initialize:
          (
            customer_id: String,
            schedule_name: String,
            covering_date: Time,
            request_options: Metronome::request_opts
          ) -> void
          | (
            ?Metronome::Models::Customers::named_schedule_retrieve_params
            | Metronome::BaseModel data
          ) -> void

        def to_hash: -> Metronome::Models::Customers::named_schedule_retrieve_params
      end
    end
  end
end
