module Metronome
  module Models
    module Customers
      type plan_end_response = {  }

      class PlanEndResponse < Metronome::BaseModel
        def initialize:
          -> void
          | (
            ?Metronome::Models::Customers::plan_end_response
            | Metronome::BaseModel data
          ) -> void

        def to_hash: -> Metronome::Models::Customers::plan_end_response
      end
    end
  end
end
