module MetronomeSDK
  module Models
    module V2
      type contract_get_edit_history_params =
        { contract_id: String, customer_id: String }
        & MetronomeSDK::request_parameters

      class ContractGetEditHistoryParams < MetronomeSDK::BaseModel
        extend MetronomeSDK::RequestParameters::Converter
        include MetronomeSDK::RequestParameters

        attr_accessor contract_id: String

        attr_accessor customer_id: String

        def initialize:
          (
            contract_id: String,
            customer_id: String,
            request_options: MetronomeSDK::request_opts
          ) -> void
          | (
            ?MetronomeSDK::Models::V2::contract_get_edit_history_params
            | MetronomeSDK::BaseModel data
          ) -> void

        def to_hash: -> MetronomeSDK::Models::V2::contract_get_edit_history_params
      end
    end
  end
end
