module MetronomeSDK
  module Models
    module V2
      type contract_edit_commit_response = { data: MetronomeSDK::Models::ID }

      class ContractEditCommitResponse < MetronomeSDK::BaseModel
        attr_accessor data: MetronomeSDK::Models::ID

        def initialize:
          (data: MetronomeSDK::Models::ID) -> void
          | (
            ?MetronomeSDK::Models::V2::contract_edit_commit_response
            | MetronomeSDK::BaseModel data
          ) -> void

        def to_hash: -> MetronomeSDK::Models::V2::contract_edit_commit_response
      end
    end
  end
end
