module MetronomeSDK
  module Models
    module V1
      type alert_archive_params =
        { id: String, release_uniqueness_key: bool }
        & MetronomeSDK::Internal::Type::request_parameters

      class AlertArchiveParams < MetronomeSDK::Internal::Type::BaseModel
        extend MetronomeSDK::Internal::Type::RequestParameters::Converter
        include MetronomeSDK::Internal::Type::RequestParameters

        attr_accessor id: String

        attr_reader release_uniqueness_key: bool?

        def release_uniqueness_key=: (bool) -> bool

        def initialize: (
          id: String,
          ?release_uniqueness_key: bool,
          ?request_options: MetronomeSDK::request_opts
        ) -> void
      end
    end
  end
end
