module MetronomeSDK
  module Models
    module V1
      type alert_create_response =
        { data: MetronomeSDK::Models::V1::AlertCreateResponse::Data }

      class AlertCreateResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor data: MetronomeSDK::Models::V1::AlertCreateResponse::Data

        def initialize: (
          data: MetronomeSDK::Models::V1::AlertCreateResponse::Data
        ) -> void

        def to_hash: -> {
          data: MetronomeSDK::Models::V1::AlertCreateResponse::Data
        }

        type data = { id: String }

        class Data < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor id: String

          def initialize: (id: String) -> void

          def to_hash: -> { id: String }
        end
      end
    end
  end
end
