module MetronomeSDK
  module Models
    module V1
      type alert_archive_response = { data: MetronomeSDK::Models::ID }

      class AlertArchiveResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor data: MetronomeSDK::Models::ID

        def initialize: (data: MetronomeSDK::Models::ID) -> void

        def to_hash: -> MetronomeSDK::Models::V1::alert_archive_response
      end
    end
  end
end
