module MetronomeSDK
  module Models
    module V1
      type billable_metric_update_params =
        { billable_metric_id: String, name: String }
        & MetronomeSDK::Internal::Type::request_parameters

      class BillableMetricUpdateParams < MetronomeSDK::Internal::Type::BaseModel
        extend MetronomeSDK::Internal::Type::RequestParameters::Converter
        include MetronomeSDK::Internal::Type::RequestParameters

        attr_accessor billable_metric_id: String

        attr_accessor name: String

        def initialize: (
          billable_metric_id: String,
          name: String,
          ?request_options: MetronomeSDK::request_opts
        ) -> void

        def to_hash: -> {
          billable_metric_id: String,
          name: String,
          request_options: MetronomeSDK::RequestOptions
        }
      end
    end
  end
end
