module MetronomeSDK
  module Models
    module V1
      type billable_metric_list_params =
        { include_archived: bool, limit: Integer, next_page: String }
        & MetronomeSDK::Internal::Type::request_parameters

      class BillableMetricListParams < MetronomeSDK::Internal::Type::BaseModel
        extend MetronomeSDK::Internal::Type::RequestParameters::Converter
        include MetronomeSDK::Internal::Type::RequestParameters

        attr_reader include_archived: bool?

        def include_archived=: (bool) -> bool

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader next_page: String?

        def next_page=: (String) -> String

        def initialize: (
          ?include_archived: bool,
          ?limit: Integer,
          ?next_page: String,
          ?request_options: MetronomeSDK::request_opts
        ) -> void

        def to_hash: -> {
          include_archived: bool,
          limit: Integer,
          next_page: String,
          request_options: MetronomeSDK::RequestOptions
        }
      end
    end
  end
end
