module MetronomeSDK
  module Models
    module V1
      type billable_metric_create_response = { data: MetronomeSDK::ID }

      class BillableMetricCreateResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor data: MetronomeSDK::ID

        def initialize: (data: MetronomeSDK::ID) -> void
      end
    end
  end
end
