module MetronomeSDK
  module Models
    module V1
      type billable_metric_create_response =
        { data: MetronomeSDK::Models::V1::BillableMetricCreateResponse::Data }

      class BillableMetricCreateResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor data: MetronomeSDK::Models::V1::BillableMetricCreateResponse::Data

        def initialize: (
          data: MetronomeSDK::Models::V1::BillableMetricCreateResponse::Data
        ) -> void

        type data = { id: String }

        class Data < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor id: String

          def initialize: (id: String) -> void
        end
      end
    end
  end
end
