module MetronomeSDK
  module Models
    module V1
      type contract_schedule_pro_services_invoice_response =
        { data: ::Array[MetronomeSDK::V1::Customers::Invoice] }

      class ContractScheduleProServicesInvoiceResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor data: ::Array[MetronomeSDK::V1::Customers::Invoice]

        def initialize: (
          data: ::Array[MetronomeSDK::V1::Customers::Invoice]
        ) -> void

        def to_hash: -> { data: ::Array[MetronomeSDK::V1::Customers::Invoice] }
      end
    end
  end
end
