module MetronomeSDK
  module Models
    module V1
      type contract_add_manual_balance_entry_params =
        {
          id: String,
          amount: Float,
          customer_id: String,
          reason: String,
          segment_id: String,
          contract_id: String,
          per_group_amounts: ::Hash[Symbol, Float],
          timestamp: Time
        }
        & MetronomeSDK::Internal::Type::request_parameters

      class ContractAddManualBalanceEntryParams < MetronomeSDK::Internal::Type::BaseModel
        extend MetronomeSDK::Internal::Type::RequestParameters::Converter
        include MetronomeSDK::Internal::Type::RequestParameters

        attr_accessor id: String

        attr_accessor amount: Float

        attr_accessor customer_id: String

        attr_accessor reason: String

        attr_accessor segment_id: String

        attr_reader contract_id: String?

        def contract_id=: (String) -> String

        attr_reader per_group_amounts: ::Hash[Symbol, Float]?

        def per_group_amounts=: (::Hash[Symbol, Float]) -> ::Hash[Symbol, Float]

        attr_reader timestamp: Time?

        def timestamp=: (Time) -> Time

        def initialize: (
          id: String,
          amount: Float,
          customer_id: String,
          reason: String,
          segment_id: String,
          ?contract_id: String,
          ?per_group_amounts: ::Hash[Symbol, Float],
          ?timestamp: Time,
          ?request_options: MetronomeSDK::request_opts
        ) -> void

        def to_hash: -> {
          id: String,
          amount: Float,
          customer_id: String,
          reason: String,
          segment_id: String,
          contract_id: String,
          per_group_amounts: ::Hash[Symbol, Float],
          timestamp: Time,
          request_options: MetronomeSDK::RequestOptions
        }
      end
    end
  end
end
