module MetronomeSDK
  module Models
    module V1
      type contract_get_subscription_quantity_history_params =
        { contract_id: String, customer_id: String, subscription_id: String }
        & MetronomeSDK::Internal::Type::request_parameters

      class ContractGetSubscriptionQuantityHistoryParams < MetronomeSDK::Internal::Type::BaseModel
        extend MetronomeSDK::Internal::Type::RequestParameters::Converter
        include MetronomeSDK::Internal::Type::RequestParameters

        attr_accessor contract_id: String

        attr_accessor customer_id: String

        attr_accessor subscription_id: String

        def initialize: (
          contract_id: String,
          customer_id: String,
          subscription_id: String,
          ?request_options: MetronomeSDK::request_opts
        ) -> void

        def to_hash: -> {
          contract_id: String,
          customer_id: String,
          subscription_id: String,
          request_options: MetronomeSDK::RequestOptions
        }
      end
    end
  end
end
