module MetronomeSDK
  module Models
    module V1
      type contract_list_response =
        { data: ::Array[MetronomeSDK::Models::V1::ContractListResponse::Data] }

      class ContractListResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor data: ::Array[MetronomeSDK::Models::V1::ContractListResponse::Data]

        def initialize: (
          data: ::Array[MetronomeSDK::Models::V1::ContractListResponse::Data]
        ) -> void

        type data =
          {
            id: String,
            amendments: ::Array[MetronomeSDK::Models::V1::ContractListResponse::Data::Amendment],
            current: MetronomeSDK::ContractWithoutAmendments,
            customer_id: String,
            initial: MetronomeSDK::ContractWithoutAmendments,
            archived_at: Time,
            custom_fields: ::Hash[Symbol, String],
            customer_billing_provider_configuration: MetronomeSDK::Models::V1::ContractListResponse::Data::CustomerBillingProviderConfiguration,
            prepaid_balance_threshold_configuration: MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration,
            scheduled_charges_on_usage_invoices: MetronomeSDK::Models::V1::ContractListResponse::Data::scheduled_charges_on_usage_invoices,
            spend_threshold_configuration: MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration,
            uniqueness_key: String
          }

        class Data < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor amendments: ::Array[MetronomeSDK::Models::V1::ContractListResponse::Data::Amendment]

          attr_accessor current: MetronomeSDK::ContractWithoutAmendments

          attr_accessor customer_id: String

          attr_accessor initial: MetronomeSDK::ContractWithoutAmendments

          attr_reader archived_at: Time?

          def archived_at=: (Time) -> Time

          attr_reader custom_fields: ::Hash[Symbol, String]?

          def custom_fields=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

          attr_reader customer_billing_provider_configuration: MetronomeSDK::Models::V1::ContractListResponse::Data::CustomerBillingProviderConfiguration?

          def customer_billing_provider_configuration=: (
            MetronomeSDK::Models::V1::ContractListResponse::Data::CustomerBillingProviderConfiguration
          ) -> MetronomeSDK::Models::V1::ContractListResponse::Data::CustomerBillingProviderConfiguration

          attr_reader prepaid_balance_threshold_configuration: MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration?

          def prepaid_balance_threshold_configuration=: (
            MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration
          ) -> MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration

          attr_reader scheduled_charges_on_usage_invoices: MetronomeSDK::Models::V1::ContractListResponse::Data::scheduled_charges_on_usage_invoices?

          def scheduled_charges_on_usage_invoices=: (
            MetronomeSDK::Models::V1::ContractListResponse::Data::scheduled_charges_on_usage_invoices
          ) -> MetronomeSDK::Models::V1::ContractListResponse::Data::scheduled_charges_on_usage_invoices

          attr_reader spend_threshold_configuration: MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration?

          def spend_threshold_configuration=: (
            MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration
          ) -> MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration

          attr_reader uniqueness_key: String?

          def uniqueness_key=: (String) -> String

          def initialize: (
            id: String,
            amendments: ::Array[MetronomeSDK::Models::V1::ContractListResponse::Data::Amendment],
            current: MetronomeSDK::ContractWithoutAmendments,
            customer_id: String,
            initial: MetronomeSDK::ContractWithoutAmendments,
            ?archived_at: Time,
            ?custom_fields: ::Hash[Symbol, String],
            ?customer_billing_provider_configuration: MetronomeSDK::Models::V1::ContractListResponse::Data::CustomerBillingProviderConfiguration,
            ?prepaid_balance_threshold_configuration: MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration,
            ?scheduled_charges_on_usage_invoices: MetronomeSDK::Models::V1::ContractListResponse::Data::scheduled_charges_on_usage_invoices,
            ?spend_threshold_configuration: MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration,
            ?uniqueness_key: String
          ) -> void

          type amendment =
            {
              id: String,
              commits: ::Array[MetronomeSDK::Commit],
              created_at: Time,
              created_by: String,
              overrides: ::Array[MetronomeSDK::Override],
              scheduled_charges: ::Array[MetronomeSDK::ScheduledCharge],
              starting_at: Time,
              credits: ::Array[MetronomeSDK::Credit],
              discounts: ::Array[MetronomeSDK::Discount],
              netsuite_sales_order_id: String,
              professional_services: ::Array[MetronomeSDK::ProService],
              reseller_royalties: ::Array[MetronomeSDK::Models::V1::ContractListResponse::Data::Amendment::ResellerRoyalty],
              salesforce_opportunity_id: String
            }

          class Amendment < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor commits: ::Array[MetronomeSDK::Commit]

            attr_accessor created_at: Time

            attr_accessor created_by: String

            attr_accessor overrides: ::Array[MetronomeSDK::Override]

            attr_accessor scheduled_charges: ::Array[MetronomeSDK::ScheduledCharge]

            attr_accessor starting_at: Time

            attr_reader credits: ::Array[MetronomeSDK::Credit]?

            def credits=: (
              ::Array[MetronomeSDK::Credit]
            ) -> ::Array[MetronomeSDK::Credit]

            attr_reader discounts: ::Array[MetronomeSDK::Discount]?

            def discounts=: (
              ::Array[MetronomeSDK::Discount]
            ) -> ::Array[MetronomeSDK::Discount]

            attr_reader netsuite_sales_order_id: String?

            def netsuite_sales_order_id=: (String) -> String

            attr_reader professional_services: ::Array[MetronomeSDK::ProService]?

            def professional_services=: (
              ::Array[MetronomeSDK::ProService]
            ) -> ::Array[MetronomeSDK::ProService]

            attr_reader reseller_royalties: ::Array[MetronomeSDK::Models::V1::ContractListResponse::Data::Amendment::ResellerRoyalty]?

            def reseller_royalties=: (
              ::Array[MetronomeSDK::Models::V1::ContractListResponse::Data::Amendment::ResellerRoyalty]
            ) -> ::Array[MetronomeSDK::Models::V1::ContractListResponse::Data::Amendment::ResellerRoyalty]

            attr_reader salesforce_opportunity_id: String?

            def salesforce_opportunity_id=: (String) -> String

            def initialize: (
              id: String,
              commits: ::Array[MetronomeSDK::Commit],
              created_at: Time,
              created_by: String,
              overrides: ::Array[MetronomeSDK::Override],
              scheduled_charges: ::Array[MetronomeSDK::ScheduledCharge],
              starting_at: Time,
              ?credits: ::Array[MetronomeSDK::Credit],
              ?discounts: ::Array[MetronomeSDK::Discount],
              ?netsuite_sales_order_id: String,
              ?professional_services: ::Array[MetronomeSDK::ProService],
              ?reseller_royalties: ::Array[MetronomeSDK::Models::V1::ContractListResponse::Data::Amendment::ResellerRoyalty],
              ?salesforce_opportunity_id: String
            ) -> void

            type reseller_royalty =
              {
                reseller_type: MetronomeSDK::Models::V1::ContractListResponse::Data::Amendment::ResellerRoyalty::reseller_type,
                aws_account_number: String,
                aws_offer_id: String,
                aws_payer_reference_id: String,
                ending_before: Time?,
                fraction: Float,
                gcp_account_id: String,
                gcp_offer_id: String,
                netsuite_reseller_id: String,
                reseller_contract_value: Float,
                starting_at: Time
              }

            class ResellerRoyalty < MetronomeSDK::Internal::Type::BaseModel
              attr_accessor reseller_type: MetronomeSDK::Models::V1::ContractListResponse::Data::Amendment::ResellerRoyalty::reseller_type

              attr_reader aws_account_number: String?

              def aws_account_number=: (String) -> String

              attr_reader aws_offer_id: String?

              def aws_offer_id=: (String) -> String

              attr_reader aws_payer_reference_id: String?

              def aws_payer_reference_id=: (String) -> String

              attr_accessor ending_before: Time?

              attr_reader fraction: Float?

              def fraction=: (Float) -> Float

              attr_reader gcp_account_id: String?

              def gcp_account_id=: (String) -> String

              attr_reader gcp_offer_id: String?

              def gcp_offer_id=: (String) -> String

              attr_reader netsuite_reseller_id: String?

              def netsuite_reseller_id=: (String) -> String

              attr_reader reseller_contract_value: Float?

              def reseller_contract_value=: (Float) -> Float

              attr_reader starting_at: Time?

              def starting_at=: (Time) -> Time

              def initialize: (
                reseller_type: MetronomeSDK::Models::V1::ContractListResponse::Data::Amendment::ResellerRoyalty::reseller_type,
                ?aws_account_number: String,
                ?aws_offer_id: String,
                ?aws_payer_reference_id: String,
                ?ending_before: Time?,
                ?fraction: Float,
                ?gcp_account_id: String,
                ?gcp_offer_id: String,
                ?netsuite_reseller_id: String,
                ?reseller_contract_value: Float,
                ?starting_at: Time
              ) -> void

              type reseller_type =
                :AWS | :AWS_PRO_SERVICE | :GCP | :GCP_PRO_SERVICE

              module ResellerType
                extend MetronomeSDK::Internal::Type::Enum

                AWS: :AWS
                AWS_PRO_SERVICE: :AWS_PRO_SERVICE
                GCP: :GCP
                GCP_PRO_SERVICE: :GCP_PRO_SERVICE

                def self?.values: -> ::Array[MetronomeSDK::Models::V1::ContractListResponse::Data::Amendment::ResellerRoyalty::reseller_type]
              end
            end
          end

          type customer_billing_provider_configuration =
            {
              billing_provider: MetronomeSDK::Models::V1::ContractListResponse::Data::CustomerBillingProviderConfiguration::billing_provider,
              delivery_method: MetronomeSDK::Models::V1::ContractListResponse::Data::CustomerBillingProviderConfiguration::delivery_method,
              id: String,
              configuration: ::Hash[Symbol, top]
            }

          class CustomerBillingProviderConfiguration < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor billing_provider: MetronomeSDK::Models::V1::ContractListResponse::Data::CustomerBillingProviderConfiguration::billing_provider

            attr_accessor delivery_method: MetronomeSDK::Models::V1::ContractListResponse::Data::CustomerBillingProviderConfiguration::delivery_method

            attr_reader id: String?

            def id=: (String) -> String

            attr_reader configuration: ::Hash[Symbol, top]?

            def configuration=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

            def initialize: (
              billing_provider: MetronomeSDK::Models::V1::ContractListResponse::Data::CustomerBillingProviderConfiguration::billing_provider,
              delivery_method: MetronomeSDK::Models::V1::ContractListResponse::Data::CustomerBillingProviderConfiguration::delivery_method,
              ?id: String,
              ?configuration: ::Hash[Symbol, top]
            ) -> void

            type billing_provider =
              :aws_marketplace
              | :stripe
              | :netsuite
              | :custom
              | :azure_marketplace
              | :quickbooks_online
              | :workday
              | :gcp_marketplace

            module BillingProvider
              extend MetronomeSDK::Internal::Type::Enum

              AWS_MARKETPLACE: :aws_marketplace
              STRIPE: :stripe
              NETSUITE: :netsuite
              CUSTOM: :custom
              AZURE_MARKETPLACE: :azure_marketplace
              QUICKBOOKS_ONLINE: :quickbooks_online
              WORKDAY: :workday
              GCP_MARKETPLACE: :gcp_marketplace

              def self?.values: -> ::Array[MetronomeSDK::Models::V1::ContractListResponse::Data::CustomerBillingProviderConfiguration::billing_provider]
            end

            type delivery_method =
              :direct_to_billing_provider | :aws_sqs | :tackle | :aws_sns

            module DeliveryMethod
              extend MetronomeSDK::Internal::Type::Enum

              DIRECT_TO_BILLING_PROVIDER: :direct_to_billing_provider
              AWS_SQS: :aws_sqs
              TACKLE: :tackle
              AWS_SNS: :aws_sns

              def self?.values: -> ::Array[MetronomeSDK::Models::V1::ContractListResponse::Data::CustomerBillingProviderConfiguration::delivery_method]
            end
          end

          type prepaid_balance_threshold_configuration =
            {
              commit: MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration::Commit,
              is_enabled: bool,
              payment_gate_config: MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration::PaymentGateConfig,
              recharge_to_amount: Float,
              threshold_amount: Float
            }

          class PrepaidBalanceThresholdConfiguration < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor commit: MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration::Commit

            attr_accessor is_enabled: bool

            attr_accessor payment_gate_config: MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration::PaymentGateConfig

            attr_accessor recharge_to_amount: Float

            attr_accessor threshold_amount: Float

            def initialize: (
              commit: MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration::Commit,
              is_enabled: bool,
              payment_gate_config: MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration::PaymentGateConfig,
              recharge_to_amount: Float,
              threshold_amount: Float
            ) -> void

            type commit =
              {
                product_id: String,
                applicable_product_ids: ::Array[String],
                applicable_product_tags: ::Array[String],
                description: String,
                name: String
              }

            class Commit < MetronomeSDK::Internal::Type::BaseModel
              attr_accessor product_id: String

              attr_reader applicable_product_ids: ::Array[String]?

              def applicable_product_ids=: (::Array[String]) -> ::Array[String]

              attr_reader applicable_product_tags: ::Array[String]?

              def applicable_product_tags=: (::Array[String]) -> ::Array[String]

              attr_reader description: String?

              def description=: (String) -> String

              attr_reader name: String?

              def name=: (String) -> String

              def initialize: (
                product_id: String,
                ?applicable_product_ids: ::Array[String],
                ?applicable_product_tags: ::Array[String],
                ?description: String,
                ?name: String
              ) -> void
            end

            type payment_gate_config =
              {
                payment_gate_type: MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration::PaymentGateConfig::payment_gate_type,
                stripe_config: MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration::PaymentGateConfig::StripeConfig,
                tax_type: MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration::PaymentGateConfig::tax_type
              }

            class PaymentGateConfig < MetronomeSDK::Internal::Type::BaseModel
              attr_accessor payment_gate_type: MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration::PaymentGateConfig::payment_gate_type

              attr_reader stripe_config: MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration::PaymentGateConfig::StripeConfig?

              def stripe_config=: (
                MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration::PaymentGateConfig::StripeConfig
              ) -> MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration::PaymentGateConfig::StripeConfig

              attr_reader tax_type: MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration::PaymentGateConfig::tax_type?

              def tax_type=: (
                MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration::PaymentGateConfig::tax_type
              ) -> MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration::PaymentGateConfig::tax_type

              def initialize: (
                payment_gate_type: MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration::PaymentGateConfig::payment_gate_type,
                ?stripe_config: MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration::PaymentGateConfig::StripeConfig,
                ?tax_type: MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration::PaymentGateConfig::tax_type
              ) -> void

              type payment_gate_type = :NONE | :STRIPE | :EXTERNAL

              module PaymentGateType
                extend MetronomeSDK::Internal::Type::Enum

                NONE: :NONE
                STRIPE: :STRIPE
                EXTERNAL: :EXTERNAL

                def self?.values: -> ::Array[MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration::PaymentGateConfig::payment_gate_type]
              end

              type stripe_config =
                {
                  payment_type: MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration::PaymentGateConfig::StripeConfig::payment_type
                }

              class StripeConfig < MetronomeSDK::Internal::Type::BaseModel
                attr_accessor payment_type: MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration::PaymentGateConfig::StripeConfig::payment_type

                def initialize: (
                  payment_type: MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration::PaymentGateConfig::StripeConfig::payment_type
                ) -> void

                type payment_type = :INVOICE | :PAYMENT_INTENT

                module PaymentType
                  extend MetronomeSDK::Internal::Type::Enum

                  INVOICE: :INVOICE
                  PAYMENT_INTENT: :PAYMENT_INTENT

                  def self?.values: -> ::Array[MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration::PaymentGateConfig::StripeConfig::payment_type]
                end
              end

              type tax_type = :NONE | :STRIPE

              module TaxType
                extend MetronomeSDK::Internal::Type::Enum

                NONE: :NONE
                STRIPE: :STRIPE

                def self?.values: -> ::Array[MetronomeSDK::Models::V1::ContractListResponse::Data::PrepaidBalanceThresholdConfiguration::PaymentGateConfig::tax_type]
              end
            end
          end

          type scheduled_charges_on_usage_invoices = :ALL

          module ScheduledChargesOnUsageInvoices
            extend MetronomeSDK::Internal::Type::Enum

            ALL: :ALL

            def self?.values: -> ::Array[MetronomeSDK::Models::V1::ContractListResponse::Data::scheduled_charges_on_usage_invoices]
          end

          type spend_threshold_configuration =
            {
              commit: MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration::Commit,
              is_enabled: bool,
              payment_gate_config: MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration::PaymentGateConfig,
              threshold_amount: Float
            }

          class SpendThresholdConfiguration < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor commit: MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration::Commit

            attr_accessor is_enabled: bool

            attr_accessor payment_gate_config: MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration::PaymentGateConfig

            attr_accessor threshold_amount: Float

            def initialize: (
              commit: MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration::Commit,
              is_enabled: bool,
              payment_gate_config: MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration::PaymentGateConfig,
              threshold_amount: Float
            ) -> void

            type commit =
              { product_id: String, description: String, name: String }

            class Commit < MetronomeSDK::Internal::Type::BaseModel
              attr_accessor product_id: String

              attr_reader description: String?

              def description=: (String) -> String

              attr_reader name: String?

              def name=: (String) -> String

              def initialize: (
                product_id: String,
                ?description: String,
                ?name: String
              ) -> void
            end

            type payment_gate_config =
              {
                payment_gate_type: MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration::PaymentGateConfig::payment_gate_type,
                stripe_config: MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration::PaymentGateConfig::StripeConfig,
                tax_type: MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration::PaymentGateConfig::tax_type
              }

            class PaymentGateConfig < MetronomeSDK::Internal::Type::BaseModel
              attr_accessor payment_gate_type: MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration::PaymentGateConfig::payment_gate_type

              attr_reader stripe_config: MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration::PaymentGateConfig::StripeConfig?

              def stripe_config=: (
                MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration::PaymentGateConfig::StripeConfig
              ) -> MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration::PaymentGateConfig::StripeConfig

              attr_reader tax_type: MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration::PaymentGateConfig::tax_type?

              def tax_type=: (
                MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration::PaymentGateConfig::tax_type
              ) -> MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration::PaymentGateConfig::tax_type

              def initialize: (
                payment_gate_type: MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration::PaymentGateConfig::payment_gate_type,
                ?stripe_config: MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration::PaymentGateConfig::StripeConfig,
                ?tax_type: MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration::PaymentGateConfig::tax_type
              ) -> void

              type payment_gate_type = :NONE | :STRIPE | :EXTERNAL

              module PaymentGateType
                extend MetronomeSDK::Internal::Type::Enum

                NONE: :NONE
                STRIPE: :STRIPE
                EXTERNAL: :EXTERNAL

                def self?.values: -> ::Array[MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration::PaymentGateConfig::payment_gate_type]
              end

              type stripe_config =
                {
                  payment_type: MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration::PaymentGateConfig::StripeConfig::payment_type
                }

              class StripeConfig < MetronomeSDK::Internal::Type::BaseModel
                attr_accessor payment_type: MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration::PaymentGateConfig::StripeConfig::payment_type

                def initialize: (
                  payment_type: MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration::PaymentGateConfig::StripeConfig::payment_type
                ) -> void

                type payment_type = :INVOICE | :PAYMENT_INTENT

                module PaymentType
                  extend MetronomeSDK::Internal::Type::Enum

                  INVOICE: :INVOICE
                  PAYMENT_INTENT: :PAYMENT_INTENT

                  def self?.values: -> ::Array[MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration::PaymentGateConfig::StripeConfig::payment_type]
                end
              end

              type tax_type = :NONE | :STRIPE

              module TaxType
                extend MetronomeSDK::Internal::Type::Enum

                NONE: :NONE
                STRIPE: :STRIPE

                def self?.values: -> ::Array[MetronomeSDK::Models::V1::ContractListResponse::Data::SpendThresholdConfiguration::PaymentGateConfig::tax_type]
              end
            end
          end
        end
      end
    end
  end
end
