module MetronomeSDK
  module Models
    module V1
      type contract_retrieve_response = { data: MetronomeSDK::Contract }

      class ContractRetrieveResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor data: MetronomeSDK::Contract

        def initialize: (data: MetronomeSDK::Contract) -> void

        def to_hash: -> { data: MetronomeSDK::Contract }
      end
    end
  end
end
