module MetronomeSDK
  module Models
    module V1
      type contract_list_response = { data: ::Array[MetronomeSDK::Contract] }

      class ContractListResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor data: ::Array[MetronomeSDK::Contract]

        def initialize: (data: ::Array[MetronomeSDK::Contract]) -> void

        def to_hash: -> { data: ::Array[MetronomeSDK::Contract] }
      end
    end
  end
end
