module MetronomeSDK
  module Models
    module V1
      type contract_archive_response =
        { data: MetronomeSDK::Models::V1::ContractArchiveResponse::Data }

      class ContractArchiveResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor data: MetronomeSDK::Models::V1::ContractArchiveResponse::Data

        def initialize: (
          data: MetronomeSDK::Models::V1::ContractArchiveResponse::Data
        ) -> void

        type data = { id: String }

        class Data < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor id: String

          def initialize: (id: String) -> void
        end
      end
    end
  end
end
