module MetronomeSDK
  module Models
    module V1
      type contract_schedule_pro_services_invoice_params =
        {
          contract_id: String,
          customer_id: String,
          issued_at: Time,
          line_items: ::Array[MetronomeSDK::Models::V1::ContractScheduleProServicesInvoiceParams::LineItem],
          netsuite_invoice_header_end: Time,
          netsuite_invoice_header_start: Time
        }
        & MetronomeSDK::Internal::Type::request_parameters

      class ContractScheduleProServicesInvoiceParams < MetronomeSDK::Internal::Type::BaseModel
        extend MetronomeSDK::Internal::Type::RequestParameters::Converter
        include MetronomeSDK::Internal::Type::RequestParameters

        attr_accessor contract_id: String

        attr_accessor customer_id: String

        attr_accessor issued_at: Time

        attr_accessor line_items: ::Array[MetronomeSDK::Models::V1::ContractScheduleProServicesInvoiceParams::LineItem]

        attr_reader netsuite_invoice_header_end: Time?

        def netsuite_invoice_header_end=: (Time) -> Time

        attr_reader netsuite_invoice_header_start: Time?

        def netsuite_invoice_header_start=: (Time) -> Time

        def initialize: (
          contract_id: String,
          customer_id: String,
          issued_at: Time,
          line_items: ::Array[MetronomeSDK::Models::V1::ContractScheduleProServicesInvoiceParams::LineItem],
          ?netsuite_invoice_header_end: Time,
          ?netsuite_invoice_header_start: Time,
          ?request_options: MetronomeSDK::request_opts
        ) -> void

        def to_hash: -> MetronomeSDK::Models::V1::contract_schedule_pro_services_invoice_params

        type line_item =
          {
            professional_service_id: String,
            amendment_id: String,
            amount: Float,
            metadata: String,
            netsuite_invoice_billing_end: Time,
            netsuite_invoice_billing_start: Time,
            quantity: Float,
            unit_price: Float
          }

        class LineItem < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor professional_service_id: String

          attr_reader amendment_id: String?

          def amendment_id=: (String) -> String

          attr_reader amount: Float?

          def amount=: (Float) -> Float

          attr_reader metadata: String?

          def metadata=: (String) -> String

          attr_reader netsuite_invoice_billing_end: Time?

          def netsuite_invoice_billing_end=: (Time) -> Time

          attr_reader netsuite_invoice_billing_start: Time?

          def netsuite_invoice_billing_start=: (Time) -> Time

          attr_reader quantity: Float?

          def quantity=: (Float) -> Float

          attr_reader unit_price: Float?

          def unit_price=: (Float) -> Float

          def initialize: (
            professional_service_id: String,
            ?amendment_id: String,
            ?amount: Float,
            ?metadata: String,
            ?netsuite_invoice_billing_end: Time,
            ?netsuite_invoice_billing_start: Time,
            ?quantity: Float,
            ?unit_price: Float
          ) -> void

          def to_hash: -> MetronomeSDK::Models::V1::ContractScheduleProServicesInvoiceParams::line_item
        end
      end
    end
  end
end
