module MetronomeSDK
  module Models
    module V1
      type contract_list_balances_response =
        MetronomeSDK::Commit | MetronomeSDK::Credit

      module ContractListBalancesResponse
        extend MetronomeSDK::Internal::Type::Union

        def self?.variants: -> ::Array[MetronomeSDK::Models::V1::contract_list_balances_response]
      end
    end
  end
end
