module MetronomeSDK
  module Models
    module V1
      type credit_grant_void_response = { data: MetronomeSDK::Models::ID }

      class CreditGrantVoidResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor data: MetronomeSDK::Models::ID

        def initialize: (data: MetronomeSDK::Models::ID) -> void

        def to_hash: -> MetronomeSDK::Models::V1::credit_grant_void_response
      end
    end
  end
end
