module MetronomeSDK
  module Models
    module V1
      type credit_grant_void_response =
        { data: MetronomeSDK::Models::V1::CreditGrantVoidResponse::Data }

      class CreditGrantVoidResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor data: MetronomeSDK::Models::V1::CreditGrantVoidResponse::Data

        def initialize: (
          data: MetronomeSDK::Models::V1::CreditGrantVoidResponse::Data
        ) -> void

        type data = { id: String }

        class Data < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor id: String

          def initialize: (id: String) -> void
        end
      end
    end
  end
end
