module MetronomeSDK
  module Models
    module V1
      type credit_grant_void_response = { data: MetronomeSDK::ID }

      class CreditGrantVoidResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor data: MetronomeSDK::ID

        def initialize: (data: MetronomeSDK::ID) -> void
      end
    end
  end
end
