module MetronomeSDK
  module Models
    module V1
      type credit_grant_list_entries_response =
        {
          data: ::Array[MetronomeSDK::Models::V1::CreditGrantListEntriesResponse::Data],
          next_page: String?
        }

      class CreditGrantListEntriesResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor data: ::Array[MetronomeSDK::Models::V1::CreditGrantListEntriesResponse::Data]

        attr_accessor next_page: String?

        def initialize: (
          data: ::Array[MetronomeSDK::Models::V1::CreditGrantListEntriesResponse::Data],
          next_page: String?
        ) -> void

        type data =
          {
            customer_id: String,
            ledgers: ::Array[MetronomeSDK::Models::V1::CreditGrantListEntriesResponse::Data::Ledger]
          }

        class Data < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor customer_id: String

          attr_accessor ledgers: ::Array[MetronomeSDK::Models::V1::CreditGrantListEntriesResponse::Data::Ledger]

          def initialize: (
            customer_id: String,
            ledgers: ::Array[MetronomeSDK::Models::V1::CreditGrantListEntriesResponse::Data::Ledger]
          ) -> void

          type ledger =
            {
              credit_type: MetronomeSDK::Models::V1::CreditGrantListEntriesResponse::Data::Ledger::CreditType,
              ending_balance: MetronomeSDK::Models::V1::CreditGrantListEntriesResponse::Data::Ledger::EndingBalance,
              entries: ::Array[MetronomeSDK::Models::V1::CreditGrantListEntriesResponse::Data::Ledger::Entry],
              pending_entries: ::Array[MetronomeSDK::Models::V1::CreditGrantListEntriesResponse::Data::Ledger::PendingEntry],
              starting_balance: MetronomeSDK::Models::V1::CreditGrantListEntriesResponse::Data::Ledger::StartingBalance
            }

          class Ledger < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor credit_type: MetronomeSDK::Models::V1::CreditGrantListEntriesResponse::Data::Ledger::CreditType

            attr_accessor ending_balance: MetronomeSDK::Models::V1::CreditGrantListEntriesResponse::Data::Ledger::EndingBalance

            attr_accessor entries: ::Array[MetronomeSDK::Models::V1::CreditGrantListEntriesResponse::Data::Ledger::Entry]

            attr_accessor pending_entries: ::Array[MetronomeSDK::Models::V1::CreditGrantListEntriesResponse::Data::Ledger::PendingEntry]

            attr_accessor starting_balance: MetronomeSDK::Models::V1::CreditGrantListEntriesResponse::Data::Ledger::StartingBalance

            def initialize: (
              credit_type: MetronomeSDK::Models::V1::CreditGrantListEntriesResponse::Data::Ledger::CreditType,
              ending_balance: MetronomeSDK::Models::V1::CreditGrantListEntriesResponse::Data::Ledger::EndingBalance,
              entries: ::Array[MetronomeSDK::Models::V1::CreditGrantListEntriesResponse::Data::Ledger::Entry],
              pending_entries: ::Array[MetronomeSDK::Models::V1::CreditGrantListEntriesResponse::Data::Ledger::PendingEntry],
              starting_balance: MetronomeSDK::Models::V1::CreditGrantListEntriesResponse::Data::Ledger::StartingBalance
            ) -> void

            type credit_type = { id: String, name: String }

            class CreditType < MetronomeSDK::Internal::Type::BaseModel
              attr_accessor id: String

              attr_accessor name: String

              def initialize: (id: String, name: String) -> void
            end

            type ending_balance =
              {
                effective_at: Time,
                excluding_pending: Float,
                including_pending: Float
              }

            class EndingBalance < MetronomeSDK::Internal::Type::BaseModel
              attr_accessor effective_at: Time

              attr_accessor excluding_pending: Float

              attr_accessor including_pending: Float

              def initialize: (
                effective_at: Time,
                excluding_pending: Float,
                including_pending: Float
              ) -> void
            end

            type entry =
              {
                amount: Float,
                created_by: String,
                credit_grant_id: String,
                effective_at: Time,
                reason: String,
                running_balance: Float,
                invoice_id: String?
              }

            class Entry < MetronomeSDK::Internal::Type::BaseModel
              attr_accessor amount: Float

              attr_accessor created_by: String

              attr_accessor credit_grant_id: String

              attr_accessor effective_at: Time

              attr_accessor reason: String

              attr_accessor running_balance: Float

              attr_accessor invoice_id: String?

              def initialize: (
                amount: Float,
                created_by: String,
                credit_grant_id: String,
                effective_at: Time,
                reason: String,
                running_balance: Float,
                ?invoice_id: String?
              ) -> void
            end

            type pending_entry =
              {
                amount: Float,
                created_by: String,
                credit_grant_id: String,
                effective_at: Time,
                reason: String,
                running_balance: Float,
                invoice_id: String?
              }

            class PendingEntry < MetronomeSDK::Internal::Type::BaseModel
              attr_accessor amount: Float

              attr_accessor created_by: String

              attr_accessor credit_grant_id: String

              attr_accessor effective_at: Time

              attr_accessor reason: String

              attr_accessor running_balance: Float

              attr_accessor invoice_id: String?

              def initialize: (
                amount: Float,
                created_by: String,
                credit_grant_id: String,
                effective_at: Time,
                reason: String,
                running_balance: Float,
                ?invoice_id: String?
              ) -> void
            end

            type starting_balance =
              {
                effective_at: Time,
                excluding_pending: Float,
                including_pending: Float
              }

            class StartingBalance < MetronomeSDK::Internal::Type::BaseModel
              attr_accessor effective_at: Time

              attr_accessor excluding_pending: Float

              attr_accessor including_pending: Float

              def initialize: (
                effective_at: Time,
                excluding_pending: Float,
                including_pending: Float
              ) -> void
            end
          end
        end
      end
    end
  end
end
