module MetronomeSDK
  module Models
    module V1
      type credit_grant_list_entries_params =
        {
          next_page: String,
          credit_type_ids: ::Array[String],
          customer_ids: ::Array[String],
          ending_before: Time,
          starting_on: Time
        }
        & MetronomeSDK::Internal::Type::request_parameters

      class CreditGrantListEntriesParams < MetronomeSDK::Internal::Type::BaseModel
        extend MetronomeSDK::Internal::Type::RequestParameters::Converter
        include MetronomeSDK::Internal::Type::RequestParameters

        attr_reader next_page: String?

        def next_page=: (String) -> String

        attr_reader credit_type_ids: ::Array[String]?

        def credit_type_ids=: (::Array[String]) -> ::Array[String]

        attr_reader customer_ids: ::Array[String]?

        def customer_ids=: (::Array[String]) -> ::Array[String]

        attr_reader ending_before: Time?

        def ending_before=: (Time) -> Time

        attr_reader starting_on: Time?

        def starting_on=: (Time) -> Time

        def initialize: (
          ?next_page: String,
          ?credit_type_ids: ::Array[String],
          ?customer_ids: ::Array[String],
          ?ending_before: Time,
          ?starting_on: Time,
          ?request_options: MetronomeSDK::request_opts
        ) -> void
      end
    end
  end
end
