module MetronomeSDK
  module Models
    module V1
      type credit_grant_list_response =
        {
          id: String,
          balance: MetronomeSDK::Models::V1::CreditGrantListResponse::Balance,
          custom_fields: ::Hash[Symbol, String],
          customer_id: String,
          deductions: ::Array[MetronomeSDK::Models::V1::CreditGrantListResponse::Deduction],
          effective_at: Time,
          expires_at: Time,
          grant_amount: MetronomeSDK::Models::V1::CreditGrantListResponse::GrantAmount,
          name: String,
          paid_amount: MetronomeSDK::Models::V1::CreditGrantListResponse::PaidAmount,
          pending_deductions: ::Array[MetronomeSDK::Models::V1::CreditGrantListResponse::PendingDeduction],
          priority: Float,
          credit_grant_type: String?,
          invoice_id: String?,
          products: ::Array[MetronomeSDK::Models::V1::CreditGrantListResponse::Product],
          reason: String?,
          uniqueness_key: String?
        }

      class CreditGrantListResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor balance: MetronomeSDK::Models::V1::CreditGrantListResponse::Balance

        attr_accessor custom_fields: ::Hash[Symbol, String]

        attr_accessor customer_id: String

        attr_accessor deductions: ::Array[MetronomeSDK::Models::V1::CreditGrantListResponse::Deduction]

        attr_accessor effective_at: Time

        attr_accessor expires_at: Time

        attr_accessor grant_amount: MetronomeSDK::Models::V1::CreditGrantListResponse::GrantAmount

        attr_accessor name: String

        attr_accessor paid_amount: MetronomeSDK::Models::V1::CreditGrantListResponse::PaidAmount

        attr_accessor pending_deductions: ::Array[MetronomeSDK::Models::V1::CreditGrantListResponse::PendingDeduction]

        attr_accessor priority: Float

        attr_accessor credit_grant_type: String?

        attr_accessor invoice_id: String?

        attr_reader products: ::Array[MetronomeSDK::Models::V1::CreditGrantListResponse::Product]?

        def products=: (
          ::Array[MetronomeSDK::Models::V1::CreditGrantListResponse::Product]
        ) -> ::Array[MetronomeSDK::Models::V1::CreditGrantListResponse::Product]

        attr_accessor reason: String?

        attr_accessor uniqueness_key: String?

        def initialize: (
          id: String,
          balance: MetronomeSDK::Models::V1::CreditGrantListResponse::Balance,
          custom_fields: ::Hash[Symbol, String],
          customer_id: String,
          deductions: ::Array[MetronomeSDK::Models::V1::CreditGrantListResponse::Deduction],
          effective_at: Time,
          expires_at: Time,
          grant_amount: MetronomeSDK::Models::V1::CreditGrantListResponse::GrantAmount,
          name: String,
          paid_amount: MetronomeSDK::Models::V1::CreditGrantListResponse::PaidAmount,
          pending_deductions: ::Array[MetronomeSDK::Models::V1::CreditGrantListResponse::PendingDeduction],
          priority: Float,
          ?credit_grant_type: String?,
          ?invoice_id: String?,
          ?products: ::Array[MetronomeSDK::Models::V1::CreditGrantListResponse::Product],
          ?reason: String?,
          ?uniqueness_key: String?
        ) -> void

        type balance =
          {
            effective_at: Time,
            excluding_pending: Float,
            including_pending: Float
          }

        class Balance < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor effective_at: Time

          attr_accessor excluding_pending: Float

          attr_accessor including_pending: Float

          def initialize: (
            effective_at: Time,
            excluding_pending: Float,
            including_pending: Float
          ) -> void
        end

        type deduction =
          {
            amount: Float,
            created_by: String,
            credit_grant_id: String,
            effective_at: Time,
            reason: String,
            running_balance: Float,
            invoice_id: String?
          }

        class Deduction < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor amount: Float

          attr_accessor created_by: String

          attr_accessor credit_grant_id: String

          attr_accessor effective_at: Time

          attr_accessor reason: String

          attr_accessor running_balance: Float

          attr_accessor invoice_id: String?

          def initialize: (
            amount: Float,
            created_by: String,
            credit_grant_id: String,
            effective_at: Time,
            reason: String,
            running_balance: Float,
            ?invoice_id: String?
          ) -> void
        end

        type grant_amount =
          {
            amount: Float,
            credit_type: MetronomeSDK::Models::V1::CreditGrantListResponse::GrantAmount::CreditType
          }

        class GrantAmount < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor amount: Float

          attr_accessor credit_type: MetronomeSDK::Models::V1::CreditGrantListResponse::GrantAmount::CreditType

          def initialize: (
            amount: Float,
            credit_type: MetronomeSDK::Models::V1::CreditGrantListResponse::GrantAmount::CreditType
          ) -> void

          type credit_type = { id: String, name: String }

          class CreditType < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor name: String

            def initialize: (id: String, name: String) -> void
          end
        end

        type paid_amount =
          {
            amount: Float,
            credit_type: MetronomeSDK::Models::V1::CreditGrantListResponse::PaidAmount::CreditType
          }

        class PaidAmount < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor amount: Float

          attr_accessor credit_type: MetronomeSDK::Models::V1::CreditGrantListResponse::PaidAmount::CreditType

          def initialize: (
            amount: Float,
            credit_type: MetronomeSDK::Models::V1::CreditGrantListResponse::PaidAmount::CreditType
          ) -> void

          type credit_type = { id: String, name: String }

          class CreditType < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor name: String

            def initialize: (id: String, name: String) -> void
          end
        end

        type pending_deduction =
          {
            amount: Float,
            created_by: String,
            credit_grant_id: String,
            effective_at: Time,
            reason: String,
            running_balance: Float,
            invoice_id: String?
          }

        class PendingDeduction < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor amount: Float

          attr_accessor created_by: String

          attr_accessor credit_grant_id: String

          attr_accessor effective_at: Time

          attr_accessor reason: String

          attr_accessor running_balance: Float

          attr_accessor invoice_id: String?

          def initialize: (
            amount: Float,
            created_by: String,
            credit_grant_id: String,
            effective_at: Time,
            reason: String,
            running_balance: Float,
            ?invoice_id: String?
          ) -> void
        end

        type product = { id: String, name: String }

        class Product < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor name: String

          def initialize: (id: String, name: String) -> void
        end
      end
    end
  end
end
