module MetronomeSDK
  module Models
    module V1
      type customer_retrieve_params =
        { customer_id: String }
        & MetronomeSDK::Internal::Type::request_parameters

      class CustomerRetrieveParams < MetronomeSDK::Internal::Type::BaseModel
        extend MetronomeSDK::Internal::Type::RequestParameters::Converter
        include MetronomeSDK::Internal::Type::RequestParameters

        attr_accessor customer_id: String

        def initialize: (
          customer_id: String,
          ?request_options: MetronomeSDK::request_opts
        ) -> void
      end
    end
  end
end
