module MetronomeSDK
  module Models
    module V1
      type custom_field_add_key_params =
        {
          enforce_uniqueness: bool,
          entity: MetronomeSDK::Models::V1::CustomFieldAddKeyParams::entity,
          key: String
        }
        & MetronomeSDK::Internal::Type::request_parameters

      class CustomFieldAddKeyParams < MetronomeSDK::Internal::Type::BaseModel
        extend MetronomeSDK::Internal::Type::RequestParameters::Converter
        include MetronomeSDK::Internal::Type::RequestParameters

        attr_accessor enforce_uniqueness: bool

        attr_accessor entity: MetronomeSDK::Models::V1::CustomFieldAddKeyParams::entity

        attr_accessor key: String

        def initialize: (
          enforce_uniqueness: bool,
          entity: MetronomeSDK::Models::V1::CustomFieldAddKeyParams::entity,
          key: String,
          ?request_options: MetronomeSDK::request_opts
        ) -> void

        def to_hash: -> {
          enforce_uniqueness: bool,
          entity: MetronomeSDK::Models::V1::CustomFieldAddKeyParams::entity,
          key: String,
          request_options: MetronomeSDK::RequestOptions
        }

        type entity =
          :alert
          | :billable_metric
          | :charge
          | :commit
          | :contract_credit
          | :contract_product
          | :contract
          | :credit_grant
          | :customer_plan
          | :customer
          | :discount
          | :invoice
          | :plan
          | :professional_service
          | :product
          | :rate_card
          | :scheduled_charge
          | :subscription
          | :package_commit
          | :package_credit
          | :package_subscription
          | :package_scheduled_charge

        module Entity
          extend MetronomeSDK::Internal::Type::Enum

          ALERT: :alert
          BILLABLE_METRIC: :billable_metric
          CHARGE: :charge
          COMMIT: :commit
          CONTRACT_CREDIT: :contract_credit
          CONTRACT_PRODUCT: :contract_product
          CONTRACT: :contract
          CREDIT_GRANT: :credit_grant
          CUSTOMER_PLAN: :customer_plan
          CUSTOMER: :customer
          DISCOUNT: :discount
          INVOICE: :invoice
          PLAN: :plan
          PROFESSIONAL_SERVICE: :professional_service
          PRODUCT: :product
          RATE_CARD: :rate_card
          SCHEDULED_CHARGE: :scheduled_charge
          SUBSCRIPTION: :subscription
          PACKAGE_COMMIT: :package_commit
          PACKAGE_CREDIT: :package_credit
          PACKAGE_SUBSCRIPTION: :package_subscription
          PACKAGE_SCHEDULED_CHARGE: :package_scheduled_charge

          def self?.values: -> ::Array[MetronomeSDK::Models::V1::CustomFieldAddKeyParams::entity]
        end
      end
    end
  end
end
