module MetronomeSDK
  module Models
    module V1
      type customer_update_config_params =
        {
          customer_id: String,
          leave_stripe_invoices_in_draft: bool?,
          salesforce_account_id: String?
        }
        & MetronomeSDK::Internal::Type::request_parameters

      class CustomerUpdateConfigParams < MetronomeSDK::Internal::Type::BaseModel
        extend MetronomeSDK::Internal::Type::RequestParameters::Converter
        include MetronomeSDK::Internal::Type::RequestParameters

        attr_accessor customer_id: String

        attr_accessor leave_stripe_invoices_in_draft: bool?

        attr_accessor salesforce_account_id: String?

        def initialize: (
          customer_id: String,
          ?leave_stripe_invoices_in_draft: bool?,
          ?salesforce_account_id: String?,
          ?request_options: MetronomeSDK::request_opts
        ) -> void
      end
    end
  end
end
