module MetronomeSDK
  module Models
    module V1
      type customer_create_response = { data: MetronomeSDK::V1::Customer }

      class CustomerCreateResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor data: MetronomeSDK::V1::Customer

        def initialize: (data: MetronomeSDK::V1::Customer) -> void

        def to_hash: -> { data: MetronomeSDK::V1::Customer }
      end
    end
  end
end
