module MetronomeSDK
  module Models
    module V1
      type customer_list_billable_metrics_params =
        {
          customer_id: String,
          include_archived: bool,
          limit: Integer,
          next_page: String,
          on_current_plan: bool
        }
        & MetronomeSDK::Internal::Type::request_parameters

      class CustomerListBillableMetricsParams < MetronomeSDK::Internal::Type::BaseModel
        extend MetronomeSDK::Internal::Type::RequestParameters::Converter
        include MetronomeSDK::Internal::Type::RequestParameters

        attr_accessor customer_id: String

        attr_reader include_archived: bool?

        def include_archived=: (bool) -> bool

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader next_page: String?

        def next_page=: (String) -> String

        attr_reader on_current_plan: bool?

        def on_current_plan=: (bool) -> bool

        def initialize: (
          customer_id: String,
          ?include_archived: bool,
          ?limit: Integer,
          ?next_page: String,
          ?on_current_plan: bool,
          ?request_options: MetronomeSDK::request_opts
        ) -> void
      end
    end
  end
end
