module MetronomeSDK
  module Models
    module V1
      type customer =
        {
          id: String,
          external_id: String,
          ingest_aliases: ::Array[String],
          name: String,
          custom_fields: ::Hash[Symbol, String]
        }

      class Customer < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor external_id: String

        attr_accessor ingest_aliases: ::Array[String]

        attr_accessor name: String

        attr_reader custom_fields: ::Hash[Symbol, String]?

        def custom_fields=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        def initialize: (
          id: String,
          external_id: String,
          ingest_aliases: ::Array[String],
          name: String,
          ?custom_fields: ::Hash[Symbol, String]
        ) -> void

        def to_hash: -> {
          id: String,
          external_id: String,
          ingest_aliases: ::Array[String],
          name: String,
          custom_fields: ::Hash[Symbol, String]
        }
      end
    end
  end
end
