module MetronomeSDK
  module Models
    module V1
      type customer_list_costs_params =
        {
          customer_id: String,
          ending_before: Time,
          starting_on: Time,
          limit: Integer,
          next_page: String
        }
        & MetronomeSDK::Internal::Type::request_parameters

      class CustomerListCostsParams < MetronomeSDK::Internal::Type::BaseModel
        extend MetronomeSDK::Internal::Type::RequestParameters::Converter
        include MetronomeSDK::Internal::Type::RequestParameters

        attr_accessor customer_id: String

        attr_accessor ending_before: Time

        attr_accessor starting_on: Time

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader next_page: String?

        def next_page=: (String) -> String

        def initialize: (
          customer_id: String,
          ending_before: Time,
          starting_on: Time,
          ?limit: Integer,
          ?next_page: String,
          ?request_options: MetronomeSDK::request_opts
        ) -> void

        def to_hash: -> {
          customer_id: String,
          ending_before: Time,
          starting_on: Time,
          limit: Integer,
          next_page: String,
          request_options: MetronomeSDK::RequestOptions
        }
      end
    end
  end
end
