module MetronomeSDK
  module Models
    module V1
      type customer_retrieve_response =
        { data: MetronomeSDK::V1::CustomerDetail }

      class CustomerRetrieveResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor data: MetronomeSDK::V1::CustomerDetail

        def initialize: (data: MetronomeSDK::V1::CustomerDetail) -> void
      end
    end
  end
end
