module MetronomeSDK
  module Models
    module V1
      type customer_set_name_params =
        { customer_id: String, name: String }
        & MetronomeSDK::Internal::Type::request_parameters

      class CustomerSetNameParams < MetronomeSDK::Internal::Type::BaseModel
        extend MetronomeSDK::Internal::Type::RequestParameters::Converter
        include MetronomeSDK::Internal::Type::RequestParameters

        attr_accessor customer_id: String

        attr_accessor name: String

        def initialize: (
          customer_id: String,
          name: String,
          ?request_options: MetronomeSDK::request_opts
        ) -> void

        def to_hash: -> MetronomeSDK::Models::V1::customer_set_name_params
      end
    end
  end
end
