module MetronomeSDK
  module Models
    module V1
      type customer_list_params =
        {
          customer_ids: ::Array[String],
          ingest_alias: String,
          limit: Integer,
          next_page: String,
          only_archived: bool,
          salesforce_account_ids: ::Array[String]
        }
        & MetronomeSDK::Internal::Type::request_parameters

      class CustomerListParams < MetronomeSDK::Internal::Type::BaseModel
        extend MetronomeSDK::Internal::Type::RequestParameters::Converter
        include MetronomeSDK::Internal::Type::RequestParameters

        attr_reader customer_ids: ::Array[String]?

        def customer_ids=: (::Array[String]) -> ::Array[String]

        attr_reader ingest_alias: String?

        def ingest_alias=: (String) -> String

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader next_page: String?

        def next_page=: (String) -> String

        attr_reader only_archived: bool?

        def only_archived=: (bool) -> bool

        attr_reader salesforce_account_ids: ::Array[String]?

        def salesforce_account_ids=: (::Array[String]) -> ::Array[String]

        def initialize: (
          ?customer_ids: ::Array[String],
          ?ingest_alias: String,
          ?limit: Integer,
          ?next_page: String,
          ?only_archived: bool,
          ?salesforce_account_ids: ::Array[String],
          ?request_options: MetronomeSDK::request_opts
        ) -> void
      end
    end
  end
end
