module MetronomeSDK
  module Models
    module V1
      type customer_archive_params =
        { id: String } & MetronomeSDK::Internal::Type::request_parameters

      class CustomerArchiveParams < MetronomeSDK::Internal::Type::BaseModel
        extend MetronomeSDK::Internal::Type::RequestParameters::Converter
        include MetronomeSDK::Internal::Type::RequestParameters

        attr_accessor id: String

        def initialize: (
          id: String,
          ?request_options: MetronomeSDK::request_opts
        ) -> void

        def to_hash: -> {
          id: String,
          request_options: MetronomeSDK::RequestOptions
        }
      end
    end
  end
end
