module MetronomeSDK
  module Models
    module V1
      type customer_archive_response = { data: MetronomeSDK::ID }

      class CustomerArchiveResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor data: MetronomeSDK::ID

        def initialize: (data: MetronomeSDK::ID) -> void
      end
    end
  end
end
