module MetronomeSDK
  module Models
    module V1
      type payment =
        {
          id: String,
          amount: Float,
          amount_paid: Float,
          contract_id: String,
          created_at: Time,
          customer_id: String,
          error_message: String,
          fiat_credit_type: MetronomeSDK::CreditTypeData,
          invoice_id: String,
          payment_gateway: MetronomeSDK::V1::Payment::PaymentGateway,
          revenue_system_payments: ::Array[MetronomeSDK::V1::Payment::RevenueSystemPayment],
          status: MetronomeSDK::Models::V1::payment_status,
          updated_at: Time
        }

      class Payment < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_reader amount: Float?

        def amount=: (Float) -> Float

        attr_reader amount_paid: Float?

        def amount_paid=: (Float) -> Float

        attr_reader contract_id: String?

        def contract_id=: (String) -> String

        attr_reader created_at: Time?

        def created_at=: (Time) -> Time

        attr_reader customer_id: String?

        def customer_id=: (String) -> String

        attr_reader error_message: String?

        def error_message=: (String) -> String

        attr_reader fiat_credit_type: MetronomeSDK::CreditTypeData?

        def fiat_credit_type=: (
          MetronomeSDK::CreditTypeData
        ) -> MetronomeSDK::CreditTypeData

        attr_reader invoice_id: String?

        def invoice_id=: (String) -> String

        attr_reader payment_gateway: MetronomeSDK::V1::Payment::PaymentGateway?

        def payment_gateway=: (
          MetronomeSDK::V1::Payment::PaymentGateway
        ) -> MetronomeSDK::V1::Payment::PaymentGateway

        attr_reader revenue_system_payments: ::Array[MetronomeSDK::V1::Payment::RevenueSystemPayment]?

        def revenue_system_payments=: (
          ::Array[MetronomeSDK::V1::Payment::RevenueSystemPayment]
        ) -> ::Array[MetronomeSDK::V1::Payment::RevenueSystemPayment]

        attr_reader status: MetronomeSDK::Models::V1::payment_status?

        def status=: (
          MetronomeSDK::Models::V1::payment_status
        ) -> MetronomeSDK::Models::V1::payment_status

        attr_reader updated_at: Time?

        def updated_at=: (Time) -> Time

        def initialize: (
          id: String,
          ?amount: Float,
          ?amount_paid: Float,
          ?contract_id: String,
          ?created_at: Time,
          ?customer_id: String,
          ?error_message: String,
          ?fiat_credit_type: MetronomeSDK::CreditTypeData,
          ?invoice_id: String,
          ?payment_gateway: MetronomeSDK::V1::Payment::PaymentGateway,
          ?revenue_system_payments: ::Array[MetronomeSDK::V1::Payment::RevenueSystemPayment],
          ?status: MetronomeSDK::Models::V1::payment_status,
          ?updated_at: Time
        ) -> void

        def to_hash: -> {
          id: String,
          amount: Float,
          amount_paid: Float,
          contract_id: String,
          created_at: Time,
          customer_id: String,
          error_message: String,
          fiat_credit_type: MetronomeSDK::CreditTypeData,
          invoice_id: String,
          payment_gateway: MetronomeSDK::V1::Payment::PaymentGateway,
          revenue_system_payments: ::Array[MetronomeSDK::V1::Payment::RevenueSystemPayment],
          status: MetronomeSDK::Models::V1::payment_status,
          updated_at: Time
        }

        type payment_gateway =
          {
            stripe: MetronomeSDK::V1::Payment::PaymentGateway::Stripe,
            type: MetronomeSDK::Models::V1::Payment::PaymentGateway::type_
          }

        class PaymentGateway < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor stripe: MetronomeSDK::V1::Payment::PaymentGateway::Stripe

          attr_accessor type: MetronomeSDK::Models::V1::Payment::PaymentGateway::type_

          def initialize: (
            stripe: MetronomeSDK::V1::Payment::PaymentGateway::Stripe,
            type: MetronomeSDK::Models::V1::Payment::PaymentGateway::type_
          ) -> void

          def to_hash: -> {
            stripe: MetronomeSDK::V1::Payment::PaymentGateway::Stripe,
            type: MetronomeSDK::Models::V1::Payment::PaymentGateway::type_
          }

          type stripe =
            {
              payment_intent_id: String,
              error: MetronomeSDK::V1::Payment::PaymentGateway::Stripe::Error,
              payment_method_id: String
            }

          class Stripe < MetronomeSDK::Internal::Type::BaseModel
            attr_accessor payment_intent_id: String

            attr_reader error: MetronomeSDK::V1::Payment::PaymentGateway::Stripe::Error?

            def error=: (
              MetronomeSDK::V1::Payment::PaymentGateway::Stripe::Error
            ) -> MetronomeSDK::V1::Payment::PaymentGateway::Stripe::Error

            attr_reader payment_method_id: String?

            def payment_method_id=: (String) -> String

            def initialize: (
              payment_intent_id: String,
              ?error: MetronomeSDK::V1::Payment::PaymentGateway::Stripe::Error,
              ?payment_method_id: String
            ) -> void

            def to_hash: -> {
              payment_intent_id: String,
              error: MetronomeSDK::V1::Payment::PaymentGateway::Stripe::Error,
              payment_method_id: String
            }

            type error = { code: String, decline_code: String, type: String }

            class Error < MetronomeSDK::Internal::Type::BaseModel
              attr_reader code: String?

              def code=: (String) -> String

              attr_reader decline_code: String?

              def decline_code=: (String) -> String

              attr_reader type: String?

              def type=: (String) -> String

              def initialize: (
                ?code: String,
                ?decline_code: String,
                ?type: String
              ) -> void

              def to_hash: -> {
                code: String,
                decline_code: String,
                type: String
              }
            end
          end

          type type_ = :stripe

          module Type
            extend MetronomeSDK::Internal::Type::Enum

            STRIPE: :stripe

            def self?.values: -> ::Array[MetronomeSDK::Models::V1::Payment::PaymentGateway::type_]
          end
        end

        type revenue_system_payment =
          {
            revenue_system_provider: String,
            sync_status: String,
            error_message: String,
            revenue_system_external_payment_id: String
          }

        class RevenueSystemPayment < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor revenue_system_provider: String

          attr_accessor sync_status: String

          attr_reader error_message: String?

          def error_message=: (String) -> String

          attr_reader revenue_system_external_payment_id: String?

          def revenue_system_external_payment_id=: (String) -> String

          def initialize: (
            revenue_system_provider: String,
            sync_status: String,
            ?error_message: String,
            ?revenue_system_external_payment_id: String
          ) -> void

          def to_hash: -> {
            revenue_system_provider: String,
            sync_status: String,
            error_message: String,
            revenue_system_external_payment_id: String
          }
        end
      end
    end
  end
end
