module MetronomeSDK
  module Models
    module V1
      type plan_get_details_response = { data: MetronomeSDK::V1::PlanDetail }

      class PlanGetDetailsResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor data: MetronomeSDK::V1::PlanDetail

        def initialize: (data: MetronomeSDK::V1::PlanDetail) -> void

        def to_hash: -> { data: MetronomeSDK::V1::PlanDetail }
      end
    end
  end
end
