module MetronomeSDK
  module Models
    module V1
      type plan_list_charges_params =
        { plan_id: String, limit: Integer, next_page: String }
        & MetronomeSDK::Internal::Type::request_parameters

      class PlanListChargesParams < MetronomeSDK::Internal::Type::BaseModel
        extend MetronomeSDK::Internal::Type::RequestParameters::Converter
        include MetronomeSDK::Internal::Type::RequestParameters

        attr_accessor plan_id: String

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader next_page: String?

        def next_page=: (String) -> String

        def initialize: (
          plan_id: String,
          ?limit: Integer,
          ?next_page: String,
          ?request_options: MetronomeSDK::request_opts
        ) -> void

        def to_hash: -> {
          plan_id: String,
          limit: Integer,
          next_page: String,
          request_options: MetronomeSDK::RequestOptions
        }
      end
    end
  end
end
