module MetronomeSDK
  module Models
    module V1
      type plan_list_response =
        {
          id: String,
          description: String,
          name: String,
          custom_fields: ::Hash[Symbol, String]
        }

      class PlanListResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor description: String

        attr_accessor name: String

        attr_reader custom_fields: ::Hash[Symbol, String]?

        def custom_fields=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        def initialize: (
          id: String,
          description: String,
          name: String,
          ?custom_fields: ::Hash[Symbol, String]
        ) -> void
      end
    end
  end
end
