module MetronomeSDK
  module Models
    module V1
      type pricing_unit_create_params =
        { name: String } & MetronomeSDK::Internal::Type::request_parameters

      class PricingUnitCreateParams < MetronomeSDK::Internal::Type::BaseModel
        extend MetronomeSDK::Internal::Type::RequestParameters::Converter
        include MetronomeSDK::Internal::Type::RequestParameters

        attr_accessor name: String

        def initialize: (
          name: String,
          ?request_options: MetronomeSDK::request_opts
        ) -> void

        def to_hash: -> {
          name: String,
          request_options: MetronomeSDK::RequestOptions
        }
      end
    end
  end
end
