module MetronomeSDK
  module Models
    module V1
      type rollover_amount_max_amount =
        { type: MetronomeSDK::V1::RolloverAmountMaxAmount::type_, value: Float }

      class RolloverAmountMaxAmount < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor type: MetronomeSDK::V1::RolloverAmountMaxAmount::type_

        attr_accessor value: Float

        def initialize: (
          type: MetronomeSDK::V1::RolloverAmountMaxAmount::type_,
          value: Float
        ) -> void

        type type_ = :MAX_AMOUNT

        module Type
          extend MetronomeSDK::Internal::Type::Enum

          MAX_AMOUNT: :MAX_AMOUNT

          def self?.values: -> ::Array[MetronomeSDK::V1::RolloverAmountMaxAmount::type_]
        end
      end
    end
  end
end
