module MetronomeSDK
  module Models
    module V1
      type setting_upsert_avalara_credentials_response = {  }

      class SettingUpsertAvalaraCredentialsResponse < MetronomeSDK::Internal::Type::BaseModel
        def initialize: -> void

        def to_hash: -> {  }
      end
    end
  end
end
