module MetronomeSDK
  module Models
    module V1
      type usage_list_with_groups_response =
        {
          ending_before: Time,
          group_key: String?,
          group_value: String?,
          starting_on: Time,
          value: Float?,
          group: ::Hash[Symbol, String]
        }

      class UsageListWithGroupsResponse < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor ending_before: Time

        attr_accessor group_key: String?

        attr_accessor group_value: String?

        attr_accessor starting_on: Time

        attr_accessor value: Float?

        attr_reader group: ::Hash[Symbol, String]?

        def group=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        def initialize: (
          ending_before: Time,
          group_key: String?,
          group_value: String?,
          starting_on: Time,
          value: Float?,
          ?group: ::Hash[Symbol, String]
        ) -> void

        def to_hash: -> {
          ending_before: Time,
          group_key: String?,
          group_value: String?,
          starting_on: Time,
          value: Float?,
          group: ::Hash[Symbol, String]
        }
      end
    end
  end
end
