module MetronomeSDK
  module Resources
    class Notifications
      class Offset
        def list: (
          ?archive_filter: MetronomeSDK::Models::Notifications::OffsetListParams::archive_filter,
          ?cursor: String,
          ?limit: Float,
          ?request_options: MetronomeSDK::request_opts
        ) -> MetronomeSDK::Models::Notifications::OffsetListResponse

        def initialize: (client: MetronomeSDK::Client) -> void
      end
    end
  end
end
