module Metronome
  module Models
    module Contracts
      module RateCards
        type named_schedule_update_params =
          {
            contract_id: String,
            customer_id: String,
            schedule_name: String,
            starting_at: Time,
            value: top,
            ending_before: Time
          }
          & Metronome::request_parameters

        class NamedScheduleUpdateParams < Metronome::BaseModel
          extend Metronome::RequestParameters::Converter
          include Metronome::RequestParameters

          attr_accessor contract_id: String

          attr_accessor customer_id: String

          attr_accessor schedule_name: String

          attr_accessor starting_at: Time

          attr_accessor value: top

          attr_reader ending_before: Time?

          def ending_before=: (Time) -> void

          def initialize:
            (
              contract_id: String,
              customer_id: String,
              schedule_name: String,
              starting_at: Time,
              value: top,
              ending_before: Time,
              request_options: Metronome::request_opts
            ) -> void
            | (
              ?Metronome::Models::Contracts::RateCards::named_schedule_update_params
              | Metronome::BaseModel data
            ) -> void

          def to_hash: -> Metronome::Models::Contracts::RateCards::named_schedule_update_params
        end
      end
    end
  end
end
