module Metronome
  module Models
    module Contracts
      module RateCards
        type rate_add_response =
          {
            data: Metronome::Models::Contracts::RateCards::RateAddResponse::Data
          }

        class RateAddResponse < Metronome::BaseModel
          attr_accessor data: Metronome::Models::Contracts::RateCards::RateAddResponse::Data

          def initialize:
            (
              data: Metronome::Models::Contracts::RateCards::RateAddResponse::Data
            ) -> void
            | (
              ?Metronome::Models::Contracts::RateCards::rate_add_response
              | Metronome::BaseModel data
            ) -> void

          def to_hash: -> Metronome::Models::Contracts::RateCards::rate_add_response

          type data =
            {
              rate_type: Metronome::Models::Contracts::RateCards::RateAddResponse::Data::rate_type,
              commit_rate: Metronome::Models::Contracts::RateCards::RateAddResponse::Data::CommitRate,
              credit_type: Metronome::Models::CreditTypeData,
              custom_rate: ::Hash[Symbol, top],
              is_prorated: bool,
              price: Float,
              pricing_group_values: ::Hash[Symbol, String],
              quantity: Float,
              tiers: ::Array[Metronome::Models::Tier],
              use_list_prices: bool
            }

          class Data < Metronome::BaseModel
            attr_accessor rate_type: Metronome::Models::Contracts::RateCards::RateAddResponse::Data::rate_type

            attr_reader commit_rate: Metronome::Models::Contracts::RateCards::RateAddResponse::Data::CommitRate?

            def commit_rate=: (
              Metronome::Models::Contracts::RateCards::RateAddResponse::Data::CommitRate
            ) -> void

            attr_reader credit_type: Metronome::Models::CreditTypeData?

            def credit_type=: (Metronome::Models::CreditTypeData) -> void

            attr_reader custom_rate: ::Hash[Symbol, top]?

            def custom_rate=: (::Hash[Symbol, top]) -> void

            attr_reader is_prorated: bool?

            def is_prorated=: (bool) -> void

            attr_reader price: Float?

            def price=: (Float) -> void

            attr_reader pricing_group_values: ::Hash[Symbol, String]?

            def pricing_group_values=: (::Hash[Symbol, String]) -> void

            attr_reader quantity: Float?

            def quantity=: (Float) -> void

            attr_reader tiers: ::Array[Metronome::Models::Tier]?

            def tiers=: (::Array[Metronome::Models::Tier]) -> void

            attr_reader use_list_prices: bool?

            def use_list_prices=: (bool) -> void

            def initialize:
              (
                rate_type: Metronome::Models::Contracts::RateCards::RateAddResponse::Data::rate_type,
                commit_rate: Metronome::Models::Contracts::RateCards::RateAddResponse::Data::CommitRate,
                credit_type: Metronome::Models::CreditTypeData,
                custom_rate: ::Hash[Symbol, top],
                is_prorated: bool,
                price: Float,
                pricing_group_values: ::Hash[Symbol, String],
                quantity: Float,
                tiers: ::Array[Metronome::Models::Tier],
                use_list_prices: bool
              ) -> void
              | (
                ?Metronome::Models::Contracts::RateCards::RateAddResponse::data
                | Metronome::BaseModel data
              ) -> void

            def to_hash: -> Metronome::Models::Contracts::RateCards::RateAddResponse::data

            type rate_type =
              :FLAT | :PERCENTAGE | :SUBSCRIPTION | :CUSTOM | :TIERED

            class RateType < Metronome::Enum
              FLAT: :FLAT
              PERCENTAGE: :PERCENTAGE
              SUBSCRIPTION: :SUBSCRIPTION
              CUSTOM: :CUSTOM
              TIERED: :TIERED

              def self.values: -> ::Array[Metronome::Models::Contracts::RateCards::RateAddResponse::Data::rate_type]
            end

            type commit_rate =
              {
                rate_type: Metronome::Models::Contracts::RateCards::RateAddResponse::Data::CommitRate::rate_type,
                price: Float,
                tiers: ::Array[Metronome::Models::Tier]
              }

            class CommitRate < Metronome::BaseModel
              attr_accessor rate_type: Metronome::Models::Contracts::RateCards::RateAddResponse::Data::CommitRate::rate_type

              attr_reader price: Float?

              def price=: (Float) -> void

              attr_reader tiers: ::Array[Metronome::Models::Tier]?

              def tiers=: (::Array[Metronome::Models::Tier]) -> void

              def initialize:
                (
                  rate_type: Metronome::Models::Contracts::RateCards::RateAddResponse::Data::CommitRate::rate_type,
                  price: Float,
                  tiers: ::Array[Metronome::Models::Tier]
                ) -> void
                | (
                  ?Metronome::Models::Contracts::RateCards::RateAddResponse::Data::commit_rate
                  | Metronome::BaseModel data
                ) -> void

              def to_hash: -> Metronome::Models::Contracts::RateCards::RateAddResponse::Data::commit_rate

              type rate_type =
                :FLAT | :PERCENTAGE | :SUBSCRIPTION | :TIERED | :CUSTOM

              class RateType < Metronome::Enum
                FLAT: :FLAT
                PERCENTAGE: :PERCENTAGE
                SUBSCRIPTION: :SUBSCRIPTION
                TIERED: :TIERED
                CUSTOM: :CUSTOM

                def self.values: -> ::Array[Metronome::Models::Contracts::RateCards::RateAddResponse::Data::CommitRate::rate_type]
              end
            end
          end
        end
      end
    end
  end
end
