module MetronomeSDK
  module Models
    module V1
      module Contracts
        type product_retrieve_params = {  } & MetronomeSDK::request_parameters

        class ProductRetrieveParams < MetronomeSDK::Models::ID
          extend MetronomeSDK::RequestParameters::Converter
          include MetronomeSDK::RequestParameters

          def initialize:
            (request_options: MetronomeSDK::request_opts) -> void
            | (
              ?MetronomeSDK::Models::V1::Contracts::product_retrieve_params
              | MetronomeSDK::BaseModel data
            ) -> void

          def to_hash: -> MetronomeSDK::Models::V1::Contracts::product_retrieve_params
        end
      end
    end
  end
end
