module MetronomeSDK
  module Models
    module V1
      module Contracts
        type rate_card_list_response =
          {
            id: String,
            created_at: Time,
            created_by: String,
            name: String,
            aliases: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardListResponse::Alias],
            credit_type_conversions: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardListResponse::CreditTypeConversion],
            custom_fields: ::Hash[Symbol, String],
            description: String,
            fiat_credit_type: MetronomeSDK::Models::CreditTypeData
          }

        class RateCardListResponse < MetronomeSDK::BaseModel
          attr_accessor id: String

          attr_accessor created_at: Time

          attr_accessor created_by: String

          attr_accessor name: String

          attr_reader aliases: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardListResponse::Alias]?

          def aliases=: (
            ::Array[MetronomeSDK::Models::V1::Contracts::RateCardListResponse::Alias]
          ) -> ::Array[MetronomeSDK::Models::V1::Contracts::RateCardListResponse::Alias]

          attr_reader credit_type_conversions: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardListResponse::CreditTypeConversion]?

          def credit_type_conversions=: (
            ::Array[MetronomeSDK::Models::V1::Contracts::RateCardListResponse::CreditTypeConversion]
          ) -> ::Array[MetronomeSDK::Models::V1::Contracts::RateCardListResponse::CreditTypeConversion]

          attr_reader custom_fields: ::Hash[Symbol, String]?

          def custom_fields=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

          attr_reader description: String?

          def description=: (String) -> String

          attr_reader fiat_credit_type: MetronomeSDK::Models::CreditTypeData?

          def fiat_credit_type=: (
            MetronomeSDK::Models::CreditTypeData
          ) -> MetronomeSDK::Models::CreditTypeData

          def initialize:
            (
              id: String,
              created_at: Time,
              created_by: String,
              name: String,
              aliases: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardListResponse::Alias],
              credit_type_conversions: ::Array[MetronomeSDK::Models::V1::Contracts::RateCardListResponse::CreditTypeConversion],
              custom_fields: ::Hash[Symbol, String],
              description: String,
              fiat_credit_type: MetronomeSDK::Models::CreditTypeData
            ) -> void
            | (
              ?MetronomeSDK::Models::V1::Contracts::rate_card_list_response
              | MetronomeSDK::BaseModel data
            ) -> void

          def to_hash: -> MetronomeSDK::Models::V1::Contracts::rate_card_list_response

          type alias_ = { name: String, ending_before: Time, starting_at: Time }

          class Alias < MetronomeSDK::BaseModel
            attr_accessor name: String

            attr_reader ending_before: Time?

            def ending_before=: (Time) -> Time

            attr_reader starting_at: Time?

            def starting_at=: (Time) -> Time

            def initialize:
              (name: String, ending_before: Time, starting_at: Time) -> void
              | (
                ?MetronomeSDK::Models::V1::Contracts::RateCardListResponse::alias_
                | MetronomeSDK::BaseModel data
              ) -> void

            def to_hash: -> MetronomeSDK::Models::V1::Contracts::RateCardListResponse::alias_
          end

          type credit_type_conversion =
            {
              custom_credit_type: MetronomeSDK::Models::CreditTypeData,
              fiat_per_custom_credit: String
            }

          class CreditTypeConversion < MetronomeSDK::BaseModel
            attr_accessor custom_credit_type: MetronomeSDK::Models::CreditTypeData

            attr_accessor fiat_per_custom_credit: String

            def initialize:
              (
                custom_credit_type: MetronomeSDK::Models::CreditTypeData,
                fiat_per_custom_credit: String
              ) -> void
              | (
                ?MetronomeSDK::Models::V1::Contracts::RateCardListResponse::credit_type_conversion
                | MetronomeSDK::BaseModel data
              ) -> void

            def to_hash: -> MetronomeSDK::Models::V1::Contracts::RateCardListResponse::credit_type_conversion
          end
        end
      end
    end
  end
end
