module MetronomeSDK
  module Models
    module V1
      module Contracts
        module RateCards
          type rate_add_many_response = { data: MetronomeSDK::Models::ID }

          class RateAddManyResponse < MetronomeSDK::BaseModel
            attr_accessor data: MetronomeSDK::Models::ID

            def initialize:
              (data: MetronomeSDK::Models::ID) -> void
              | (
                ?MetronomeSDK::Models::V1::Contracts::RateCards::rate_add_many_response
                | MetronomeSDK::BaseModel data
              ) -> void

            def to_hash: -> MetronomeSDK::Models::V1::Contracts::RateCards::rate_add_many_response
          end
        end
      end
    end
  end
end
