module Metronome
  module Resources
    class Contracts
      class RateCards
        class NamedSchedules
          def retrieve:
            (
              Metronome::Models::Contracts::RateCards::NamedScheduleRetrieveParams
              | Hash[Symbol, top] params
            ) -> Metronome::Models::Contracts::RateCards::NamedScheduleRetrieveResponse
            | (
              Metronome::Models::Contracts::RateCards::NamedScheduleRetrieveParams
              | Hash[Symbol, top] params,
              contract_id: String,
              customer_id: String,
              schedule_name: String,
              covering_date: Time,
              request_options: Metronome::request_opts
            ) -> Metronome::Models::Contracts::RateCards::NamedScheduleRetrieveResponse

          def update:
            (
              Metronome::Models::Contracts::RateCards::NamedScheduleUpdateParams
              | Hash[Symbol, top] params
            ) -> nil
            | (
              Metronome::Models::Contracts::RateCards::NamedScheduleUpdateParams
              | Hash[Symbol, top] params,
              contract_id: String,
              customer_id: String,
              schedule_name: String,
              starting_at: Time,
              value: top,
              ending_before: Time,
              request_options: Metronome::request_opts
            ) -> nil

          def initialize: (client: Metronome::Client) -> void
        end
      end
    end
  end
end
