module MetronomeSDK
  module Models
    type base_threshold_commit =
      { product_id: String, description: String, name: String }

    class BaseThresholdCommit < MetronomeSDK::Internal::Type::BaseModel
      attr_accessor product_id: String

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader name: String?

      def name=: (String) -> String

      def initialize: (
        product_id: String,
        ?description: String,
        ?name: String
      ) -> void

      def to_hash: -> { product_id: String, description: String, name: String }
    end
  end
end
