module MetronomeSDK
  module Models
    type hierarchy_configuration =
      MetronomeSDK::HierarchyConfiguration::ParentHierarchyConfiguration
      | MetronomeSDK::HierarchyConfiguration::ChildHierarchyConfiguration

    module HierarchyConfiguration
      extend MetronomeSDK::Internal::Type::Union

      type parent_hierarchy_configuration =
        {
          children: ::Array[MetronomeSDK::HierarchyConfiguration::ParentHierarchyConfiguration::Child]
        }

      class ParentHierarchyConfiguration < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor children: ::Array[MetronomeSDK::HierarchyConfiguration::ParentHierarchyConfiguration::Child]

        def initialize: (
          children: ::Array[MetronomeSDK::HierarchyConfiguration::ParentHierarchyConfiguration::Child]
        ) -> void

        def to_hash: -> {
          children: ::Array[MetronomeSDK::HierarchyConfiguration::ParentHierarchyConfiguration::Child]
        }

        type child = { contract_id: String, customer_id: String }

        class Child < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor contract_id: String

          attr_accessor customer_id: String

          def initialize: (contract_id: String, customer_id: String) -> void

          def to_hash: -> { contract_id: String, customer_id: String }
        end
      end

      type child_hierarchy_configuration =
        {
          parent: MetronomeSDK::HierarchyConfiguration::ChildHierarchyConfiguration::Parent
        }

      class ChildHierarchyConfiguration < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor parent: MetronomeSDK::HierarchyConfiguration::ChildHierarchyConfiguration::Parent

        def initialize: (
          parent: MetronomeSDK::HierarchyConfiguration::ChildHierarchyConfiguration::Parent
        ) -> void

        def to_hash: -> {
          parent: MetronomeSDK::HierarchyConfiguration::ChildHierarchyConfiguration::Parent
        }

        type parent = { contract_id: String, customer_id: String }

        class Parent < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor contract_id: String

          attr_accessor customer_id: String

          def initialize: (contract_id: String, customer_id: String) -> void

          def to_hash: -> { contract_id: String, customer_id: String }
        end
      end

      def self?.variants: -> ::Array[MetronomeSDK::Models::hierarchy_configuration]
    end
  end
end
