module MetronomeSDK
  module Models
    type overwrite_rate =
      {
        rate_type: MetronomeSDK::Models::OverwriteRate::rate_type,
        credit_type: MetronomeSDK::CreditTypeData,
        custom_rate: ::Hash[Symbol, top],
        is_prorated: bool,
        price: Float,
        quantity: Float,
        tiers: ::Array[MetronomeSDK::Tier]
      }

    class OverwriteRate < MetronomeSDK::Internal::Type::BaseModel
      attr_accessor rate_type: MetronomeSDK::Models::OverwriteRate::rate_type

      attr_reader credit_type: MetronomeSDK::CreditTypeData?

      def credit_type=: (
        MetronomeSDK::CreditTypeData
      ) -> MetronomeSDK::CreditTypeData

      attr_reader custom_rate: ::Hash[Symbol, top]?

      def custom_rate=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      attr_reader is_prorated: bool?

      def is_prorated=: (bool) -> bool

      attr_reader price: Float?

      def price=: (Float) -> Float

      attr_reader quantity: Float?

      def quantity=: (Float) -> Float

      attr_reader tiers: ::Array[MetronomeSDK::Tier]?

      def tiers=: (::Array[MetronomeSDK::Tier]) -> ::Array[MetronomeSDK::Tier]

      def initialize: (
        rate_type: MetronomeSDK::Models::OverwriteRate::rate_type,
        ?credit_type: MetronomeSDK::CreditTypeData,
        ?custom_rate: ::Hash[Symbol, top],
        ?is_prorated: bool,
        ?price: Float,
        ?quantity: Float,
        ?tiers: ::Array[MetronomeSDK::Tier]
      ) -> void

      def to_hash: -> {
        rate_type: MetronomeSDK::Models::OverwriteRate::rate_type,
        credit_type: MetronomeSDK::CreditTypeData,
        custom_rate: ::Hash[Symbol, top],
        is_prorated: bool,
        price: Float,
        quantity: Float,
        tiers: ::Array[MetronomeSDK::Tier]
      }

      type rate_type =
        :FLAT
        | :PERCENTAGE
        | :SUBSCRIPTION
        | :TIERED
        | :TIERED_PERCENTAGE
        | :CUSTOM

      module RateType
        extend MetronomeSDK::Internal::Type::Enum

        FLAT: :FLAT
        PERCENTAGE: :PERCENTAGE
        SUBSCRIPTION: :SUBSCRIPTION
        TIERED: :TIERED
        TIERED_PERCENTAGE: :TIERED_PERCENTAGE
        CUSTOM: :CUSTOM

        def self?.values: -> ::Array[MetronomeSDK::Models::OverwriteRate::rate_type]
      end
    end
  end
end
