module MetronomeSDK
  module Models
    type payment_attempt_params =
      { customer_id: String, invoice_id: String }
      & MetronomeSDK::Internal::Type::request_parameters

    class PaymentAttemptParams < MetronomeSDK::Internal::Type::BaseModel
      extend MetronomeSDK::Internal::Type::RequestParameters::Converter
      include MetronomeSDK::Internal::Type::RequestParameters

      attr_accessor customer_id: String

      attr_accessor invoice_id: String

      def initialize: (
        customer_id: String,
        invoice_id: String,
        ?request_options: MetronomeSDK::request_opts
      ) -> void

      def to_hash: -> {
        customer_id: String,
        invoice_id: String,
        request_options: MetronomeSDK::RequestOptions
      }
    end
  end
end
