module MetronomeSDK
  module Models
    type prepaid_balance_threshold_configuration =
      {
        commit: MetronomeSDK::PrepaidBalanceThresholdConfiguration::Commit,
        is_enabled: bool,
        payment_gate_config: MetronomeSDK::PaymentGateConfig,
        recharge_to_amount: Float,
        threshold_amount: Float,
        custom_credit_type_id: String
      }

    class PrepaidBalanceThresholdConfiguration < MetronomeSDK::Internal::Type::BaseModel
      attr_accessor commit: MetronomeSDK::PrepaidBalanceThresholdConfiguration::Commit

      attr_accessor is_enabled: bool

      attr_accessor payment_gate_config: MetronomeSDK::PaymentGateConfig

      attr_accessor recharge_to_amount: Float

      attr_accessor threshold_amount: Float

      attr_reader custom_credit_type_id: String?

      def custom_credit_type_id=: (String) -> String

      def initialize: (
        commit: MetronomeSDK::PrepaidBalanceThresholdConfiguration::Commit,
        is_enabled: bool,
        payment_gate_config: MetronomeSDK::PaymentGateConfig,
        recharge_to_amount: Float,
        threshold_amount: Float,
        ?custom_credit_type_id: String
      ) -> void

      def to_hash: -> {
        commit: MetronomeSDK::PrepaidBalanceThresholdConfiguration::Commit,
        is_enabled: bool,
        payment_gate_config: MetronomeSDK::PaymentGateConfig,
        recharge_to_amount: Float,
        threshold_amount: Float,
        custom_credit_type_id: String
      }

      type commit =
        {
          applicable_product_ids: ::Array[String],
          applicable_product_tags: ::Array[String],
          specifiers: ::Array[MetronomeSDK::CommitSpecifierInput]
        }

      class Commit < MetronomeSDK::Models::BaseThresholdCommit
        def applicable_product_ids: -> ::Array[String]?

        def applicable_product_ids=: (::Array[String] _) -> ::Array[String]

        def applicable_product_tags: -> ::Array[String]?

        def applicable_product_tags=: (::Array[String] _) -> ::Array[String]

        def specifiers: -> ::Array[MetronomeSDK::CommitSpecifierInput]?

        def specifiers=: (
          ::Array[MetronomeSDK::CommitSpecifierInput] _
        ) -> ::Array[MetronomeSDK::CommitSpecifierInput]

        def initialize: (
          ?applicable_product_ids: ::Array[String],
          ?applicable_product_tags: ::Array[String],
          ?specifiers: ::Array[MetronomeSDK::CommitSpecifierInput]
        ) -> void

        def to_hash: -> {
          applicable_product_ids: ::Array[String],
          applicable_product_tags: ::Array[String],
          specifiers: ::Array[MetronomeSDK::CommitSpecifierInput]
        }
      end
    end
  end
end
