module MetronomeSDK
  module Models
    type spend_threshold_configuration_v2 =
      {
        commit: MetronomeSDK::BaseThresholdCommit,
        is_enabled: bool,
        payment_gate_config: MetronomeSDK::PaymentGateConfigV2,
        threshold_amount: Float,
        discount_configuration: MetronomeSDK::SpendThresholdConfigurationV2::DiscountConfiguration
      }

    class SpendThresholdConfigurationV2 < MetronomeSDK::Internal::Type::BaseModel
      attr_accessor commit: MetronomeSDK::BaseThresholdCommit

      attr_accessor is_enabled: bool

      attr_accessor payment_gate_config: MetronomeSDK::PaymentGateConfigV2

      attr_accessor threshold_amount: Float

      attr_reader discount_configuration: MetronomeSDK::SpendThresholdConfigurationV2::DiscountConfiguration?

      def discount_configuration=: (
        MetronomeSDK::SpendThresholdConfigurationV2::DiscountConfiguration
      ) -> MetronomeSDK::SpendThresholdConfigurationV2::DiscountConfiguration

      def initialize: (
        commit: MetronomeSDK::BaseThresholdCommit,
        is_enabled: bool,
        payment_gate_config: MetronomeSDK::PaymentGateConfigV2,
        threshold_amount: Float,
        ?discount_configuration: MetronomeSDK::SpendThresholdConfigurationV2::DiscountConfiguration
      ) -> void

      def to_hash: -> {
        commit: MetronomeSDK::BaseThresholdCommit,
        is_enabled: bool,
        payment_gate_config: MetronomeSDK::PaymentGateConfigV2,
        threshold_amount: Float,
        discount_configuration: MetronomeSDK::SpendThresholdConfigurationV2::DiscountConfiguration
      }

      type discount_configuration =
        {
          payment_fraction: Float,
          cap: MetronomeSDK::SpendThresholdConfigurationV2::DiscountConfiguration::Cap
        }

      class DiscountConfiguration < MetronomeSDK::Internal::Type::BaseModel
        attr_accessor payment_fraction: Float

        attr_reader cap: MetronomeSDK::SpendThresholdConfigurationV2::DiscountConfiguration::Cap?

        def cap=: (
          MetronomeSDK::SpendThresholdConfigurationV2::DiscountConfiguration::Cap
        ) -> MetronomeSDK::SpendThresholdConfigurationV2::DiscountConfiguration::Cap

        def initialize: (
          payment_fraction: Float,
          ?cap: MetronomeSDK::SpendThresholdConfigurationV2::DiscountConfiguration::Cap
        ) -> void

        def to_hash: -> {
          payment_fraction: Float,
          cap: MetronomeSDK::SpendThresholdConfigurationV2::DiscountConfiguration::Cap
        }

        type cap = { amount: Float, spend_tracker_alias: String }

        class Cap < MetronomeSDK::Internal::Type::BaseModel
          attr_accessor amount: Float

          attr_accessor spend_tracker_alias: String

          def initialize: (amount: Float, spend_tracker_alias: String) -> void

          def to_hash: -> { amount: Float, spend_tracker_alias: String }
        end
      end
    end
  end
end
