module MetronomeSDK
  module Models
    type spend_threshold_configuration =
      {
        commit: MetronomeSDK::BaseThresholdCommit,
        is_enabled: bool,
        payment_gate_config: MetronomeSDK::PaymentGateConfig,
        threshold_amount: Float
      }

    class SpendThresholdConfiguration < MetronomeSDK::Internal::Type::BaseModel
      attr_accessor commit: MetronomeSDK::BaseThresholdCommit

      attr_accessor is_enabled: bool

      attr_accessor payment_gate_config: MetronomeSDK::PaymentGateConfig

      attr_accessor threshold_amount: Float

      def initialize: (
        commit: MetronomeSDK::BaseThresholdCommit,
        is_enabled: bool,
        payment_gate_config: MetronomeSDK::PaymentGateConfig,
        threshold_amount: Float
      ) -> void

      def to_hash: -> {
        commit: MetronomeSDK::BaseThresholdCommit,
        is_enabled: bool,
        payment_gate_config: MetronomeSDK::PaymentGateConfig,
        threshold_amount: Float
      }
    end
  end
end
