module MetronomeSDK
  module Models
    type spend_threshold_configuration_v2 =
      {
        commit: MetronomeSDK::UpdateBaseThresholdCommit,
        is_enabled: bool,
        payment_gate_config: MetronomeSDK::PaymentGateConfigV2,
        threshold_amount: Float
      }

    class SpendThresholdConfigurationV2 < MetronomeSDK::Internal::Type::BaseModel
      attr_accessor commit: MetronomeSDK::UpdateBaseThresholdCommit

      attr_accessor is_enabled: bool

      attr_accessor payment_gate_config: MetronomeSDK::PaymentGateConfigV2

      attr_accessor threshold_amount: Float

      def initialize: (
        commit: MetronomeSDK::UpdateBaseThresholdCommit,
        is_enabled: bool,
        payment_gate_config: MetronomeSDK::PaymentGateConfigV2,
        threshold_amount: Float
      ) -> void

      def to_hash: -> {
        commit: MetronomeSDK::UpdateBaseThresholdCommit,
        is_enabled: bool,
        payment_gate_config: MetronomeSDK::PaymentGateConfigV2,
        threshold_amount: Float
      }
    end
  end
end
