module MetronomeSDK
  module Models
    type tier = { price: Float, size: Float }

    class Tier < MetronomeSDK::Internal::Type::BaseModel
      attr_accessor price: Float

      attr_reader size: Float?

      def size=: (Float) -> Float

      def initialize: (price: Float, ?size: Float) -> void
    end
  end
end
