module MetronomeSDK
  module Models
    type update_base_threshold_commit =
      { description: String, name: String, product_id: String }

    class UpdateBaseThresholdCommit < MetronomeSDK::Internal::Type::BaseModel
      attr_reader description: String?

      def description=: (String) -> String

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader product_id: String?

      def product_id=: (String) -> String

      def initialize: (
        ?description: String,
        ?name: String,
        ?product_id: String
      ) -> void

      def to_hash: -> { description: String, name: String, product_id: String }
    end
  end
end
