module Metronome
  module Models
    module Contracts
      type product_archive_response = { data: Metronome::Models::ID }

      class ProductArchiveResponse < Metronome::BaseModel
        attr_accessor data: Metronome::Models::ID

        def initialize:
          (data: Metronome::Models::ID) -> void
          | (
            ?Metronome::Models::Contracts::product_archive_response
            | Metronome::BaseModel data
          ) -> void

        def to_h: -> Metronome::Models::Contracts::product_archive_response
      end
    end
  end
end
