module Metronome
  module Models
    module Contracts
      type product_archive_params =
        { product_id: String } & Metronome::request_parameters

      class ProductArchiveParams < Metronome::BaseModel
        extend Metronome::RequestParameters::Converter
        include Metronome::RequestParameters

        attr_accessor product_id: String

        def initialize:
          (product_id: String, request_options: Metronome::request_opts) -> void
          | (
            ?Metronome::Models::Contracts::product_archive_params
            | Metronome::BaseModel data
          ) -> void

        def to_h: -> Metronome::Models::Contracts::product_archive_params
      end
    end
  end
end
