module Metronome
  module Models
    module Contracts
      type rate_card_retrieve_params = {  } & Metronome::request_parameters

      class RateCardRetrieveParams < Metronome::Models::ID
        extend Metronome::RequestParameters::Converter
        include Metronome::RequestParameters

        def initialize:
          (request_options: Metronome::request_opts) -> void
          | (
            ?Metronome::Models::Contracts::rate_card_retrieve_params
            | Metronome::BaseModel data
          ) -> void

        def to_h: -> Metronome::Models::Contracts::rate_card_retrieve_params
      end
    end
  end
end
