module Metronome
  module Models
    module Contracts
      type rate_card_update_params =
        {
          rate_card_id: String,
          aliases: Array[Metronome::Models::Contracts::RateCardUpdateParams::Alias],
          description: String,
          name: String
        }
        & Metronome::request_parameters

      class RateCardUpdateParams < Metronome::BaseModel
        extend Metronome::RequestParameters::Converter
        include Metronome::RequestParameters

        attr_accessor rate_card_id: String

        attr_reader aliases: Array[Metronome::Models::Contracts::RateCardUpdateParams::Alias]?

        def aliases=: (
          Array[Metronome::Models::Contracts::RateCardUpdateParams::Alias]
        ) -> void

        attr_reader description: String?

        def description=: (String) -> void

        attr_reader name: String?

        def name=: (String) -> void

        def initialize:
          (
            rate_card_id: String,
            aliases: Array[Metronome::Models::Contracts::RateCardUpdateParams::Alias],
            description: String,
            name: String,
            request_options: Metronome::request_opts
          ) -> void
          | (
            ?Metronome::Models::Contracts::rate_card_update_params
            | Metronome::BaseModel data
          ) -> void

        def to_hash: -> Metronome::Models::Contracts::rate_card_update_params

        type alias_ = { name: String, ending_before: Time, starting_at: Time }

        class Alias < Metronome::BaseModel
          attr_accessor name: String

          attr_reader ending_before: Time?

          def ending_before=: (Time) -> void

          attr_reader starting_at: Time?

          def starting_at=: (Time) -> void

          def initialize:
            (name: String, ending_before: Time, starting_at: Time) -> void
            | (
              ?Metronome::Models::Contracts::RateCardUpdateParams::alias_
              | Metronome::BaseModel data
            ) -> void

          def to_hash: -> Metronome::Models::Contracts::RateCardUpdateParams::alias_
        end
      end
    end
  end
end
