module Metronome
  module Models
    module Contracts
      type rate_card_retrieve_rate_schedule_params =
        {
          rate_card_id: String,
          starting_at: Time,
          limit: Integer,
          next_page: String,
          ending_before: Time,
          selectors: Array[Metronome::Models::Contracts::RateCardRetrieveRateScheduleParams::Selector]
        }
        & Metronome::request_parameters

      class RateCardRetrieveRateScheduleParams < Metronome::BaseModel
        extend Metronome::RequestParameters::Converter
        include Metronome::RequestParameters

        attr_accessor rate_card_id: String

        attr_accessor starting_at: Time

        attr_reader limit: Integer?

        def limit=: (Integer) -> void

        attr_reader next_page: String?

        def next_page=: (String) -> void

        attr_reader ending_before: Time?

        def ending_before=: (Time) -> void

        attr_reader selectors: Array[Metronome::Models::Contracts::RateCardRetrieveRateScheduleParams::Selector]?

        def selectors=: (
          Array[Metronome::Models::Contracts::RateCardRetrieveRateScheduleParams::Selector]
        ) -> void

        def initialize:
          (
            rate_card_id: String,
            starting_at: Time,
            limit: Integer,
            next_page: String,
            ending_before: Time,
            selectors: Array[Metronome::Models::Contracts::RateCardRetrieveRateScheduleParams::Selector],
            request_options: Metronome::request_opts
          ) -> void
          | (
            ?Metronome::Models::Contracts::rate_card_retrieve_rate_schedule_params
            | Metronome::BaseModel data
          ) -> void

        def to_h: -> Metronome::Models::Contracts::rate_card_retrieve_rate_schedule_params

        type selector =
          {
            partial_pricing_group_values: Hash[Symbol, String],
            pricing_group_values: Hash[Symbol, String],
            product_id: String
          }

        class Selector < Metronome::BaseModel
          attr_reader partial_pricing_group_values: Hash[Symbol, String]?

          def partial_pricing_group_values=: (Hash[Symbol, String]) -> void

          attr_reader pricing_group_values: Hash[Symbol, String]?

          def pricing_group_values=: (Hash[Symbol, String]) -> void

          attr_reader product_id: String?

          def product_id=: (String) -> void

          def initialize:
            (
              partial_pricing_group_values: Hash[Symbol, String],
              pricing_group_values: Hash[Symbol, String],
              product_id: String
            ) -> void
            | (
              ?Metronome::Models::Contracts::RateCardRetrieveRateScheduleParams::selector
              | Metronome::BaseModel data
            ) -> void

          def to_h: -> Metronome::Models::Contracts::RateCardRetrieveRateScheduleParams::selector
        end
      end
    end
  end
end
