module Metronome
  module Models
    module Contracts
      type rate_card_list_params =
        { body: top, limit: Integer, next_page: String }
        & Metronome::request_parameters

      class RateCardListParams < Metronome::BaseModel
        extend Metronome::RequestParameters::Converter
        include Metronome::RequestParameters

        attr_accessor body: top

        attr_reader limit: Integer?

        def limit=: (Integer) -> void

        attr_reader next_page: String?

        def next_page=: (String) -> void

        def initialize:
          (
            body: top,
            limit: Integer,
            next_page: String,
            request_options: Metronome::request_opts
          ) -> void
          | (
            ?Metronome::Models::Contracts::rate_card_list_params
            | Metronome::BaseModel data
          ) -> void

        def to_h: -> Metronome::Models::Contracts::rate_card_list_params
      end
    end
  end
end
