module Metronome
  module Models
    module Contracts
      type rate_card_update_response = { data: Metronome::Models::ID }

      class RateCardUpdateResponse < Metronome::BaseModel
        attr_accessor data: Metronome::Models::ID

        def initialize:
          (data: Metronome::Models::ID) -> void
          | (
            ?Metronome::Models::Contracts::rate_card_update_response
            | Metronome::BaseModel data
          ) -> void

        def to_hash: -> Metronome::Models::Contracts::rate_card_update_response
      end
    end
  end
end
